- test/io/io.go
- test/io/io_test.go
copy from nuts-foundation/nuts-go-test
> added nuts-go-test

- cmd/root.go
- cmd/root_test.go
- core/config.go
- core/config_test.go
- core/diagnostics.go
- core/engine.go
- core/engine_test.go
- core/mock.go
- core/status.go
- core/status_test.go
- crypto/mock.go
- makefile
Replaced with System type which isn't a singleton.
> Removed EngineCtl singleton to improve testability and isolation

- crypto/interface.go
- crypto/jwx.go
- crypto/jwx_test.go
- crypto/mock.go
- crypto/test.go
- network/api/v1/api_test.go
- network/api/v1/client_test.go
- network/dag/bboltdag_test.go
- network/dag/dag_contract_test.go
- network/dag/dag_test.go
- network/dag/document.go
- network/dag/document_test.go
- network/dag/parser.go
- network/dag/parser_test.go
- network/dag/signing.go
- network/dag/signing_test.go
- network/dag/sigverifier.go
- network/dag/sigverifier_test.go
- network/dag/test.go
- network/engine/engine_test.go
- network/network.go
- network/network_integration_test.go
- network/network_test.go
- network/proto/handlers.go
- network/proto/impl.go
- network/proto/interface.go
- network/proto/mock.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/25
Based on https://github.com/nuts-foundation/nuts-node/pull/27 (must be merged first)
> Verify documents signatures upon receiving before adding them to the DAG

- development/docker-compose.yaml
image: nuts -> nuts-node
added anchors to image
> Fixed image in docker-compose

- core/status.go
- core/status_test.go
- test/matchers.go
> Added uptime diagnostic to status engine

- docs/conf.py
css has to be added through sphinx setup
> add swagger css to readthedocs

- network/p2p/impl-connection.go
- network/p2p/impl-peer.go
- network/p2p/impl.go
- network/p2p/interface.go
- network/p2p/mock.go
- network/p2p/stats.go
- network/proto/impl.go
> Network: Show peer address in diagnostics

- core/client_config.go
- core/client_config_test.go
- crypto/cmd/cmd.go
- network/cmd/cmd.go
- network/p2p/impl.go
- network/p2p/stats.go
- vdr/cmd/cmd.go
- vdr/cmd/cmd_test.go
> Fix 121 address param

- vcr/api/v1/api.go
- vcr/api/v1/api_test.go
- vdr/resolvers.go
- vdr/resolvers_test.go
- vdr/types/common.go
- vdr/types/interface.go
> Handle specific error codes when creating VCs through the API

- vcr/credential/builder.go
- vcr/credential/builder_test.go
> VCR: Only add default VC type if not present

- vcr/concept/template.go
- vcr/concept/template_test.go
> ignore slices when transforming VCs to concepts

- auth/api/experimental/api_test.go
- auth/api/v0/api_test.go
- auth/services/contract/notary_test.go
- auth/services/irma/signer_test.go
- auth/services/irma/validator.go
- auth/services/oauth/oauth_test.go
- auth/services/util_test.go
- vcr/credential/builder_test.go
- vcr/credential/validator_test.go
- vcr/vcr_test.go
- vdr/resolvers_test.go
- vdr/test.go
Describes what it is for instead of how we created it.
> Rename (Alt)RandomDID to TestDIDA and B

- vcr/api/v1/api_test.go
- vcr/assets/NutsOrganizationCredential.json.template
- vcr/concept/registry.go
- vcr/concept/registry_test.go
- vcr/concept/template_test.go
- vcr/concept/test.go
- vcr/credential/types.go
- vcr/credential/types_test.go
- vcr/vcr_test.go
> VCR: renamed 'company' concept to 'organization', fix marshalling

- vdr/ambassador.go
- vdr/ambassador_test.go
> VDR: Validate service ID

- auth/services/x509/uzi_validator_test.go
- crypto/jwx_test.go
- docs/_static/vdr/v1.yaml
- vdr/ambassador.go
- vdr/ambassador_test.go
- vdr/api/v1/api.go
- vdr/api/v1/api_test.go
- vdr/api/v1/client.go
- vdr/api/v1/client_test.go
- vdr/api/v1/generated.go
- vdr/cmd/cmd.go
- vdr/cmd/cmd_test.go
- vdr/integration_test.go
- vdr/types/common.go
- vdr/types/common_test.go
- vdr/types/interface.go
- vdr/types/mock.go
- vdr/vdr.go
- vdr/vdr_test.go
Adds the CLI and API `Deactivate` commands.
Adds the deactivated status to the resolvemetadata.
> Add cli and API DID deactivation

- network/dag/bbolt_dag.go
- network/dag/bbolt_dag_test.go
> Network: implemented datastore size statistic

- auth/api/experimental/generated.go
- auth/api/v0/generated.go
- crypto/api/v1/generated.go
- crypto/interface.go
- crypto/jwx.go
- crypto/jwx_test.go
- docs/_static/vdr/v1.yaml
- network/api/v1/generated.go
- vcr/api/v1/generated.go
- vdr/api/v1/api.go
- vdr/api/v1/api_test.go
- vdr/test.go
- vdr/types/common.go
- vdr/types/interface.go
- vdr/vdr.go
- vdr/vdr_test.go
Add ErrDIDNotManagedByThisNode
Handle deactivated errors in api.
Improved vdr interfaces with errors descriptions.
> Improve VDR error handling

- auth/auth.go
- auth/services/contract/notary.go
- auth/services/contract/notary_test.go
> fix broken notary instantiating

- README.rst
- README_template.rst
* Correct link to the documentation
* Add docker build badge to the readme template
> Fix readme badges

- network/cmd/cmd.go
- network/cmd/cmd_test.go
- network/dag/test.go
`nuts network list --sort=time`
`nuts network list --sort=type`
> Add CLI sort flag to network list

- auth/services/irma/irmaconfig.go
- auth/services/irma/irmaconfig_test.go
- auth/services/validator/validator.go
> removed irma singleton config

- auth/auth.go
- auth/services/contract/notary_test.go
- auth/services/irma/signer.go
- auth/services/irma/signer_test.go
- auth/services/irma/validator.go
- auth/services/validator/validator.go
- vcr/ambassador_test.go
- vcr/api/v1/api.go
- vcr/api/v1/api_test.go
- vcr/concept/mock.go
- vcr/concept/registry.go
- vcr/concept/registry_test.go
- vcr/concept/template_test.go
- vcr/concept/test.go
- vcr/credential/types.go
- vcr/interface.go
- vcr/mock.go
- vcr/vcr.go
- vcr/vcr_test.go
> Re-enable Irma contract validation

- auth/services/irma/signer.go
- auth/services/irma/signer_test.go
- auth/services/irma/validator.go
- auth/services/types.go
This was old code, now an extra step is required: createJwtBearerToken which does all the checks
Fixes #196
> Removed signing of nuts_auth_token when getting session status from Irma

- go.mod
- go.sum
https://github.com/privacybydesign/irmago/releases/tag/v0.7.0
Fixes #171
> Updates irmago to v0.7.0

- auth/services/contract/notary.go
- auth/services/contract/notary_test.go
- auth/services/irma/signer.go
- auth/services/irma/signer_test.go
- auth/services/irma/validator.go
- auth/services/oauth/oauth.go
- auth/services/oauth/oauth_test.go
- auth/services/validator/validator.go
- go.sum
Closes #91 
Apparently already covered by the VP validation. There the actor DID is used to resolve an organization concept. The concept values (name/city) are then compared to the contract values.
> Removed validation from notary

- .github/workflows/build-images.yaml
- Dockerfile
- cmd/root.go
- core/build_vars.go
- core/build_vars_test.go
- core/status/engine.go
- core/status/engine_test.go
- makefile
> added git tag, branch and hash. Also added Os/Arch to diagnostics

- auth/services/irma/irmaconfig.go
> Auth: moved IRMA client URL to /public

- auth/services/irma/irmaconfig.go
- auth/services/irma/irmacontract.go
- cmd/root.go
- core/client_config.go
- core/client_config_test.go
- core/status/cmd.go
- crypto/cmd/cmd.go
- crypto/crypto.go
- network/cmd/cmd.go
- network/dag/bbolt_dag.go
- network/network.go
- network/p2p/impl-connection.go
- network/p2p/impl.go
- network/proto/handlers.go
- vcr/ambassador.go
- vcr/cmd/cmd.go
- vcr/cmd/cmd_test.go
- vcr/vcr.go
- vdr/ambassador.go
- vdr/cmd/cmd.go
- vdr/cmd/cmd_test.go
- vdr/vdr.go
Fixes #40 
- No more `Fatal` (except for 1 single place where I couldn't trigger it)
- Correct usage of levels
- Tested setting level through `verbosity` config flag
- Consistent log format of parameters
> Made logging consistent

- auth/api/v1/api.go
- auth/api/v1/api_test.go
- auth/api/v1/generated.go
- auth/services/messages.go
- auth/services/oauth/oauth.go
- auth/services/oauth/oauth_test.go
- auth/services/util.go
- auth/services/util_test.go
- docs/_static/auth/v1.yaml
Closes #83 
Waiting for nuts-foundation/nuts-specification#51
> use compound service for oauth endpoint resolution

- network/dag/parser.go
- network/dag/parser_test.go
- network/dag/signing.go
- network/dag/signing_test.go
- network/dag/transaction.go
- network/dag/transaction_test.go
- vdr/ambassador.go
- vdr/ambassador_test.go
- vdr/cmd/cmd_test.go
- vdr/doc-updater_test.go
- vdr/types/common.go
- vdr/types/common_test.go
- vdr/types/interface.go
- vdr/vdr.go
- vdr/vdr_test.go
> removed tiv and tid

- auth/services/oauth/oauth.go
- auth/services/oauth/oauth_test.go
- auth/services/util_test.go
Closes #215 
After merge fix oauth e2e test
> Validate aud when creating accesstoken

- docs/pages/getting-started/configure-your-node.rst
- docs/pages/getting-started/running-a-node.rst
- docs/pages/getting-started/running-docker.rst
- makefile
closes #239 
also fixed makefile
> Extended getting started documentation

- auth/services/oauth/oauth_test.go
- go.mod
- go.sum
- vdr/ambassador.go
- vdr/ambassador_test.go
- vdr/doc-updater.go
- vdr/doc-updater_test.go
- vdr/doc/creator.go
- vdr/doc/creator_test.go
- vdr/doc/resolvers.go
- vdr/doc/resolvers_test.go
- vdr/integration_test.go
- vdr/store/common.go
- vdr/store/memory.go
- vdr/test/diddocument.json
- vdr/types/interface.go
- vdr/types/mock.go
- vdr/vdr.go
- vdr/vdr_test.go
Closes #221
There was duplication of controller resolution between VDR and ambassador. Used #227 as basis since it resolves part of the requirements.
> Iss221 remove controller recursion

- network/dag/transaction.go
- network/dag/transaction_test.go
- network/interface.go
- network/mock.go
- network/network.go
- network/network_integration_test.go
- network/network_test.go
- network/p2p/impl.go
- network/p2p/interface.go
- vcr/vcr.go
- vcr/vcr_test.go
- vdr/ambassador.go
- vdr/ambassador_test.go
- vdr/doc-updater_test.go
- vdr/types/interface.go
- vdr/vdr.go
- vdr/vdr_test.go
> Complete did.Document conflict resolution integration

- auth/services/contract/notary.go
- auth/services/contract/notary_test.go
- auth/services/oauth/oauth.go
- auth/services/oauth/oauth_test.go
- auth/services/validator/validator.go
- crypto/crypto.go
- crypto/crypto_test.go
- crypto/interface.go
- crypto/mock.go
Public key resolvement has already been moved to the VDR.
This was some leftover code.
> remove public keystore

- crypto/jwx.go
- crypto/jwx_test.go
- vdr/ambassador.go
- vdr/ambassador_test.go
- vdr/doc/creator.go
- vdr/doc/creator_test.go
> altered DID Document check according to RFC006

- Dockerfile
older image had 12 security vulnerabilities
> updated docker image

- network/proto/handlers_test.go
- network/proto/senders_mock.go
- network/transport/network.pb.go
Some mocks were not updated and method signatures were wrong.
> ran generators and fixed tests

- cmd/root.go
- vdr/doc/creator_test.go
- vdr/doc/manipulator.go
- vdr/doc/manipulator_test.go
- vdr/doc/resolvers_test.go
- vdr/doc/test.go
- vdr/integration_test.go
- vdr/vdr_test.go
So that it conforms to the rest of the DID document operations
> VDR: Move "DocUpdater" to "doc" package and rename to Manipulator 

- vcr/test.go
- vcr/trust/trust.go
- vcr/vcr.go
- vcr/vcr_test.go
> Autotrust issuer when issuing VC

- network/p2p/impl.go
- network/p2p/impl_test.go
> Network: reverted accidental struct rename

- didman/api/v1/api.go
- didman/api/v1/api_test.go
- didman/api/v1/generated.go
- didman/didman.go
- didman/didman_test.go
- didman/mock.go
- didman/types.go
- docs/_static/didman/v1.yaml
Fixes https://github.com/nuts-foundation/nuts-node/issues/280
> DIDMan: API for adding a compound service

- auth/services/uzi/validator.go
- didman/api/v1/api.go
- didman/didman.go
- vdr/ambassador.go
- vdr/ambassador_test.go
- vdr/cmd/cmd_test.go
- vdr/integration_test.go
- vdr/vdr.go
- vdr/vdr_test.go
It has annoyed me long enough now.
> Use correct casing for 'did', follow Go stdlib in spelling of 'marshal'

- README.rst
- docs/pages/development/development.rst
Improved consistency, renamed "Dependencies" (which sounds like Go modules/libraries) to "Requirements".
> Polished development docs

- docs/_static/vdr/v1.yaml
- vdr/ambassador.go
- vdr/ambassador_test.go
- vdr/api/v1/api.go
- vdr/api/v1/api_test.go
- vdr/doc/creator.go
- vdr/doc/manipulator.go
- vdr/doc/manipulator_test.go
- vdr/validators.go
- vdr/vdr.go
- vdr/vdr_test.go
Fixes #305 
More checks will be added by https://github.com/nuts-foundation/nuts-node/pull/310
> VDR: Validate DID Document before publishing the update transaction

- auth/services/util.go
- didman/didman.go
- go.mod
- go.sum
- vdr/api/v1/api.go
- vdr/api/v1/api_test.go
- vdr/doc/creator.go
- vdr/doc/creator_test.go
- vdr/doc/manipulator.go
- vdr/doc/manipulator_test.go
- vdr/doc/resolvers.go
- vdr/doc/resolvers_test.go
- vdr/test.go
- vdr/vdr_test.go
replaced all ParseDID with ParseDIDURL where needed
> Update godid dep

- docs/pages/api.rst
> added didman OAS to swagger UI

- Dockerfile
> Fix Docker build by upgrading musl-dev pkg

- vdr/ambassador_test.go
Based on https://github.com/nuts-foundation/nuts-node/pull/318 (merge first)
> VDR: Rename a few missed subscriberDocuments to transaction

- docs/pages/getting-started/5-irma-contract.rst
Some details might be missing, but we'll know when it's used.
> IRMA manual

- network/dag/bbolt_dag.go
- network/dag/bbolt_dag_test.go
> Fix bbolt dag diagnostics test

- .circleci/config.yml
- README.rst
- README_template.rst
closes #357 
check the beautiful check marks in the build overview
> first trial run for codeclimate coverage

- docs/index.rst
- docs/pages/development/3-vc.rst
- vcr/assets/NutsAuthorizationCredential.json.template
- vcr/credential/resolver.go
- vcr/credential/resolver_test.go
- vcr/credential/types.go
- vcr/credential/validator.go
- vcr/credential/validator_test.go
Closes #362 
This PR adds the NutsAuthorizationCredential template and validator.
Also fixed development documentation not loading correctly on readTheDocs
> Added support for NutsAuthorizationCredential

- README.rst
- auth/api/v1/api.go
- auth/api/v1/api_test.go
- auth/api/v1/client.go
- auth/api/v1/client_test.go
- auth/api/v1/generated.go
- auth/auth.go
- auth/cmd/cmd.go
- auth/config.go
- auth/interface.go
- auth/mock.go
- auth/services/messages.go
- auth/services/mock.go
- auth/services/oauth/oauth.go
- auth/services/oauth/oauth_test.go
- auth/services/services.go
- cmd/root.go
- core/echo_errors.go
- docs/_static/auth/v1.yaml
- makefile
Note that this is a draft PR (all unittests are missing for example). I'd like to get some early feedback before finishing everything up.
- Renamed JWT Bearer Token -> JWT Grant as the JWT will be used as an authorization grant specified in RFC7523.
- Added request token endpoint
> Implement new oauth flow

- .github/workflows/e2e-tests.yaml
Fixes #382
we'll now if it works for master after merging ;)
> set env.SHA so e2e tests work for both branches and PRs

- docs/pages/getting-started/6-adding-authorizations.rst
- docs/pages/technology/vc-concepts.rst
The added manual describes how to add and search for a authorization credential
waiting for #378
This PR only adds the new manual. Please only review the `6-adding-authorizations.rst` file
> Add authorization manual

- didman/didman.go
- didman/didman_test.go
Incorrect typecast of concept.
> DIDMan: fix organization search

- .github/dependabot.yml
closes #381 
let Dependabot check for updates
> Move to Dependabot 

- .github/workflows/e2e-tests.yaml
> e2e image push step with specific secret

- docs/_static/auth/v1.yaml
- docs/_static/didman/v1.yaml
- docs/_static/vdr/v1.yaml
> Add tags to OAS files

- auth/api/v1/api_test.go
- auth/api/v1/generated.go
- docs/_static/auth/v1.yaml
fixes #461 
some leftover OIDs that should have been DIDs
> remove oid refs from docs

- crypto/jwx.go
- crypto/jwx_test.go
part of #484
adds 5 seconds of clock skew
> allow for clock skew when creating access token

- network/dag/bbolt_dag.go
- network/dag/bbolt_payloadstore.go
- network/dag/util.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/489
Not sure how to unit test this.
Will make a test to check whether this fixes the appearant memory corruption.
> Copy BBolt slices before sharing them outside of TX bounds

- vcr/vcr.go
- vcr/vcr_test.go
Currently allows for 5 seconds max
> Fix credential clock skew

- auth/api/v1/generated.go
- docs/_static/auth/v1.yaml
- network/network_integration_test.go
fixes #498 
was there incorrectly
> remove usi from introspection

- network/p2p/connection_test.go
This small change seems to help in getting a more stable build
> trying to have more stable test

- core/server_config.go
- core/server_config_test.go
Allows to set it to `text` or `json`.
> Add loggerFormat to config

- auth/contract/template.go
Fixes #602 
this will allow use of the demo email attribute in combination with the demo gemeente attributes.
> update email attr def in contract

- core/diagnostics.go
- core/diagnostics_test.go
- core/status/engine.go
- core/status/engine_test.go
- docs/pages/monitoring.rst
- network/dag/bbolt_dag.go
- network/dag/bbolt_dag_test.go
- network/network_test.go
- network/transport/grpc/stats.go
- network/transport/grpc/stats_test.go
- network/transport/v1/logic/impl.go
- network/transport/v1/logic/impl_test.go
- network/transport/v1/logic/stats.go
- vcr/config.go
- vdr/config.go
- vdr/vdr.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/468
Example JSON output:
```
{
"Network": {
"[DAG] Heads": [
"d9217dfe685edc65e3b51303ce14292f6572140b197488bc3e8300d54792f017"
],
"[DAG] Number of transactions": 664,
"[DAG] Stored database size (bytes)": 0,
"[P2P Network] Connected peers": [
{
"ID": "0c1b8600-b4b4-4c3f-a643-cfe84ebfc7a3",
"Address": "128.199.61.173:39090"
},
{
"ID": "799d1b42-2926-4a0d-bce4-f7e8abd38d77",
"Address": "nuts.woutslakhorst.nl:5555"
},
{
"ID": "b395c279-2b7d-4f99-9151-b98959635a99",
"Address": "128.199.61.173:55114"
},
{
"ID": "a5c2009e-f018-4102-9fd3-9738ea09487e",
"Address": "89.184.189.226:48732"
},
{
"ID": "3d2c4fb1-cc12-4a98-b7e8-d6897f5ae2c6",
"Address": "128.199.61.173:39392"
},
{
"ID": "ebbd8f0b-8cb6-466c-af29-95c6f3fcfd40",
"Address": …
```
> Core: allow diagnostics to be retrieved in JSON format

- Dockerfile
deps were out-of-date again....
> update docker image deps

- cmd/root.go
- network/network.go
- network/network_test.go
- network/test.go
- vdr/integration_test.go
> Network: supply DID Document Resolver (nil deref)

- vdr/ambassador.go
- vdr/ambassador_test.go
> Now really fix stable order for metadata.SourceTransactions

- vdr/cmd/cmd.go
- vdr/cmd/cmd_test.go
Required for configuring Node DID.
> VDR: Provide convenience CLI command to register keyAgreement

- .github/workflows/e2e-tests.yaml
waiting for a dependabot PR to try this one
Fixes #646
> different token with permissions for dependabot

- crypto/decrypter_test.go
- crypto/ecies.go
- crypto/ecies_test.go
- network/dag/pal.go
- network/dag/pal_test.go
- network/transport/connection_manager_test.go
- network/transport/grpc/authenticator.go
- network/transport/grpc/authenticator_test.go
- network/tx.go
- vdr/doc/util.go
- vdr/doc/util_test.go
We need a build step to check this...
> Fixed copyrights

- docs/pages/getting-started/3-configure-your-node.rst
- docs/pages/getting-started/6-adding-authorizations.rst
Fixes https://github.com/nuts-foundation/nuts-node/issues/685
> Document node DID and NutsComm

- network/transport/grpc/connection_manager.go
Forgot to log the actual error.
> Network: log node DID authentication errors

- network/network.go
- network/network_integration_test.go
- network/network_test.go
- network/transport/grpc/authenticator.go
- network/transport/types.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/686
> Network: return operator-friendly error when creating private TXs when node DID isn't configured

- network/dag/pal.go
- network/transport/v2/handlers.go
- network/transport/v2/handlers_test.go
- network/transport/v2/protocol.go
- network/transport/v2/protocol_test.go
closes #709 
merging will conflict with #708 
This PR has splitted handlePrivateTx better.
#708 has better error message for handlePrivateTx.
> added assertion of peer nodeDID when requesting private TX

- network/transport/v1/logic/impl.go
- network/transport/v1/logic/impl_test.go
Thought this might be a problem in the current build failing now and then (deadlock), but on a second thought it's probably not the cause. Fixed it nonetheless.
Fixes https://github.com/nuts-foundation/nuts-node/issues/480
> Network: properly shutdown goroutines in v1 protocol

- events/subjects.go
- events/test.go
- network/dag/publisher.go
- network/dag/publisher_test.go
- network/network.go
- Fix NATS publisher nil ref
- Add stream for the private transactions (thus closes #711)
> Fix NATS publisher nil ref and add stream for the subject

- network/transport/grpc/connection.go
- network/transport/grpc/connection_manager.go
- network/transport/grpc/connection_manager_test.go
- network/transport/grpc/connection_mock.go
- network/transport/grpc/interface.go
- network/transport/grpc/interface_mock.go
- network/transport/grpc/test.go
- network/transport/grpc/testprotocol_impl.pb.go
- network/transport/v1/protocol.go
- network/transport/v2/protocol.go
Closes: https://github.com/nuts-foundation/nuts-node/issues/723
> Actually set the authenticated peer on the connection

- events/event_test.go
- network/transport/grpc/connection.go
- network/transport/grpc/connection_list.go
- network/transport/grpc/connection_list_test.go
- network/transport/grpc/connection_manager.go
- network/transport/grpc/connection_manager_test.go
- network/transport/grpc/connection_mock.go
- network/transport/grpc/connection_test.go
- network/transport/grpc/predicate.go
- network/transport/grpc/predicate_test.go
- network/transport/grpc/test.go
- network/transport/v1/logic/impl.go
- network/transport/v1/logic/impl_test.go
- network/transport/v1/protocol.go
See https://github.com/nuts-foundation/nuts-node/pull/683
> After-merge PR feedback on gRPC refactor

- network/network.go
- network/network_integration_test.go
- network/network_test.go
- network/transport/v1/logic/blocks.go
- network/transport/v1/logic/blocks_test.go
- network/transport/v1/logic/handlers_test.go
- vcr/interface.go
- vdr/ambassador.go
- vdr/store/bbolt_test.go
This PR is just to make sure all listeners to the dag.Publisher can handle duplicate callbacks.
After merge create issue to handle ever growing processed maps.
> added robustness checks and tests

- network/dag/publisher_test.go
`nil` was passed previously, which was errornuous.
> Network: fix publisher tests passed value for payloadWritten

- network/network_integration_test.go
- network/transport/v2/handlers.go
- network/transport/v2/handlers_test.go
- network/transport/v2/protocol.go
- network/transport/v2/protocol_test.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/737
Fixes #720 
Based on https://github.com/nuts-foundation/nuts-node/pull/712
> Network: broadcast TransactionPayloadQuery to all private TX participants

- docs/_static/didman/v1.yaml
- docs/_static/vcr/v1.yaml
- docs/_static/vdr/v1.yaml
Fixes https://github.com/nuts-foundation/nuts-node/issues/763
> Fix OpenAPI examples being lists

- vdr/vdr.go
- vdr/vdr_test.go
> Don't create a transaction when a document updates without changes

- network/transport/grpc/connection.go
When a peer disconnects `Recv()` returns `io.EOF`.  This should be logged as the peer disconnecting normally.
> Network: don't log peer disconnecting as error

- events/conn_test.go
a test created a new dir in our source tree
> remove locally generated dir in code tree by test

- network/transport/v2/protocol.go
- network/transport/v2/protocol_test.go
The problem was that the v1 protocol already started the connection manager. Causing a connection to be established which tried to call a callback on the v2 protocol which hadn't started yet.....
> fix race condition in protocol test

- docs/_static/vdr/v1.yaml
- vcr/api/v2/generated.go
> Fix for inconsistency in generated APIs vs go-did implementation

- docs/_static/vcr/v2.yaml
- makefile
- vcr/api/v2/api.go
- vcr/api/v2/api_test.go
- vcr/api/v2/generated.go
- vcr/api/v2/types.go
- vcr/holder/holder.go
- vcr/holder/holder_test.go
- vcr/holder/interface.go
- vcr/interface.go
- vcr/mock.go
- vcr/vcr.go
- vcr/verifier/interface.go
- vcr/verifier/leia_store.go
- vcr/verifier/leia_store_test.go
- vcr/verifier/mock.go
- vcr/verifier/verifier.go
- vcr/verifier/verifier_test.go
- vdr/test.go
Based on https://github.com/nuts-foundation/nuts-node/pull/844
> VCR: Support verifying VPs

- vcr/issuer/issuer.go
- vcr/issuer/issuer_test.go
- vcr/vcr.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/883
> VCR: Auto-trust VCs issued by local node

- docs/_static/vcr/v2.yaml
- vcr/api/v2/api.go
- vcr/api/v2/api_test.go
- vcr/api/v2/generated.go
Just a copy from v1, since that will be removed in future.
> VCR: Add trust-related calls to v2

- docs/_static/vcr/v2.yaml
- vcr/api/v2/generated.go
> VCR: return application/json from v2 api instead of application/ld+json

- docs/pages/development/3-vc.rst
- docs/pages/getting-started/4-connecting-crm.rst
- docs/pages/getting-started/6-adding-authorizations.rst
Fixes https://github.com/nuts-foundation/nuts-node/issues/886
> Docs: rewrite getting started to use VCR v2 API

- auth/services/oauth/oauth_test.go
- didman/api/v1/client_test.go
- didman/didman_test.go
- network/transport/grpc/authenticator_test.go
- vcr/api/v1/api_test.go
- vcr/api/v2/api_test.go
- vcr/concept/registry_test.go
- vcr/credential/builder.go
- vcr/credential/builder_test.go
- vcr/credential/test.go
- vcr/issuer/issuer.go
- vcr/issuer/issuer_test.go
- vcr/issuer/leia_store_test.go
- vcr/issuer/network_publisher.go
- vcr/issuer/network_publisher_test.go
- vcr/signature/proof/jsonld.go
- vcr/trust/trust.go
- vcr/trust/trust_test.go
- vcr/vcr_test.go
- vcr/verifier/verifier_test.go
- vdr/doc/merge_test.go
- vdr/doc/resolvers.go
- vdr/doc/resolvers_test.go
- vdr/doc/util_test.go
- vdr/validators_test.go
> Replace ParseURI with MustParseURI where returned error is ignored

- auth/api/v1/api.go
> Auth: log warning when an invalid token is offered for introspection

- docs/pages/development/3-vc.rst
- docs/pages/getting-started/6-adding-authorizations.rst
> fix vcr search paths in docs

- vcr/api/v2/registry.go
- vcr/api/v2/registry_test.go
Used by Demo EHR when searching for applicable `NutsAuthorizationCredential`s.
> VCR: Support searching on credential issuer on v2 API

- docs/pages/release_notes.rst
Added sub-sections that should be present every release. Instead of filling them with issues, I added some explanation to them.
> first release notes

- auth/services/oauth/oauth_test.go
- vcr/credential/validator.go
- vcr/credential/validator_test.go
> VCR: Validate Nuts VC ID is according to the specified format

- vcr/store.go
- vcr/store_test.go
> VCR: Assert that VC IDs are unique

- vcr/api/v2/api.go
- vcr/api/v2/api_test.go
- vcr/issuer/interface.go
- vcr/issuer/issuer.go
- vcr/verifier/interface.go
- vcr/verifier/leia_store.go
- vcr/verifier/leia_store_test.go
- vcr/verifier/mock.go
- vcr/verifier/verifier.go
- vcr/verifier/verifier_test.go
> add revocation status to searchIssuedVcs

- network/network.go
- network/network_test.go
Fixes #934 
Rationale: the linked issue occurs on nodes that auto-resolve the node DID (typically outdated nodes or nodes with outdated DID documents), which is only allowed in non-strict mode. In strict mode (aka production) node DID **must** be configured, and then the error should be blocking.
Letting the node start with auto-resolved node DID which is invalid allows operators in dev/test environments to fix the issue using the API/CLI.
> Network: only return error when node DID is invalid in strict mode

- auth/api/v1/api.go
- auth/api/v1/api_test.go
- auth/api/v1/generated.go
- cmd/root.go
- docs/_static/auth/v1.yaml
> Auth: resolve access token VCs when introspecting tokens

- vcr/api/v2/api.go
- vcr/api/v2/api_test.go
- vcr/signature/proof/jsonld.go
- vcr/signature/proof/jsonld_test.go
- vcr/signature/proof/legacy_test.go
- vcr/verifier/verifier.go
> VCR: rename expirationDate to expires in LDProof

- docs/_static/vcr/v2.yaml
> VCR: Fix type definition in API spec

- network/transport/v2/gossip/manager_test.go
> Network: changed test to use less waitgroups and count the number of routines running

- network/dag/bbolt_dag.go
- network/dag/bbolt_dag_test.go
- network/dag/interface.go
- network/dag/mock.go
- network/dag/state.go
- network/dag/state_test.go
- network/transport/v2/handlers.go
- network/transport/v2/handlers_test.go
- network/transport/v2/senders.go
- network/transport/v2/senders_test.go
closes #951
Query state for LC, XOR, IBLT and uses these to complete the Gossip message
> Network: query state and complete gossip messages

- docs/_static/vcr/v2.yaml
- vcr/api/v2/api.go
- vcr/api/v2/api_test.go
- vcr/api/v2/generated.go
> remove format from VCR OAS

- cmd/root.go
- jsonld/document_test.go
- jsonld/reader_test.go
- jsonld/test.go
- vcr/api/v2/api.go
- vcr/api/v2/api_test.go
- vcr/api/v2/registry.go
- vcr/api/v2/registry_test.go
- vcr/assets/assets/contexts/nuts.ldjson
- vcr/assets/assets/default.index.yaml
- vcr/assets/test_assets/contexts/test.ldjson
- vcr/verifier/verifier_test.go
Also fixed the Nuts specific context for org/auth credentials.
> VCR V2 API JSON-LD usage

- auth/contract/template_test.go
> Auth: fix contract render test by using same clock

- network/dag/state.go
- network/dag/state_test.go
- network/network.go
- network/network_integration_test.go
- network/transport/v2/conversation.go
- network/transport/v2/conversation_test.go
- network/transport/v2/gossip/manager.go
- network/transport/v2/gossip/manager_test.go
- network/transport/v2/gossip/mock.go
- network/transport/v2/gossip/queue.go
- network/transport/v2/gossip/queue_test.go
- network/transport/v2/handlers.go
- network/transport/v2/handlers_test.go
- network/transport/v2/protocol.go
- network/transport/v2/protocol_test.go
- network/transport/v2/senders.go
- network/transport/v2/senders_mock.go
- network/transport/v2/senders_test.go
> Network: add State and TransactionSet

- network/transport/v2/handlers.go
- network/transport/v2/handlers_test.go
> Network: send state when missing prevs

- network/transport/v2/conversation.go
- network/transport/v2/conversation_test.go
- network/transport/v2/handlers.go
- network/transport/v2/handlers_test.go
- network/transport/v2/senders.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/1007
> Network: fix datarace in network gossipmanager handling

- network/dag/interface.go
- network/dag/state.go
- network/network_integration_test.go
- network/transport/v1/logic/handlers.go
- network/transport/v1/logic/handlers_test.go
- network/transport/v2/handlers.go
- network/transport/v2/handlers_test.go
> moved State.IsPresent check to within State.Add for transactional context

- auth/services/contract/notary.go
- auth/services/contract/notary_test.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/998
> Auth: fail DrawUpContract when DID has multiple non-matching VCs

- network/transport/v2/handlers.go
- network/transport/v2/handlers_test.go
- network/transport/v2/protocol_test.go
> Network: don't send back internal errors in protocol v2

- network/transport/v2/handlers.go
- network/transport/v2/handlers_test.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/1010
> Network: reject public TXs received without payload in protocol v2

- network/transport/grpc/connection.go
- network/transport/grpc/connection_manager.go
- network/transport/grpc/connection_test.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/1017
> Network: fix SendMsg() panic during testing

- core/engine.go
Makes it easier where the problem is when it freezes/crashes.
> Make boot logging (starting/stopping) more symmetric

- auth/api/v1/generated.go
- codegen/oapi/echo/echo-register.tmpl
- crypto/api/v1/generated.go
- didman/api/v1/generated.go
- network/api/v1/generated.go
- vcr/api/v2/generated.go
- vdr/api/v1/generated.go
fixes #1064 
Needs to be backported
#1067 needs to be taken care of next.
> fix broken status codes

- auth/api/v1/generated.go
- codegen/oapi/echo/echo-register.tmpl
- crypto/api/v1/generated.go
- didman/api/v1/generated.go
- network/api/v1/generated.go
- vcr/api/v2/generated.go
- vdr/api/v1/generated.go
> fix broken status codes (#1068)

- network/transport/v2/senders.go
- network/transport/v2/senders_test.go
> Network: increases TransactionList overhead margins

- echo/echo_integration_test.go
- go.sum
- network/dag/state.go
- network/dag/state_test.go
- network/network_integration_test.go
private payloads also called the observer
also a small fix for the echo_integration_test that  kept showing up during race tests
> fixed incorrect observer for private TX

- network/transport/v2/handlers.go
- network/transport/v2/handlers_test.go
> Network: Filter all gossiped Tx from peer's gossip queue

- network/transport/v2/handlers.go
- network/transport/v2/senders.go
All handlers log trace of incoming messages. The remaining messages are set to debug.
> Network: Update handler/sender log levels

- vcr/vcr.go
- vcr/vcr_test.go
fixes #1065
I'm not sure about the various error cases. Some extra attention for that would be appreciated.
> VCR: Untrusted only lists active issuers

- core/tls.go
> Support TLS v1.2

- vcr/issuer/interface.go
- vcr/issuer/issuer.go
- vcr/issuer/issuer_test.go
- vcr/issuer/leia_store.go
- vcr/issuer/leia_store_test.go
- vcr/issuer/mock.go
- vcr/vcr.go
- vcr/vcr_test.go
> VCR: issuer tracks credentials it revoked and returns 409 on double revocation

- network/transport/grpc/authenticator.go
- network/transport/grpc/connection_manager.go
> Network: debug logging in case of authentication error

- go.mod
- go.sum
- vcr/phonetics.go
possible fix for #1145 since the featured version mentions thread safety as fix
> update phonetics lib featuring thread safety

- network/dag/bbolt_dag.go
- network/dag/bbolt_dag_test.go
- network/dag/state.go
> Network: Cleanup unused code

- network/api/v1/generated.go
- network/dag/interface.go
- network/dag/mock.go
- network/dag/state.go
- network/dag/state_test.go
- network/network.go
- network/network_integration_test.go
- network/network_test.go
fixes #1174 
Functionality of lastTransactionTracker was also covered by state
> Remove lastTransactionTracker

- docs/_static/network/v1.yaml
- docs/pages/monitoring.rst
- network/api/v1/api.go
- network/api/v1/api_test.go
- network/api/v1/generated.go
- network/dag/dotviz.go
- network/dag/interface.go
- network/dag/mock.go
- network/dag/state.go
- network/interface.go
- network/mock.go
- network/network.go
- network/network_test.go
closes #1199 
Graphs can be created using open ended range requests.
not sure if this is the right api format
> Render graph on Lamport Clock ranges

- docs/pages/getting-started/3-configure-your-node.rst
Fixes #1209
Elaborate on key and network concepts and configuration
> Update getting started docs

- docs/_static/vcr/v2.yaml
- vcr/api/v2/registry.go
- vcr/api/v2/registry_test.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/1221
> VCR: ResolveVC should not verify VC before returning it

- network/dag/parser_test.go
- network/dag/signing.go
- network/dag/signing_test.go
- network/dag/transaction.go
- network/dag/transaction_test.go
> revert tx version back to v1, remove LC from crit headers

- docs/pages/integrating/vc.rst
> elaborate on VC searching

- network/dag/bbolt_dag.go
- network/dag/bbolt_dag_test.go
- network/dag/interface.go
- network/dag/state.go
- network/dag/state_test.go
part of #1216 
Also removed `walk`, not used anymore.
> disable DAG.Verify at startup

- go.sum
- network/dag/dag.go
- network/dag/dag_test.go
- network/dag/interface.go
- network/dag/mock.go
- network/dag/payloadstore_test.go
- network/dag/state.go
- network/network.go
> Network: store number of TXs

- network/dag/payloadstore_test.go
- network/dag/state.go
- network/dag/test.go
- storage/engine.go
- vdr/store/store.go
Depending on the backing store, this might not do anything.
> Network: clean up bucket init code

- docs/index.rst
- docs/pages/deployment/backup-restore.rst
part of #1269 
preview at: https://nuts-node.readthedocs.io/en/doc-1269_backup_restore/pages/deployment/backup-restore.html
> described bbolt backup procedure

- docs/pages/release_notes.rst
this time before we tag the version
> add V4 release notes

- docs/Dockerfile
- docs/pages/development/1-development.rst
- docs/requirements.txt
New laptop had to get sphinx up and running again, troublesome....
Replace python/sphinx install with docker
> replace sphinx build with docker

- go.mod
- go.sum
- storage/bbolt.go
- storage/interface.go
- storage/redis.go
Closes https://github.com/nuts-foundation/nuts-node/issues/1298
@woutslakhorst can you repeat the test with this change?
> Storage: update go-stoabs, so lock acquisition expires in 1s

- go.mod
- go.sum
> redis beta lib update

- docs/pages/release_notes.rst
> add V4.1.0 release notes

- docs/pages/getting-started/3-configure-your-node.rst
> add test network to docs

- docs/pages/deployment/tls-configuration.rst
- network/transport/grpc/tls_offloading.go
- network/transport/grpc/tls_offloading_test.go
Closes https://github.com/nuts-foundation/nuts-node/issues/1337
> Network: support TLS offloading with DER encoded client certs

- core/engine.go
- core/engine_test.go
There's dependencies between engines, so order for `Start()` matters. The same then applies to `Shutdown()`, but then in reverse.
> Core: let engines shutdown in reverse order from which they're started

- network/dag/parser_test.go
- network/dag/signing.go
- network/dag/signing_test.go
- network/dag/transaction.go
- network/dag/transaction_test.go
- vcr/store.go
Closes https://github.com/nuts-foundation/nuts-node/issues/1243
> Network: produce v2 transactions

- docs/_static/vdr/v1.yaml
> Fix OAPI keyAgreement default

- go.mod
- go.sum
Closes https://github.com/nuts-foundation/nuts-node/issues/1394
> Storage: update go-stoabs to fix Redis Iterate() bug

- go.mod
- go.sum
Backports https://github.com/nuts-foundation/nuts-node/issues/1394
> Backport - Storage: update go-stoabs to fix Redis Iterate() bug

- crypto/storage/vault.go
- crypto/storage/vault_test.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/1407
> Crypto: fix nil deref when key is not found in Vault

- docs/pages/deployment/tls-configuration.rst
closes #1392?
I could not reproduce issues with max message size, so I have only added the supposed solution as a note.
The current config didn't work for me, so I changed some things to make it a copy-paste solution to get started with NGINX
> Docs: update nginx tls offload config

- docs/pages/deployment/backup-restore.rst
- docs/pages/deployment/database-configuration.rst
> added info on trusted_issuers.yaml

- docs/pages/deployment/tls-configuration.rst
Added the wrong flag in previous PR since I was not able to reproduce the issue.
> Docs: correct NGINX config flag

- docs/index.rst
- docs/pages/deployment/production-configuration.rst
- docs/pages/deployment/storage-configuration.rst
Closes https://github.com/nuts-foundation/nuts-node/issues/1429
> Docs: tweaks in storage configuration docs

- docs/index.rst
- docs/pages/deployment/resource-requirements.rst
Closes https://github.com/nuts-foundation/nuts-node/issues/1362
> Docs: described minimum resource requirements

- docs/pages/deployment/tls-configuration.rst
Closes https://github.com/nuts-foundation/nuts-node/issues/1422
> Docs: note on CRL checking

- auth/services/contract/notary_test.go
apparently, dutch timezone in 1900 has changed from +00:19:32 to +00:17:xx
> change time in tests to 1970 to avoid weird timezone in 1900

- docs/pages/deployment/recommended-deployment.rst
Closes https://github.com/nuts-foundation/nuts-node/issues/1363
> Docs: tweak TLS offloading docs

- crypto/storage/vault.go
- crypto/storage/vault_test.go
> fix overriding VAULT_TOKEN with empty default

- crypto/storage/vault.go
- crypto/storage/vault_test.go
> fix overriding VAULT_TOKEN with empty default (#1465)

- crypto/storage/vault.go
- crypto/storage/vault_test.go
Backport of #1470 and #1410 
Depends on https://github.com/nuts-foundation/nuts-node/pull/1476 for fixed tests
> V4 vault memory fixes

- vcr/api/v2/api.go
- vcr/issuer/issuer.go
- vcr/issuer/issuer_test.go
> VCR: Return 400 when trying to issue a VC with invalid input

- auth/auth.go
- auth/services/contract/notary.go
- auth/services/irma/irmaconfig.go
- auth/services/irma/validator.go
> Set IRMA to production-mode on strict-mode installs

- auth/api/v1/api_test.go
- auth/api/v1/client_test.go
- core/status/cmd_test.go
- didman/api/v1/client_test.go
- didman/cmd/cmd_test.go
- docs/cli_docgen.go
- docs/pages/deployment/cli-reference.rst
- network/cmd/cmd_test.go
- test/http/handler.go
- vcr/api/v2/client.go
- vcr/api/v2/client_test.go
- vcr/cmd/cmd.go
- vcr/cmd/cmd_test.go
- vdr/api/v1/client_test.go
- vdr/cmd/cmd_test.go
Was reported missing, required for setting up care organizations using CLI.
Closes https://github.com/nuts-foundation/nuts-node/issues/1455
> VCR: Support issuing a VC using CLI

- go.mod
- go.sum
Got released after my PR got accepted 🥂
> Update to go-redsync/redsync@v4.6.0 for official Redis 9 support

- auth/services/oauth/oauth_test.go
- vcr/api/v2/registry_test.go
- vcr/credential/resolver_test.go
- vcr/credential/test.go
- vcr/credential/validator.go
- vcr/credential/validator_test.go
- vcr/issuer/issuer_test.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/1502
> VCR: Only check LegalBase for v2 VCs

- auth/services/contract/notary_test.go
* change time in tests to 1970 to avoid weird timezone in 1900
* another test
> V4 change time in tests to 1970 to avoid weird timezone in 1900 (#1457)

- network/dag/notifier.go
The initial response from `receiver` was always logged by in `Notify`
added a method to reduce duplicate code
> Notifier: only log actual errors

- auth/api/v1/api_test.go
- auth/services/oauth/oauth.go
- auth/services/oauth/oauth_test.go
- docs/pages/release_notes.rst
- vcr/credential/resolver.go
- vcr/credential/resolver_test.go
- vcr/credential/test.go
- vcr/credential/types.go
- vcr/credential/validator.go
- vcr/credential/validator_test.go
- vcr/issuer/issuer.go
- vcr/issuer/issuer_test.go
- vcr/search.go
- vcr/verifier/verifier.go
> VCR: Validate that VCs only contain fields that are defined by JSON-LD context (#1190)

- network/dag/interface.go
- network/dag/mock.go
- network/dag/state.go
- network/dag/state_test.go
- network/network_integration_test.go
- network/transport/v2/handlers.go
- network/transport/v2/handlers_test.go
- network/transport/v2/protocol.go
- network/transport/v2/protocol_test.go
- network/transport/v2/transactionlist_handler.go
- network/transport/v2/transactionlist_handler_test.go
> Network: add highest LC to cached state (#1522)

- network/dag/tree/tree.go
- network/dag/tree/tree_test.go
> State: build tree bottom up (#1528)

- README.rst
- README_template.rst
- docs/pages/development/1-development.rst
> Readme: add Go version and Slack badge

- docs/pages/getting-started/3-configure-your-node.rst
- docs/pages/getting-started/4-connecting-crm.rst
- docs/pages/integrating/faq-errors.rst
> Docs: clarify node bootstrap

- Dockerfile
> Docker: update must-dev dep

- didman/didman.go
- didman/didman_test.go
- docs/pages/integrating/vc.rst
- docs/pages/release_notes.rst
- vcr/api/v2/registry.go
- vcr/api/v2/registry_test.go
- vcr/search.go
- vcr/search_test.go
Closes https://github.com/nuts-foundation/nuts-node/issues/1619
> VCR: SearchVCs match exact by default, allow wildcard for notnil/exact match

- codegen/configs/vdr_v1.yaml
- docs/_static/vdr/v1.yaml
- docs/index.rst
- docs/pages/deployment/key-rotation.rst
- http/engine.go
- vcr/cmd/cmd_test.go
- vdr/api/v1/api.go
- vdr/api/v1/api_test.go
- vdr/api/v1/client.go
- vdr/api/v1/generated.go
- vdr/api/v1/test/generated.go
- vdr/api/v1/types.go
- vdr/cmd/cmd.go
- vdr/doc/creator.go
- vdr/doc/creator_test.go
- vdr/doc/manipulator.go
- vdr/doc/manipulator_test.go
- vdr/types/common.go
- vdr/types/common_test.go
- vdr/types/interface.go
- vdr/types/mock.go
Closes https://github.com/nuts-foundation/nuts-node/issues/1517
TODO:
> VDR: Support & document key rotation operations

- auth/api/v1/api.go
- auth/api/v1/api_test.go
- auth/services/messages.go
- auth/services/oauth/oauth.go
- auth/services/oauth/oauth_test.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/1649
> Auth: populate auth server URL in JWT grant response

- auth/services/irma/irmaconfig.go
- auth/services/irma/irmaconfig_test.go
> Remove temporary irma schema dirs at startup

- docs/pages/release_notes.rst
Forward of https://github.com/nuts-foundation/nuts-node/pull/1672
> Release notes for v5.0.1

- didman/didman.go
- didman/didman_test.go
- docs/pages/release_notes.rst
Backports https://github.com/nuts-foundation/nuts-node/pull/1678 to v4
> DIDMan: serialize DIDMan calls (backport to v4)

- crypto/storage/fs.go
- crypto/storage/fs_test.go
Closes https://github.com/nuts-foundation/nuts-node/issues/1674
> Crypto: cleanup FS backend initialization (NTS-006)

- docs/_static/auth/v1.yaml
Closes https://github.com/nuts-foundation/nuts-node/issues/1461
> Auth: adjust OpenAPI for CreateAccessToken request to indicate credentials are optional

- network/dag/notifier.go
- network/dag/notifier_test.go
closes #1730
The notifier only logged the errors returned by the receivers in an Event.
When the receiver did not return an error, but also didn't finish, we returned an error to keep the notifiers retry mechanism going. Since this wasn't an actual error it wasn't in the Event, but a missing error leads to more confusion than adding the error that explains the issue.
> Notifier: log unfinished event error

- docs/pages/release_notes.rst
> v5.0.3 release notes

- docs/pages/getting-started/5-irma-contract.rst
fixes #1646 
Describes some of the magic URL rewriting the Nuts node does for IRMA.
> add some explanation on how IRMA path is constructed

- network/api/v1/api.go
- network/api/v1/api_test.go
- network/interface.go
- network/mock.go
- network/network.go
- network/network_test.go
Bug fix, code simplification, and a more future proof API.
> Synchronous Reprocess Call

- core/config.go
- core/config_test.go
- docs/pages/deployment/configuration.rst
Fixes https://github.com/nuts-foundation/nuts-node/issues/1715
> Config: disallow secrets being set as flag, to avoid leaking them

- docs/pages/deployment/recommended-deployment.rst
Probably far from complete, please elaborate.
Fixes https://github.com/nuts-foundation/nuts-node/issues/1645
> Docs: production checklist

- auth/services/contract/notary.go
- auth/services/oauth/oauth.go
- didman/didman.go
- jsonld/reader.go
- vcr/api/v2/registry_test.go
- vcr/context_test.go
Backport of https://github.com/nuts-foundation/nuts-node/commit/615607f3e1e2a91309007682b19d4811100b3178
> VCR: Validate SearchVCs input (V5 backport)

- crl/validator.go
- crl/validator_test.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/1761 and https://github.com/nuts-foundation/nuts-node/issues/1762
> CRL: Ignore expired certificates

- crl/validator.go
- crl/validator_test.go
Backport of https://github.com/nuts-foundation/nuts-node/pull/1773 to V5
> CRL: Ignore expired certificates (V5 backport)

- .github/workflows/build-images.yaml
> Fix github actions: add master tag for default branch

- docs/pages/deployment/production-configuration.rst
Fixes https://github.com/nuts-foundation/nuts-node/issues/1702
> Docs: some advise on monitoring malicious traffic

- docs/index.rst
- docs/pages/deployment/configuration.rst
- docs/pages/deployment/logging.rst
- docs/pages/deployment/monitoring.rst
Closes https://github.com/nuts-foundation/nuts-node/issues/1431
> Docs: document how to enable JSON logging

- network/network.go
- network/transport/grpc/connection_list.go
- network/transport/grpc/connection_manager.go
- network/transport/grpc/interface.go
- network/transport/grpc/outbound_connector_test.go
- network/transport/grpc/test.go
This should contain no functional changes
removes unused struct values / interfaces / tests
small refactor in start/stop to improve readability
> Network: connection manager cleanup

- docs/pages/release_notes.rst
> v506 release notes for master

- docs/pages/release_notes.rst
some release notes on patch version
> v506 release notes

- network/transport/grpc/connection_list.go
- network/transport/grpc/connection_list_test.go
- network/transport/grpc/connection_manager.go
- network/transport/grpc/connection_manager_test.go
fixes #1866 
Fixing it in a more beautiful way is a waste of time since @gerardsn is refactoring the connection manager.
backport to V5 and release
> quick fix for allowing multiple nodes from same IP

- docs/pages/release_notes.rst
> 508 release notes

- auth/services/oauth/oauth_test.go
- crypto/jwx_test.go
No bugs found, but we were missing (unit) test coverage
> Test coverage for access tokens with invalid signature

- network/transport/v2/handlers.go
- network/transport/v2/handlers_test.go
- network/transport/v2/peer_diagnostics.go
- network/transport/v2/peer_diagnostics_test.go
- network/transport/v2/protocol.go
- network/transport/v2/protocol_test.go
- network/transport/v2/transactionlist_handler.go
- network/transport/v2/transactionlist_handler_test.go
Part of https://github.com/nuts-foundation/nuts-node/issues/1900
> Network: fix goroutine leak on shutdown in v2 protocol

- auth/services/oauth/oauth_test.go
- docs/_static/vcr/v2.yaml
- docs/pages/release_notes.rst
- vcr/credential/revocation.go
- vcr/credential/revocation_test.go
- vcr/credential/test.go
- vcr/issuer/issuer.go
- vcr/issuer/issuer_test.go
Upstream port to master of https://github.com/nuts-foundation/nuts-node/pull/1913
Fixes https://github.com/nuts-foundation/nuts-node/issues/1911
Fixes https://github.com/nuts-foundation/nuts-node/issues/1902
> VCR: Don't check VC existence when revoking (#1913)

- docs/pages/integrating/api-authentication.rst
> Docs: fix API authentication formatting

- crypto/storage/fs/fs.go
- crypto/storage/fs/fs_test.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/1943
Does not fix the underlying issue, but the nil dereference that occurs. When it happens again, the underlying error is now logged.
> Crypto: fix nil deref in ListPrivateKeys

- cmd/root.go
Part of https://github.com/nuts-foundation/nuts-node/issues/1943
> Crypto: start before dependent engines

- vdr/didservice/creator.go
- vdr/didservice/creator_test.go
> VDR: Disable ephemeral keys in DID creation

- network/transport/grpc/connection_manager.go
- network/transport/grpc/connection_manager_test.go
closes #1921 
do we even need a separate tlsConfig for server and client?
> Also check if peer's certificate is revoked on outbound connections

- docs/pages/release_notes.rst
> Release notes: JWM support not scheduled for v5.1

- http/tokenV2/authorized_keys.go
- http/tokenV2/authorized_keys_test.go
> Fix bug with commented authorized_keys lines

- network/network.go
- network/network_integration_test.go
- network/network_test.go
- network/transport/connection_manager.go
- network/transport/connection_manager_mock.go
- network/transport/grpc/connection_manager.go
- network/transport/grpc/connection_manager_test.go
- network/transport/v2/protocol_integration_test.go
closes #1976 
Not sure if we want this solution of add optional `ConnectOption`s to `ConnectionManager.Connect`
> Network: don't reset backoff on startup

- docs/pages/development/2-releasing.rst
> expand releasing with RCs

- docs/pages/release_notes.rst
> add release date

- codegen/configs/didman_v1.yaml
- didman/api/v1/api.go
- didman/api/v1/api_test.go
- didman/api/v1/client_test.go
- didman/api/v1/generated.go
- didman/api/v1/types.go
- docs/_static/didman/v1.yaml
Still causes compilation issues, which I fixed in the codegen in https://github.com/deepmap/oapi-codegen/pull/999, but which needs to be released. For the time being, maybe just fix it manually (it's changing 1 character), we don't alter the API too often.
> DIDman: Strict API interfaces

- crl/validator.go
> CRL: update deprecated logic

- codegen/configs/vcr_v2.yaml
- docs/_static/vcr/v2.yaml
- vcr/api/v2/api.go
- vcr/api/v2/api_test.go
- vcr/api/v2/generated.go
- vcr/api/v2/registry.go
- vcr/api/v2/registry_test.go
- vcr/api/v2/types.go
> VCR: Strict API interfaces

- go.mod
images are already built with go 1.20
> Upgrade to Go 1.20

- network/network.go
- network/network_integration_test.go
- network/network_test.go
- network/transport/grpc/connection_manager.go
- network/transport/grpc/connection_manager_test.go
- network/transport/nodedid.go
- network/transport/nodedid_test.go
- network/transport/v2/protocol.go
- network/transport/v2/protocol_integration_test.go
- network/transport/v2/protocol_test.go
changes requested to https://github.com/nuts-foundation/nuts-node/pull/2016 by @reinkrul
> Network: nodeDID is not a pointer

- vcr/assets/assets/contexts/nuts.ldjson
added assuranceLevel to AuthCred, added NutsEmplCred and SelfSignedPresentation
part of #2047 
- assuranceLevel is modelled after https://openid.net/specs/openid-connect-4-identity-assurance-1_0.html
- Example on how to use on [playground](https://json-ld.org/playground/#startTab=tab-nquads&json-ld=%7B%22%40context%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2F2018%2Fcredentials%2Fv1%22%2C%22https%3A%2F%2Fw3id.org%2Fsecurity%2Fsuites%2Fjws-2020%2Fv1%22%2C%7B%22%40version%22%3A1.1%2C%22%40protected%22%3Atrue%2C%22id%22%3A%22%40id%22%2C%22type%22%3A%22%40type%22%2C%22schema%22%3A%22http%3A%2F%2Fschema.org%2F%22%2C%22nuts%22%3A%22https%3A%2F%2Fnuts.nl%2Fcredentials%2Fv1%23%22%2C%22NutsSelfSignedPresentation%22%3A%22nuts%3ANutsSelfSignedPresentation%22%2C%22NutsEmployeeCredential%22%3A%7B%22%40id%22%3 …
> Update JSON-LD for new authentication means

- auth/services/selfsigned/signer.go
- auth/services/selfsigned/types.go
> Auth: fix build for selfsigned holder VP

- docs/pages/release_notes.rst
> v5.2.1 release notes

- docs/pages/deployment/recommended-deployment.rst
> Docs: fix list in Recommended Deployment

- Dockerfile
- core/status/engine.go
- core/status/engine_test.go
- docs/pages/deployment/monitoring.rst
- docs/pages/release_notes.rst
> Core: use /health endpoint in dockerfile

- docs/pages/deployment/backup-restore.rst
> Docs: add nodedid to backup-restore procedure

- vdr/didstore/event.go
- vdr/didstore/event_test.go
- vdr/didstore/reader.go
- vdr/didstore/reader_test.go
- vdr/didstore/store.go
- vdr/didstore/store_test.go
> always write index data for VDR, never check on duplicate (#2141)

- vcr/api/vcr/v2/types.go
- vcr/api/vcr/v2/types_test.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/2165
> VCR: Use DID library JSON marshaller (revert API behavior to v5.1)

- pki/pki.go
- pki/pki_test.go
- pki/validator.go
> PKI: add HealthCheckable

- docs/_static/auth/v1.yaml
- docs/pages/getting-started/5-authentication.rst
closes #2170 
Added note to OAS and auth getting started page.
> added field description to token introspection

- pki/validator.go
stable and dev network root certificates are x509 v1. Checking if a v1 cert is a CA is non trivial resulting in the following log messages:
```
time="2023-05-26T13:29:30Z" level=warning msg="Did not add CRL Distribution Points" error="certificate's issuer is not in the trust store: subject=CN=Nuts Development Network Root CA, issuer=CN=Nuts Development Network Root CA" module=pki
time="2023-05-26T13:29:30Z" level=warning msg="Did not add CRL Distribution Points" error="certificate's issuer is not in the trust store: subject=CN=Nuts Development Network Root CA, issuer=CN=Nuts Development Network Root CA" module=pki
```
pki validator now just adds the entire chain, which may include end user certs. They are only used for CRL signature verification so should have no impact.
> PKI: do not check if CA in AddTruststore(chain)

- crypto/jwx.go
- didman/didman.go
- vcr/api/oidc4vci/v0/issuer.go
- vcr/api/oidc4vci/v0/issuer_test.go
- vcr/credential/validator.go
- vcr/holder/oidc4vci_wallet.go
- vcr/issuer/oidc4vci_issuer.go
- vcr/issuer/oidc4vci_issuer_mock.go
- vcr/issuer/oidc4vci_issuer_test.go
- vcr/oidc4vci/types.go
- vcr/vcr.go
- vdr/cmd/cmd.go
- vdr/didservice/creator.go
- vdr/didservice/resolvers.go
- vdr/didservice/util.go
- vdr/didservice/util_test.go
- vdr/types/mock.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/2036
> OpenID4VCI: Validate proof when processing CredentialRequest

- vdr/vdr.go
- vdr/vdr_test.go
fixes #1860 
and add the TX of the controller to the prevs
> check existence of controller on DID creation

- vcr/holder/oidc4vci_wallet.go
- vcr/holder/oidc4vci_wallet_test.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/2038
> OpenID4VCI: Validate grants in credential offer

- docs/pages/technology/saas.rst
Some ideas and pointers for parties considering offering Nuts nodes as SaaS.
> Docs: things to consider when building a SaaS platform

- vdr/vdr_test.go
> VDR: fix failing test #2189

- vdr/types/mock.go
> VDR: regen mocks

- pki/validator.go
> backport 5.3: do not check if CA (#2196)

- network/transport/grpc/connection_manager.go
This change (or something very similar) looks useful to us given recent discussions. What do you think?
> Set grpc server keepalive policy

- auth/services/oauth/authz_server.go
- auth/services/oauth/authz_server_test.go
- auth/services/oauth/relying_party.go
fixes #1861
This current field name is a type and not according to spec. 
removal of deprecated claim is done in #2204 (v6)
> add extra purposeOfUse claim to access token request

- auth/auth_test.go
- auth/test.go
- codegen/configs/vcr_oidc4vci_v0.yaml
- docs/_static/vcr/oidc4vci_v0.yaml
- pki/mock.go
- vcr/api/oidc4vci/v0/api.go
- vcr/api/oidc4vci/v0/generated.go
- vcr/api/oidc4vci/v0/wallet.go
- vcr/api/oidc4vci/v0/wallet_test.go
- vcr/holder/oidc4vci_wallet.go
- vcr/holder/oidc4vci_wallet_test.go
- vcr/oidc4vci/test.go
- vcr/oidc4vci/types.go
- vcr/oidc4vci/wallet_client.go
- vcr/oidc4vci/wallet_client_test.go
- vcr/vcr_test.go
To put responsibility of retrying on offerer.
Fixes https://github.com/nuts-foundation/nuts-node/issues/2040
> OpenID4VCI: Retrieve credentials synchronously

- network/network.go
- network/network_test.go
> Reprocess: do not fail on missing payload

- http/tokenV2/middleware.go
- http/tokenV2/middleware_test.go
fixes #1974 
the auth middleware no longer does `echoCtx.String(code, message)` but now relies on the error writer in the context to do the final output.
> replace direct String return with specific error writer

- vcr/holder/oidc4vci_wallet.go
#2035 is closed stating that this wasn't an issue
> Remove issue comment

- e2e-tests/auth/selfsigned/go.mod
- e2e-tests/auth/selfsigned/go.sum
> go mod tidy

- network/transport/grpc/authenticator.go
- network/transport/grpc/authenticator_mock.go
- network/transport/grpc/authenticator_test.go
- network/transport/grpc/connection_list_test.go
- network/transport/grpc/connection_manager.go
- network/transport/grpc/connection_manager_test.go
- network/transport/grpc/connection_test.go
> Network: set Peer.Certificate on bootstrap connections

- jsonld/scalar.go
- jsonld/scalar_test.go
- vcr/holder/oidc4vci_wallet.go
- vcr/holder/oidc4vci_wallet_test.go
- vcr/issuer/issuer.go
- vcr/oidc4vci/issuer_client_test.go
- vcr/vcr.go
> OIDC4VCI: compare offered and received credential types for equality

- e2e-tests/nuts-network/direct-wan/run-test.sh
- e2e-tests/nuts-network/ssl-offloading/haproxy/run-test.sh
- e2e-tests/nuts-network/ssl-offloading/nginx/run-test.sh
- e2e-tests/nuts-network/ssl-pass-through/run-test.sh
- e2e-tests/oauth-flow/run-test.sh
> e2e-tests: replace sleeps with waitFor

- vcr/oidc4vci/issuer_client.go
- vcr/oidc4vci/wallet_client.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/2032
> OpenID4VCI: Remove TLS support TODO (already fixed)

- docs/pages/deployment/backup-restore.rst
closes #2324 
With the removal of the DID reprocess, the docs are consistent again.
> Remove DID restore from restore procedure

- pki/denylist.go
- pki/denylist_test.go
fixes #2343 
had to pass correct error
> use correct error on banned

- network/dag/notifier.go
- network/dag/notifier_test.go
> Notifier: fix error occuring after completion of event

- e2e-tests/denylist/README.md
- e2e-tests/nuts-network/private-transactions/run-test.sh
- e2e-tests/openid4vci/README.md
- e2e-tests/openid4vci/issuer-initiated/docker-compose.yml
- e2e-tests/openid4vci/issuer-initiated/node-A/nuts.yaml
- e2e-tests/openid4vci/issuer-initiated/node-B/nuts.yaml
- e2e-tests/openid4vci/issuer-initiated/run-test.sh
- e2e-tests/openid4vci/network-issuance/docker-compose.yml
- e2e-tests/openid4vci/network-issuance/node-A/nuts.yaml
- e2e-tests/openid4vci/network-issuance/node-B/nuts.yaml
- e2e-tests/openid4vci/network-issuance/run-test.sh
- e2e-tests/openid4vci/run-tests.sh
closes #2362 
mix-and match from `nuts-network/private-transactions` and `openid4vci/issuer-initiated` tests
> Add openid4vci disabled issuance test

- network/dag/verifier.go
- network/dag/verifier_test.go
- network/network.go
- vdr/ambassador.go
- vdr/didservice/resolvers.go
- vdr/didservice/resolvers_test.go
- vdr/types/interface.go
Part of https://github.com/nuts-foundation/nuts-node/issues/2361
> VDR: 'De-Nuts' the KeyResolver interface for better abstraction

- crypto/api/v1/api.go
- go.mod
- go.sum
- network/dag/pal_test.go
- network/network_test.go
- network/transport/grpc/util_test.go
- vcr/api/vcr/v2/api_test.go
- vcr/credential/validator_test.go
- vcr/issuer/issuer_test.go
- vcr/issuer/network_publisher_test.go
- vdr/api/v1/api_test.go
- vdr/didservice/util.go
See https://github.com/nuts-foundation/go-did/pull/73
> Upgrade go-did lib

- network/dag/consistency_test.go
- network/dag/notifier_test.go
- network/dag/state_test.go
- network/network_test.go
- network/test.go
- network/transport/v2/protocol_integration_test.go
- storage/bbolt.go
- storage/engine_test.go
- storage/test.go
- vcr/test.go
- vcr/vcr_test.go
- vdr/didstore/test.go
> Use in-memory BBolt storage for test Storage Engines

- auth/services/selfsigned/validator.go
- auth/services/selfsigned/validator_test.go
- e2e-tests/auth/selfsigned/apps/selfsigned.go
- e2e-tests/auth/selfsigned/main_test.go
- vcr/api/vcr/v2/api.go
- vcr/api/vcr/v2/api_test.go
- vcr/verifier/interface.go
- vcr/verifier/mock.go
- vcr/verifier/verifier.go
- vcr/verifier/verifier_test.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/2428
> Derive trust for NutsEmployeeCredential from NutsOrganizationCredential

- .github/workflows/govulncheck.yaml
https://go.dev/blog/vuln
Sounds like a good addition to our CI. Maybe should be merged with CodeQL workflow?
> Add govulncheck to CI

- e2e-tests/storage/backup-restore/run-test.sh
- vcr/issuer/leia_store.go
- vcr/issuer/leia_store_test.go
- vcr/verifier/leia_store.go
- vcr/verifier/leia_store_test.go
fixes #2450
commit 2 is the bug, commit 3 is nice to have but maybe not appropriate for back port?
> Always write network revocations to backup store

- docs/pages/release_notes.rst
- network/transport/v2/handlers.go
- network/transport/v2/handlers_test.go
> Backport of reduced page transmission

- network/dag/notifier.go
- network/dag/notifier_test.go
closes #2569
Nearly all non-retry able errors are for contexts that were previously not on the jsonld remote allow list. By ignoring these types of errors Network module startup went from ~2,5 min to <10 sec for a node on stable network.
This hack does not actually fix the underlying issue, and if the context is later put on the allow list it can be `Reprocess`ed, but that will not remove the event from the list. Is this enough with #2548 in mind?
> ignore events with jsonld.ContextURLNotAllowedErr at startup

- network/transport/grpc/connection_test.go
This test keeps failing in CI because go routines on GitHub may close in a different order than locally. The entire test does't make sense, so just removed it. There are plenty of tests that will catch anything that was supposed to be tested here.
> remove failing test

- docs/_static/vdr/v2.yaml
- vdr/api/v2/generated.go
Had some invalid definitions, changed `id` to `serviceID` (otherwise there's `Did` and `Id` parameters in the request object, which is confusing).
> VDRv2: Fix OpenAPI DID document service API specs

- Dockerfile
See https://github.com/mattn/go-sqlite3/issues/1164
> Fix Docker build due to sqlite3 and alpine 3.19 incompatibility

- crypto/crypto.go
- crypto/crypto_test.go
- crypto/storage/spi/interface.go
- crypto/storage/spi/wrapper_test.go
did:web with a port number wasn't allowed. This should fix that.
> fix didkey pattern

- http/engine.go
- http/engine_test.go
When testing did:web with encoded port numbers, the did in the controller was missing the %3A for the port.
> remove url decode from middleware, now handled by codegen bind

- vdr/didnuts/ambassador_test.go
- vdr/didnuts/creator.go
- vdr/didnuts/creator_test.go
- vdr/vdr.go
- vdr/vdr_test.go
Cleaning up VDR implementation.
> VDR: Move did:nuts specific to did:nuts creator

- discovery/module_test.go
- docs/_static/vdr/v2.yaml
- storage/test.go
- vcr/test.go
- vdr/api/v2/api.go
- vdr/api/v2/api_test.go
- vdr/api/v2/generated.go
> VDR: API to list owned DIDs

- discovery/api/v1/api.go
- discovery/api/v1/api_test.go
- discovery/api/v1/generated.go
- discovery/interface.go
- discovery/mock.go
- discovery/module.go
- discovery/module_test.go
- discovery/store.go
- discovery/store_test.go
- docs/_static/discovery/v1.yaml
Most probably required by future "Nuts Admin"-applications.
Fixes https://github.com/nuts-foundation/nuts-node/issues/2727
> Discovery: get DID activation status on service

- vdr/vdr.go
- vdr/vdr_test.go
> VDR: Do not return nil for ListOwned

- docs/diagrams/discovery service architecture.drawio
> did:web diagram

- discovery/api/v1/generated.go
- docs/_static/vcr/vcr_v2.yaml
- vcr/api/vcr/v2/api.go
- vcr/api/vcr/v2/api_test.go
- vcr/api/vcr/v2/generated.go
> VCR: List credentials in wallet

- echo/echo_integration_test.go
> Improve Echo log assertion test stability

- go.mod
- go.sum
- storage/engine_test.go
accidental major release (according to retraction notice)
> Dep: downgrade retracted version mattn/go-sqlite3

- jsonld/jsonld.go
- jsonld/jsonld_test.go
- jsonld/test.go
- vcr/credential/validator.go
- vcr/credential/validator_test.go
- vcr/issuer/issuer.go
- vcr/issuer/issuer_test.go
needed in statuslist2021 package, but is a better fit in jsonld package anyway
> Move AllFieldsDefinedValidator to jsonld package

- storage/sql_migrations/001_credential.sql
- storage/sql_migrations/007_wallet.sql
- vcr/holder/wallet.go
- vcr/holder/wallet_test.go
- vcr/test.go
- vcr/vcr.go
- vcr/vcr_test.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/2798
> VCR: Implement holder's wallet as SQL store instead of KV

- docs/pages/release_notes.rst
- Fix formatting
- Add existing v5.4.5
- Add new v5.4.6
> Fix v5.4 release notes

- .circleci/config.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/e2e-tests.yaml
- .github/workflows/govulncheck.yaml
- go.mod
details on some of the most interesting changes: https://go.dev/blog/
release notes: https://go.dev/doc/go1.22
> Upgrade to go 1.22

- storage/sql_migrations/001_credential.sql
- storage/sql_migrations/002_discoveryservice.sql
- storage/sql_migrations/003_didweb.sql
- storage/sql_migrations/004_discoveryservice_client_registration.sql
- storage/sql_migrations/005_didweb_services.sql
- storage/sql_migrations/006_statuslist.sql
- storage/sql_migrations/007_wallet.sql
- storage/sql_migrations/008_issued_credential.sql
- storage/sql_migrations/README.md
fixes #2858 
fixed varchar length of 370 for did and 415 for id (did+identifier)
@reinkrul and @gerardsn could you check if this is ok for the tables you added?
> set column length for did and id

- vdr/api/v2/api.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/2869
> VDR: Replace v2 API panics with errors

- docs/pages/deployment/key-rotation.rst
part of #2854 
key rotation is rewritten to a add/delete procedure. A new issue has been created for finding issued VCs based on period/kid (#2894)
> rewrite key rotation

- .github/workflows/build-images.yaml
compare was wrong so nothing was uploaded
> Github action upload dev image for master

- vcr/holder/interface.go
- vcr/holder/wallet.go
- vcr/holder/wallet_test.go
> return empty list on empty wallet

- discovery/client.go
- discovery/client_test.go
- vcr/holder/wallet.go
- vcr/pe/presentation_definition.go
- vcr/pe/presentation_definition_test.go
- vcr/pe/presentation_submission.go
fixes: #2916 
added simple check to see if to VCs are required
> allow for empty VP when registering with discovery service

- docs/_static/vdr/v2.yaml
- vdr/api/v2/api.go
- vdr/didweb/manager.go
- vdr/didweb/manager_test.go
- vdr/management/management.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/2910
> VDR: Check whether the did:web DID to create already exists

- auth/api/iam/generated.go
- docs/_static/auth/iam.yaml
- e2e-tests/oauth-flow/openid4vp/docker-compose.yml
- e2e-tests/oauth-flow/rfc021/docker-compose.yml
- e2e-tests/oauth-flow/statuslist2021/docker-compose.yml
- e2e-tests/oauth-flow/statuslist2021/run-test.sh
closes #2922
improved test by checking `message` for revocation instead of relying on `validity`
> fix statuslist2021 e2e-test

- docs/_static/vdr/v2.yaml
- vdr/api/v2/generated.go
> VDR: Move FilterServices to /service instead of /service/{id}

- api/ssi_types_test.go
- auth/api/auth/v1/api_test.go
- auth/services/oauth/relying_party_test.go
- auth/services/selfsigned/signer.go
- discovery/test.go
- go.mod
- go.sum
- vcr/api/vcr/v2/types_test.go
- vcr/credential/validator.go
- vcr/credential/validator_test.go
- vcr/issuer/issuer.go
- vcr/issuer/issuer_test.go
- vcr/issuer/network_publisher.go
- vcr/issuer/network_publisher_test.go
- vcr/revocation/statuslist2021_issuer.go
- vcr/revocation/statuslist2021_issuer_test.go
- vcr/revocation/statuslist2021_verifier.go
- vcr/revocation/statuslist2021_verifier_test.go
- vcr/test/credentials.go
- vcr/test/openid4vci_integration_test.go
- vcr/verifier/signature_verifier_test.go
> Revert usage of validFrom and validUntil

- auth/auth.go
- auth/auth_test.go
- auth/client/iam/client.go
- auth/client/iam/openid4vp.go
- auth/client/iam/openid4vp_test.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/2995
> Auth: IAM client should not use PKI TLS config

- storage/gorm_logger.go
> Set SQL logging to TRACE instead of DEBUG

- docs/_static/vcr/vcr_v2.yaml
- vcr/api/vcr/v2/api.go
- vcr/api/vcr/v2/api_test.go
- vcr/api/vcr/v2/generated.go
> Ignore allowUntrustedIssuer for did:web and clarify 'revocation' in vcr/search

- auth/api/iam/api.go
- auth/api/iam/api_test.go
- auth/api/iam/generated.go
- docs/_static/auth/iam.yaml
Fixes https://github.com/nuts-foundation/nuts-node/issues/3031
> IAM: Expand InputDescriptorConstraintIdMap onto introspection response

- vdr/didweb/manager.go
- vdr/didweb/manager_test.go
fixes #3044 
check parsing error on creation and return err.
> fix DID creation with invalid tenant and default DID

- docs/pages/deployment/pex.rst
- docs/pages/release_notes.rst
- docs/pages/technology/saas.rst
Fixes https://github.com/nuts-foundation/nuts-node/issues/2952 (there were some leftovers)
> Docs: fix list styles

- vcr/test/openid4vci_integration_test.go
This is a fix for TestOpenID4VCIConnectionReuse fails on some systems #3069
Adjusted the computation for maximum expected connection in the OpenID4VCI integration test to only factor in the limit per host and number of transport instances, removing specific regard for IPv4 and IPv6, as well as per host limit validations. The connection total check has also been updated to validate directly against each host's new connections, ensuring each host does not exceed the maximum connection limit.
> Fix for TestOpenID4VCIConnectionReuse fails on some systems #3069

- docs/_static/vcr/vcr_v2.yaml
Fixes https://github.com/nuts-foundation/nuts-node/issues/3043
> VCR: document IssueVC() did:web and did:nuts specifics more clearly

- auth/api/iam/user.go
- auth/api/iam/user_test.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/3105
> IAM: nil deref when re-using same user session

- auth/api/iam/api.go
- auth/api/iam/api_test.go
> return 404 for missing token sessionID

- docs/_static/css/style.css
- docs/conf.py
- docs/pages/integrating/supported-protocols-formats.rst
Add DIIP list of components with green checkmarks where relevant. This should help with explaining what we do: implementing international set of protocols which are actively adopted by other Dutch industries.
> Add DIPP comparison to the docs

- auth/api/iam/openid4vp.go
- auth/api/iam/openid4vp_test.go
Improves https://github.com/nuts-foundation/nuts-node/issues/3007
> IAM: adjusted 'no credentials available' error message

- auth/api/iam/openid4vp.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/3062
> Auth v2: don't throw away errors

- .github/workflows/e2e-tests.yaml
old package cleanup was abandoned and broken.
> change package cleanup for e2e tests

- go.mod
- go.sum
fixes #3240
see nuts-foundation/go-leia#28
library update is enough for fix.
> update go-leia to v4.0.3

- docs/index.rst
- docs/pages/roadmap.rst
> remove roadmap from documentation

- auth/api/iam/api.go
- auth/api/iam/api_test.go
- auth/api/iam/generated.go
- docs/_static/auth/iam.partial.yaml
Fixes https://github.com/nuts-foundation/nuts-node/issues/3275
> Auth: remove root did:web metadata endpoint

- storage/engine.go
ignoring errors results in a goose chase in #3311
> don't ignore errors

- vdr/didsubject/did.go
- vdr/didsubject/did_test.go
- vdr/didsubject/management.go
- vdr/didsubject/management_mock.go
- vdr/didsubject/manager.go
As better alternative to `len(List())`
> VDR: Support SubjectManager.Exists()

- docs/pages/deployment/storage.rst
- storage/engine.go
- storage/engine_azuresql_test.go
The driver already supports it, we just needed to recognize the driver scheme (`azuresql://`)
> Storage: enable Azure SQL Support

- vdr/didsubject/manager.go
Make it align with the rest of the Nuts node. We have a INFO-level success message for business operation.
(and I'd like to know it when things go well).
> VDR: Added happy flow logging for subject manager

- auth/api/iam/api.go
- auth/api/iam/api_test.go
- auth/api/iam/generated.go
- docs/_static/auth/v2.yaml
- e2e-tests/browser/client/iam/generated.go
- e2e-tests/browser/openid4vp_employeecredential/main_test.go
> remove sub from access token introspection

- docs/_static/vdr/v2.yaml
- e2e-tests/browser/openid4vp_employeecredential/main_test.go
- vdr/api/v2/api.go
- vdr/api/v2/api_test.go
- vdr/api/v2/client.go
- vdr/api/v2/client_test.go
- vdr/api/v2/generated.go
- vdr/cmd/cmd.go
- vdr/cmd/cmd_test.go
oversight in change from DID to Subject. 
I'm fine dropping this if we don't want to make any API changes for this
> Rename CreateDID to CreateSubject

- storage/orm/did_document.go
- vdr/didsubject/did_document.go
- vdr/didsubject/did_document_test.go
> Auto set CreatedAt for new DID documents

- e2e-tests/ops/create-subject/docker-compose.yml
- e2e-tests/ops/create-subject/run-test.sh
- e2e-tests/ops/run-tests.sh
- storage/orm/did_document.go
- vdr/didnuts/manager.go
fixes #3368 
note: nuts did context is no longer used
> fix ordering of DID document context

- auth/api/iam/generated.go
- docs/_static/auth/v2.yaml
- e2e-tests/browser/client/iam/generated.go
- e2e-tests/oauth-flow/openid4vp/do-test.sh
- e2e-tests/oauth-flow/openid4vp/resource/nginx.conf
- e2e-tests/oauth-flow/rfc021/do-test.sh
- e2e-tests/oauth-flow/rfc021/node-A/nginx.conf
> Update to auth/v2/dpop/... paths

- docs/pages/deployment/recommended-deployment.rst
closes #3279 
only had to add discovery endpoint as optional endpoint.
> add discovery endpoint to deployment docs

- docs/_static/discovery/v1.yaml
> fix spec example

- docs/index.rst
- docs/pages/deployment/domain.rst
closes #3232 
top item for deployment
> added doc page on public url

- vdr/didnuts/didstore/store_test.go
- vdr/didnuts/didstore/writer.go
closes #3411
once a DID has been deactivated it should forever be considered deactivated after that. (did:nuts)
backport to v5 (situation does not exist on the production network, so no migration needed)
> VDR: once deactivated is always deactivated

- e2e-tests/oauth-flow/rfc021/node-A/nuts.yaml
- e2e-tests/oauth-flow/rfc021/node-B/nuts.yaml
- vcr/holder/presenter.go
- vcr/pe/presentation_submission.go
- vcr/pe/presentation_submission_test.go
- vcr/pe/test/test_definitions.go
- vcr/pe/types.go
fixes #3424 
removed multiple signing instructions from presentation builder.
> remove multiple signing instructions for presentation builder

- docs/_static/vdr/v2.yaml
- vdr/api/v2/api.go
- vdr/didsubject/interface.go
- vdr/didsubject/manager.go
- vdr/didsubject/manager_test.go
fixes #3426
returned some fixed errors from didsubject manager and mapped it to 400/409
> fix http status codes for did subject creation

- e2e-tests/migration/main_test.go
- storage/test.go
- vdr/didsubject/interface.go
- vdr/didsubject/manager.go
- vdr/didsubject/manager_test.go
- vdr/vdr.go
- vdr/vdr_test.go
builds on #3392 
closes #3330
original issue says to migrate verification methods, but I don't know what exactly should be migrated.
> migration: did:web for existing did:nuts

- auth/api/iam/api.go
- auth/client/iam/client.go
- auth/client/iam/client_test.go
- auth/client/iam/openid4vp.go
- auth/client/iam/openid4vp_test.go
- docs/_static/auth/v2.yaml
- vdr/didsubject/mock.go
fixes #3430 
some 500 => correct status codes based on early findings. I don't think this is the complete set. Will have to do some more tests using a fully setup https environment.
> fixes for rfc021 client status codes

- auth/api/iam/generated.go
- auth/client/iam/client.go
- auth/client/iam/client_test.go
- auth/client/iam/openid4vp_test.go
- docs/_static/auth/iam.partial.yaml
fixes #3437 
- OAS description and return error was wrong
- handle OAuthError in PD client
> fix OAS for presentation definition and client in handling correct status code

- docs/_static/vdr/v2.yaml
- vdr/api/v2/api.go
fixes #3428 
added some error to status codes mappings. Added some doc to the update/delete api spec on escaping the service ID.
> fix status codes on did service APIs

- discovery/store.go
- e2e-tests/oauth-flow/rfc021/do-test.sh
- e2e-tests/oauth-flow/rfc021/shared/discovery/definition.json
- vcr/revocation/statuslist2021_issuer.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/3442
> Discovery: fix GetActivationStatus on MS SQL Server

- e2e-tests/migration/main_test.go
- vdr/vdr.go
- vdr/vdr_test.go
> disable did:web migration

- discovery/module.go
- discovery/module_test.go
- policy/local.go
> fix configure for discovery service

- docs/pages/deployment/migration.rst
- docs/pages/integrating/version-incompatibilities.rst
- docs/pages/release_notes.rst
- e2e-tests/migration/main_test.go
- vdr/didsubject/manager.go
- vdr/didsubject/manager_test.go
- vdr/vdr.go
- vdr/vdr_test.go
> re-enable did:web migration

- discovery/api/server/api.go
- discovery/api/server/api_test.go
- discovery/api/server/client/http.go
- discovery/api/server/client/http_test.go
- discovery/api/server/client/interface.go
- discovery/api/server/client/mock.go
- discovery/api/server/client/types.go
- discovery/client.go
- discovery/client_test.go
- discovery/interface.go
- discovery/mock.go
- discovery/module.go
- discovery/module_test.go
- discovery/store.go
- discovery/store_test.go
- discovery/test.go
- docs/_static/discovery/server.yaml
- storage/sql_migrations/009_discoveryservice_seed.sql
closes #3463
all entries are wiped if seed changes.
> Add seed to discovery service protocol

- go.mod
- go.sum
- vcr/verifier/signature_verifier.go
- vcr/verifier/signature_verifier_test.go
> update go-did to v0.15.0

- e2e-tests/oauth-flow/rfc021/do-test.sh
- vcr/revocation/bitstring.go
- vcr/revocation/statuslist2021_issuer.go
> Add statuslist revocation to e2e-test and fix failing code

- docs/_static/vdr/v2.yaml
- vdr/didsubject/manager.go
- vdr/didsubject/manager_test.go
> allow _ in subject name

- crypto/crypto.go
- crypto/crypto_test.go
> fix invalid keyReference migration objects

- docs/index.rst
- docs/pages/release_notes.rst
Also added note/link to previous version of documentation on did:nuts network setup.
> docs: v6 release date

- .github/workflows/codeql-analysis-cron-schedule.yml
> change cron schedule

- .github/workflows/codeql-analysis-cron-schedule.yml
> Schedule CodeQL twice a week

- pki/interface.go
- pki/mock.go
- pki/validator.go
- pki/validator_test.go
part of #3530 (gRPC consequences need to be considered before closing that issue)
> PKI add ValidateStrict

- http/engine.go
closes #2957 - only ratelimit when did:nuts is in supoprted DID methods
closes #3539 - ratelimit VDR v2 APIs. DELETE APIs are already limited by creation of stuff to be deleted
> Ratelimit APIs that publish to the nuts network

- crypto/storage/vault/vault.go
- crypto/storage/vault/vault_test.go
- docs/pages/release_notes.rst
> fix vault key path/key

- docs/pages/release_notes.rst
create github releases after merge
> add release notes for v6.0.5 and previous

- .github/workflows/codeql-analysis-cron-schedule.yml
> Add scheduled CodeQL action to v6.0

- .github/workflows/codeql-analysis-cron-schedule.yml
> Add scheduled CodeQL action to V5.4

- .github/workflows/govulncheck-cron-schedule.yaml
> govulncheck: checkout branch for action

- core/server_config.go
don't print Redis password for session database
> Redact password for Redis in session DBs

- docs/pages/release_notes.rst
- vcr/credential/util.go
- vcr/credential/util_test.go
> fix holder credential autocorrect credentialsubject.id

- auth/api/iam/api.go
- auth/api/iam/api_test.go
- auth/api/iam/generated.go
- docs/_static/auth/v2.yaml
- e2e-tests/browser/client/iam/generated.go
- vcr/credential/util.go
> Reject self-asserted credentials with an issuer or credentialSubject.id

- http/echo.go
- http/echo_test.go
- http/engine.go
> Expose /status on public HTTP interface as well

- vcr/assets/assets/default.index.yaml
fixes #3801 
Before and after:
> Add index on subject with org credential

- docs/pages/development/2-releasing.rst
currently aren't displayed correctly
> fix links in docs

- .github/workflows/e2e-tests.yaml
- qlty.toml
added check for disabling e2e tests on forks disabled the tests on master as well.
> reenable e2e tests on master

- go.mod
- go.sum
> Update chi on v5.4 branch
