nuts-foundation/nuts-node

main.go
Main func is not calling CreateSystem, leading to engines not being registered.
Broken since https://github.com/nuts-foundation/nuts-node/pull/48
=> Fix main func not registering engines

README.rst, cmd/root.go, cmd/root_test.go, core/engine_test.go, crypto/crypto.go, crypto/crypto_test.go, crypto/engine/engine.go, crypto/engine/engine_test.go, crypto/test.go, network/api/v1/api.go, network/api/v1/api_test.go, network/config.go, network/engine/engine.go, network/engine/engine_test.go, network/interface.go, network/mock.go, network/network.go, network/network_integration_test.go, network/network_test.go, network/test.go, vdr/ambassador.go, vdr/engine/engine.go, vdr/engine/engine_test.go, vdr/vdr.go, vdr/vdr_test.go
- `NetworkEngine` instance (which wasn't the actual engine) renamed to `Transactions`
- Made instance/network instantiation explicit in root command
- Removed last singletons and configOnce's
- Added previously missing tests
=> Improved Instance/Engine naming and instantation

cmd/root.go
Broken since engine layer refactor. To prevent this in future I'd like an integration test suite.
=> Register core engine routes

cmd/root_test.go, core/echo.go, core/echo_test.go, development/docker-compose.yaml, development/nuts.yaml, docs/pages/production-configuration.rst
`Echo.Start()` is blocking, so only the first (default) echo server was started. Now it's using goroutines.
=> Fixed starting multiple Echo servers

crypto/api/v1/api.go, crypto/api/v1/api_test.go, crypto/crypto.go, crypto/crypto_test.go, crypto/interface.go, crypto/jwx.go, crypto/jwx_test.go, crypto/mock.go
SavePublicKey -> AddPublicKey which only accepts a creation time instead of period
Add RevokePublicKey method
Add ErrKeyNotFound on crypto level to prevent dependency on storage for error checking.
Add ErrKeyRevoked and ErrKeyAlreadyExists.
=> Improve PublicKeyStore interface

network/dag/parser.go, network/dag/parser_test.go
Fix #73 
Remove faulty check for presence of `kid` in embedded key in network document.
=> Remove check for kid in jwk

docs/pages/production-configuration.rst, network/network.go, network/network_test.go, network/p2p/impl.go, network/p2p/impl_test.go
While fixing the end-to-end test for the new implementation, found out that SSL offloading (for incoming Nuts Network connections) was broken.
=> Fix SSL offloading support for Nuts Network

vdr/cmd/cmd.go, vdr/cmd/cmd_test.go, vdr/vdr.go
Pointed out while fixing end-to-end tests.
=> Added logs to VDR and flags to print only the document or metadata

go.mod, go.sum
Fix IRMA schema updating when directory is mounted on different volume from tmp folder by updating to unreleased `irmago` commit. Tested it locally, it's fixed now.
=> Fix IRMA schema updating (os.Rename error)

development/nuts.yaml
IRMA directory configuration was removed in favor of deriving it from the global datadir config. This change reflects that in the development config.
=> Fix IRMA directory configuration for development config

network/p2p/impl.go, network/p2p/stats.go
Fixes #108 
Turned out while diagnosing the development network; peer ID is randomly generated at boot time and communicated to other nodes, but not logged or shown elsewhere. Add it to diagnostics so we can analyze the dev network better.
=> Network: Added diagnostic that returns the node's own Peer ID

Dockerfile
Is now inconsistent with default bind address (1323). Broken by https://github.com/nuts-foundation/nuts-node/pull/120
Also removed unused port 4222 (artifact from old nuts node).
=> Docker: Reverted HEALTHCHECK port change 

go.mod, go.sum
Fixes #153
Any change to a search clause in the vcr tests will now result in an error.
=> updated go-leia to v0.2.3

cmd/root.go, core/metrics_test.go, core/status/cmd.go, core/status/cmd_test.go, core/status/engine.go, core/status/engine_test.go
=> Provide CLI commands for querying node status and diagnostics

auth/services/messages.go, auth/services/messages_test.go, auth/services/oauth/oauth.go, auth/services/oauth/oauth_test.go
part fix for #163 
`kid` was put as claim in bearer token. When creating the access token it was expected to be there instead of the header.
=> fix correct kid extraction from parsing bearer token

core/client_config.go, core/server_config.go, core/server_config_test.go, docs/pages/production-configuration.rst
Much more convenient, not much less safe.
Fixes #78
=> Bind echo to all network ifaces by default

makefile, vdr/api/v1/generated.go
This removes the diff between oapicodegen and gofmt output.
=> run gofmt on generated code

vdr/ambassador.go, vdr/ambassador_test.go
The development network now shows some invalid DID documents since they're considered valid (without context for example). After this change they won't be considered valid any more.
Based on https://github.com/nuts-foundation/nuts-node/pull/176
=> VDR: Validate DID Documents using W3C spec validator

crypto/api/v1/api.go, crypto/api/v1/api_test.go
Now returns 400 for `ErrKeyNotFound` and 500 in all other cases
closes #182
=> Differentiate between SignJwt error returns

docs/_static/network/v1.yaml, docs/pages/monitoring.rst, network/api/v1/api.go, network/api/v1/api_test.go, network/api/v1/generated.go, network/dag/dotviz.go, network/dag/dotviz_test.go, network/interface.go, network/mock.go, network/network.go
Goal is to visualize it in Nuts Explorer.
=> Network: expose graphviz DAG visitor in API for visualization/analytical purposes

auth/api/v1/api.go, auth/api/v1/api_test.go, auth/api/v1/generated.go, crypto/api/v1/api.go, docs/_static/auth/v1.yaml, go.sum
part of #112
Standardizes API returns for the auth engine
=> AUTH: Standardize API returns

network/proto/blocks.go, network/proto/blocks_test.go
Getting the block date uses `getStartOfDay()` which should've taken the start of day in UTC, instead of the local timezone. Since otherwise they aren't comparable to the start of day timestamps of other peers in other timezones.
=> Network: fix incorrect timezone used in blockdate

network/dag/verifier.go, network/dag/verifier_test.go, network/network.go, network/proto/blocks.go, network/proto/blocks_test.go, network/proto/handlers.go, network/proto/handlers_test.go
Fixes #289 
- Calculate peer omnihash even when historic block differs (solves all-zeroes omnihashes)
- Reject transactions with a signing time further than 1 day in the future (makes determining heads much easier, if we keep it we should put it in the spec)
- Fix marking new transaction as head instead of the previous transaction if they're in the same block
The time-based blocks are complicated and I discovered more issues with it (next TX being in an older block). Should probably be rethought. (even if it's fixed for now)
=> Network: solve desync of historic block and omnihashes being all zeroed

network/p2p/connection.go, network/p2p/connection_test.go, network/p2p/impl.go, network/p2p/impl_test.go
P2P layer used connection out channel directly instead of using `send()` which is protected by a mutex.
=> Network: fix racy behaviour while broadcasting to a closing connection

didman/didman.go, didman/didman_test.go
So the method complies to its interface.
=> DIDMan: return ErrServiceNotFound when service to be deleted does not exist

network/proto/handlers.go, network/proto/handlers_test.go
Possible when a new message type is added but peers don't understand that message type (yet). Should not be possible when the gRPC interface enforces correct versions for peers, but might happen when we choose to support some degree of forward (and backward, in some cases) compatibility.
Other case might be that the peer actually sent an empty message.
=> Network: log empty messages (peer sent empty envelope or might have different protocol version)

core/echo.go, core/echo_test.go
Register Echo logger middleware but do not log calls to the status endpoint, since that gets called by the Docker healthcheck very, very often which leads to lots of clutter in the log.
=> Stop logging calls to /status (done by Docker healthcheck)

auth/api/v1/api.go, auth/api/v1/api_test.go, auth/api/v1/generated.go, docs/_static/auth/v1.yaml
codegen automatically generates models as `{operationName}Request` and `{operationName}Response`.
We also named our request and response JSON models that way. When generating client code, duplicates are created.
A simple rename does the trick
=> renamed auth api model

didman/didman.go, didman/didman_test.go
inside a did.Document.service, an `endpoint` needs to be a `map[string]interface{}`, `[]interface{}` or `string`. In didman a `ContactInformation` struct is set as `endpoint`, this trips the validation. This only recently became a problem when validation was added before publishing.
an alternative would be to change the adding of a service.
It should then marshal/unmarshal which would always fool the validator....
=> fix correct types for service

vdr/api/v1/generated.go
Changed in https://github.com/nuts-foundation/nuts-node/pull/325
=> Regenerate VDR API after change to OpenAPI spec

vdr/ambassador.go, vdr/ambassador_test.go, vdr/doc/resolvers.go, vdr/doc/resolvers_test.go, vdr/types/interface.go, vdr/types/mock.go, vdr/vdr.go
It currently resolves to the latest versions, which is incorrect.
Fixes #311
=> VDR: Use TX's signing time when resolving a DID document's controllers when updating

docs/pages/getting-started/4-connecting-crm.rst
fixes #327 
Example was missing `holder-did` and `organization` wrapper.
=> fix VC example in getting started manual

docs/_static/vdr/v1.yaml
fixes #328 
`one-of` can cause problems for some open api spec code generators. Better to stick to a single type, eg `object`.
=> removed one-of from vdr spec

auth/api/v1/api.go, auth/api/v1/api_test.go
Looks like the API originally intended to require RFC3339 but only supported numerical +/- timezones not separated by `Z`. RFC3339 format supports both.
=> Auth: parse dates for contract as RFC3339

network/network.go, network/network_test.go
To avoid nil deref while collecting diagnostics.
=> Network: make sure startTime is set before P2P layer is started

network/p2p/connection.go, network/p2p/connection_test.go
Access to `connection.messenger` was synchronized but could be nil, due to `receiveMessages()` using the messenger outside of the lock. Now it's checked for `nil` and if so, it indicates the connection is closed (or closing), so the function can simply return.
Fixes #346
=> Network: fix racy behaviour on nil connection.messenger due to peers parallel reconnect

auth/api/v1/generated.go, network/p2p/connection_mock.go
Apparentely it was out-of-date.
=> Regenerated code

docs/_static/vcr/v1.yaml, docs/_static/vdr/v1.yaml
closes #112 
All APIs now document error returns in the same way.
=> VDR & VCR: update docs

auth/services/x509/uzi_validator.go, auth/services/x509/uzi_validator_test.go
Correct UZI attribute name to `roleCode`
https://github.com/nuts-foundation/nuts-specification/pull/102
=> Auth: typo

network/dag/verifier_test.go
It seems like the `TestSigningTimeVerifier` unittest (specifically the "error - signed a day in the future" one) can fail if creating a test transaction takes longer than one second. Doesn't happen often but as CircleCI is "relatively" slow (DAG tests take 15s instead of 6s on my machine) it can fail even though it works just fine.
This PR adds one minute instead of one second to the signingtime so in theory it could still fail if creating the test transaction takes longer than one minute however it's very unlikely that will ever happen.
See: https://app.circleci.com/pipelines/github/nuts-foundation/nuts-node/1349/workflows/a77d6022-c272-469e-83de-2189a4e9cb2a/jobs/1359
=> Fix flaky signing time verifier test

vdr/store/memory.go
Development network is now broken, this makes it functional again.
Problem is still not fixed permanently though, since ultimately the 2 versions (in time) must be merged.
=> Temporarily fixes case when 2 versions of the same DID doc have the same signingTime where one removes a key

cmd/root.go, docs/_static/vcr/v1.yaml, vcr/api/v1/api.go, vcr/api/v1/api_test.go, vcr/api/v1/generated.go, vcr/concept/test.go, vcr/interface.go, vcr/mock.go, vcr/store_test.go, vcr/test.go, vcr/vcr.go, vcr/vcr_test.go, vdr/api/v1/generated.go
Closes #351 
Also part of nuts-foundation/nuts-specification#108, it solves the validity problem of VCs where the issuer has been deactivated.
This PR adds a `validate` and `validateForUse` private function to the vcr which does runtime checks.
The Resolve API now also has an optional `at` query param for resolving at a specific time.
=> Iss351 vc resolve period validation

auth/services/oauth/oauth_test.go, docs/_static/vdr/v1.yaml, vdr/api/v1/api.go, vdr/api/v1/api_test.go, vdr/doc/resolvers.go, vdr/doc/resolvers_test.go, vdr/types/common.go, vdr/types/interface.go
closes #372 
It now checks if the controller is not deactivated. If it is, it'll return an ErrDeactivated.
It still honours metadata.AllowDeactivated
=> added check to vdr.Resolve for deactivated controller

docs/_static/vdr/v1.yaml, vdr/api/v1/generated.go
Fixes #365 
Returning document.controller as object is the quickest and simplest way to fix this. 
The API returns a DIDDocument according to the go-did library not according to spec.
=> Return DID.controller as object

network/p2p/backoff.go, network/p2p/backoff_test.go, network/p2p/impl.go, network/p2p/impl_test.go
When 2 nodes configure each other as bootstrap node, a reconnect loop occurs because:
- They don't recognize an existing incoming connection from the configured bootstrap node as being from that node, because bootstrap nodes are configured with just their address, not their peer ID.
- When a connection to a bootstrap node closes it the local node immediately reconnects. When the remote node does the same, the result is racy: the second connection that succeeds will close the first, leading to a reconnection, etc.
Fix is 2-fold:
- When connecting to a bootstrap node, store its peer ID so we can check whether we're already connected (to a peer with that ID), before reconnecting.
- Wait a random duration before reconnecting to make the chance of simultaneously reconnecting to each other …
=> Network: fix reconnect loop for bootstrap nodes

network/p2p/connection.go, network/p2p/connection_test.go, network/p2p/impl.go
Part of #387, still needs to be solved definitively. This should make the development network working again.
=> Network: temporarily fix freezing nodes due to full channels, caused by increasing DAG

vcr/assets/NutsOrganizationCredential.config.yaml, vcr/vcr.go, vcr/vcr_test.go
Adds a `whitespaceOrExact` tokenizer which adds the input itself as a token as well to allow exact matches.
Closes: #386
=> Allow exact matches in VCR search

network/p2p/connection.go, network/p2p/impl.go, network/p2p/impl_test.go
It looks like adding yourself as a peer works (sort of) but can have unexpected side-effects such as the connection being closed and re-tried many times. This doesn't really work out in the unittest so @gerardsn and I changed it to connect to another peer.
=> Fix p2p test

auth/api/v1/api.go, auth/api/v1/api_test.go, auth/contract/template.go, auth/services/oauth/oauth.go, auth/services/oauth/oauth_test.go
Currently, the oath flow doesn't work without user identity because of two bugs:
1. In the OpenAPI spec the identity is a string but in our code it's a string pointer. Before this fix the empty string would be converted into an empty string pointer instead of `nil`
2. No identity means no contract validation (if I understand it correctly) this wasn't taken into account when creating the access token
=> Fix oauth flow without identity

.github/workflows/build-images.yaml
also for dependabot the secrets are not available.
=> skip docker login in docker action if not pushing

auth/services/oauth/oauth_test.go, didman/didman.go, didman/didman_test.go
Before it only resolved references from the endpoints specified by the compound service, not a reference to the compound service itself (the latter is how Nuts Registry Admin Demo currently registers endpoints).
=> DIDMan: GetCompoundServiceEndpoint should resolve reference to compound service as well

auth/services/oauth/oauth.go, auth/services/oauth/oauth_test.go
We need this in the demo EHR (specifically the `subject`). We could parse it from the JWT in the demo EHR but why would we if we already introspect the token to retrieve the `NutsAuthorizationCredential`s ?
=> Also include the public claims in token introspection

didman/didman.go, didman/didman_test.go
Missed this test before because the unit tests create a DID Document using the Go structs, instead of unmarshaling one.  I added a test to exactely mimic the DID Document structure as registry-admin-demo does it.
Before I cast the `serviceEndpoint` to a string, which is plainly wrong because many DID elements are always an array under the hood, so I had to use the unmarshal endpoint func instead.
=> DIDMan: fixed following ref to compound service endpoint with unmarshal instead of cast

network/p2p/impl.go, network/p2p/impl_test.go
When the `NUTS_NETWORK_BOOTSTRAPNODES` env/config variable is set, but empty, it results in a single (empty) bootstrap node address. Empty entries should be ignored.
=> Network: ignore empty bootstrap addresses

README.rst, development/nuts.yaml, docs/pages/getting-started/1-running-docker.rst, docs/pages/getting-started/3-configure-your-node.rst
Changed quite a while ago, docs were out of date appearantely.
=> Docs: fix bootstrap nodes example config

network/dag/bbolt_dag.go, network/dag/bbolt_dag_test.go, network/dag/interface.go, network/network_integration_test.go, network/network_pagination_test.go, network/p2p/impl.go, network/p2p/interface.go, network/proto/handlers.go, network/proto/impl.go, network/proto/senders.go, network/proto/senders_test.go
When number of transactions exceeds the maximum Protobuf message size.
Fixes https://github.com/nuts-foundation/nuts-node/issues/416
Also altered the behaviour of `dag.FindBetween`, it now returns the transactions in DAG walking order, to prevent out-of-order transactions (signing time) to be in the from page, preventing the receiving peer from processing the transactions (because it's previous transaction(s) are sent in a succeeding page, because its signing time lies before them). (edge case)
=> Network: split TransactionList response message in pages 

network/network.go, network/network_integration_test.go, network/network_test.go
Fixes 2 situations:
- All additional prevs (specified by caller) MUST be present, including its payload.
- All calculated prevs (heads of DAG) TX's payload MUST be present. If we specify TXs which' payload we're missing as prev, we can't answer peers querying us for that payload.
We do this by using a subscriber to determine the heads, because the subscriber only publishes transactions which' payload is present.
Fixes #469 by not prev'-ing TXs with missing payload.
=> Network: only use TXs as prev which' payload is present

network/network.go, network/network_test.go
Currently causes a nil dereference.
=> Network: handle missing transaction for GetTransactionPayload

auth/services/contract/notary.go, auth/services/contract/notary_test.go
When the wrong date is used, the error is misleading.
=> Fix error message of drawup contract call

docs/_static/vdr/v1.yaml, vdr/api/v1/api.go, vdr/api/v1/api_test.go, vdr/api/v1/client.go, vdr/api/v1/client_test.go, vdr/api/v1/generated.go, vdr/cmd/cmd.go, vdr/cmd/cmd_test.go, vdr/types/interface.go, vdr/types/mock.go, vdr/vdr.go, vdr/vdr_test.go
closes #456 
Added API that returns all conflicting docs and metadata. This will reflect the conflicting docs count in the diagnostics.
=> added API for finding conflicting docs

auth/services/oauth/oauth.go, auth/services/oauth/oauth_test.go, crypto/jwx.go, crypto/jwx_test.go, network/proto/impl_test.go
fixes #495
credential IDs are now added to the token.
=> fix missing credential IDs in access token

auth/services/oauth/oauth.go, auth/services/oauth/oauth_test.go, vcr/concept/test.go, vcr/credential/resolver.go, vcr/credential/validator.go, vcr/interface.go, vcr/mock.go, vcr/vcr.go, vcr/vcr_test.go
closes #494
The Validate method on the VCR now accepts an additional `checkSignature` param. VCs returned from local storage do not need this check, but VCs given via the API do.
=> check VC sig when creating access token

auth/api/v1/api.go, auth/api/v1/api_test.go, auth/api/v1/generated.go, auth/contract/verifier.go, auth/services/dummy/dummy.go, auth/services/dummy/dummy_test.go, auth/services/irma/validator.go, auth/services/irma/validator_test.go, auth/services/messages.go, auth/services/mock.go, auth/services/oauth/oauth.go, auth/services/oauth/oauth_test.go, auth/services/test.go, auth/services/types.go, auth/services/uzi/validator.go, auth/services/uzi/validator_test.go, auth/services/validator/validator.go, auth/services/validator/validator_test.go, docs/_static/auth/v1.yaml
closes #493 
made VPVerificationResult to an interface so we can use default claim names. The means used will then convert it from their own attribute names.
=> changed VPVerificationResult to interface and streamlined attributes

core/echo.go, core/echo_errors.go, core/echo_test.go
Adds custom logger middleware instead of using echo.RequestLogger because of this issue: https://github.com/labstack/echo/issues/2015
=> Use logrus as http request logger

core/echo_test.go, docs/_static/vdr/v1.yaml, network/transport/v1/protocol_v1_test.go, vdr/api/v1/api.go, vdr/api/v1/api_test.go, vdr/api/v1/client.go, vdr/api/v1/generated.go
Part of the #572 
Adding a versionId query param to the VDR getDID API call.
Resulting in:
```
GET http://localhost:1323/internal/vdr/v1/did/did:nuts:9uJ8V9aQ1vSoe3fj7ipnMVsnR5Kq6dxmkb7GmdBPntuC?versionId=e6efa34322812bd5ddec7f1aa3389957a2c35d19949913287407cb1068e16eb9
```
=> Add versionId param to api/vdr/getDID

docs/_static/vdr/v1.yaml, vdr/ambassador.go, vdr/ambassador_test.go, vdr/types/common.go, vdr/types/common_test.go
Part of #572 
Adds a `previousHash` property to resolver metadata:
```json
{
"document": {
"@context": "https://www.w3.org/ns/did/v1",
"id": "did:nuts:9uJ8V9aQ1vSoe3fj7ipnMVsnR5Kq6dxmkb7GmdBPntuC"
},
"documentMetadata": {
"created": "2021-11-02T10:53:25Z",
"updated": "2021-11-02T15:15:49Z",
"hash": "223f884b812027c3da02975e117741910491d0491f689e26d2557aec39e07f46",
"previousHash": "e6efa34322812bd5ddec7f1aa3389957a2c35d19949913287407cb1068e16eb9",
"txs": [
"68a2a3d13dc245abdf7ff9330d3710cc4d8e2c564c9d9efb3a6c8012f0654c5c"
],
"deactivated": true
}
```
=> Add prev document hash to metadata

docs/_static/vdr/v1.yaml, vdr/api/v1/api.go, vdr/api/v1/api_test.go, vdr/api/v1/generated.go
Part of #572
Allows to search for a DID version active at the given time.
=> Add versionTime param to api/vdr/getDID

auth/auth_test.go, cmd/root_test.go, network/cmd/cmd.go, network/config.go, network/config_test.go, network/network.go, network/network_integration_test.go, network/network_test.go, network/test.go, vdr/integration_test.go
Was previously derived from `CertFile` and `CertKeyFile` being set, but this didn't actually work. Changed it to be set explicitly, with default = `true`. Also logs a warning when one of the cert/key properties is set, but TLS is disabled.
=> Network: enable TLS by default, do not derive from other properties

network/transport/grpc/connection.go, network/transport/grpc/connection_manager.go, network/transport/grpc/connection_manager_test.go, network/transport/grpc/connection_test.go
This could prevent a client from reconnecting in certain edge cases (e.g. TCP connection got closed by a network device). Fix is backported from https://github.com/nuts-foundation/nuts-node/pull/571
=> Network: clean up closed inbound connections

didman/api/v1/api.go, didman/api/v1/api_test.go
=> DIDMan: return empty array instead of null in REST API calls

vdr/store/bbolt.go, vdr/store/bbolt_test.go
This is only the 'bare' implementation + tests. Need to configure it by default and test it using my local nuts node (but maybe that could be in a different PR?).
The tests are copied from the `MemoryStore` tests so we can verify it works more or less the same.
Fixes #109
=> Implemented a persisent version of the vdr store

network/network.go, network/network_test.go
Currently, the node starts connecting to bootstrap nodes while still configuring and starting, which causes DAG sync'ing because the node looks out of date, while the DAG is still loading.
It needs to wait to start connecting to nodes until all other services are started.
=> Network: connect to bootstrap nodes during start instead of configuration phase

network/network_integration_test.go, network/transport/grpc/connection.go, network/transport/grpc/connection_test.go
Based on https://github.com/nuts-foundation/nuts-node/pull/635 (rebase first).
Currently, the peer ID is never reset, while it is randomly generated when a node starts. That way, when a bootstrap node restarts, its peers aren't able to reconnect (because it sends a new peer ID after the restart). Peer ID should be reset/emptied when a peer disconnects, then it can be set again when it reconnects.
=> Network: reset peer ID when connection closes

vcr/ambassador.go, vcr/ambassador_test.go, vcr/interface.go, vcr/mock.go, vcr/store.go, vcr/store_test.go
fixes #633 
At startup all TXs are replayed from the DAG. Any VC is then written to the VCR. Before it's written a validation takes place, this validation is always done against the current time, not the signing time.
=> validate replayed VCs at signing time

cmd/root.go, cmd/root_test.go, core/engine.go, core/engine_mock.go, core/engine_test.go, crypto/mock.go, network/transport/connection_manager_mock.go
This will allow engines to perform migrations before they are started.
How they do this and how they track historic migrations is up to the engine.
=> add migration feature to engine

docs/_static/vdr/v1.yaml, docs/pages/getting-started/4-connecting-crm.rst, vdr/ambassador.go, vdr/api/v1/api.go, vdr/api/v1/api_test.go, vdr/doc/creator.go, vdr/doc/creator_test.go, vdr/doc/merge.go, vdr/integration_test.go, vdr/vdr_test.go
* Only when the DID document is owned by the node
Fixes https://github.com/nuts-foundation/nuts-node/issues/627
=> Enable KeyAgreement by default on DID document creation

auth/auth_test.go, auth/services/contract/notary_test.go, auth/test.go, cmd/root.go, core/engine.go, didman/api/v1/api.go, didman/api/v1/api_test.go, didman/didman.go, didman/didman_test.go, didman/mock.go, didman/types.go, go.mod, go.sum, network/interface.go, network/network.go, network/transport/connection_manager.go, network/transport/v1/logic/blocks_test.go, vcr/api/v1/api.go, vcr/api/v1/api_test.go, vcr/concept/phonetics.go, vcr/concept/phonetics_test.go, vcr/config.go, vcr/interface.go, vcr/mock.go, vcr/store.go, vcr/test.go, vcr/vcr.go, vcr/vcr_test.go
fixes #612 
a migration is added that removes the current VCR DB. This is allowed as long as the DAG is walked at startup. When that stops the migration must be removed.
=> update to go-leia/v2

network/transport/v1/p2p/impl.go, network/transport/v1/p2p/impl_test.go
Now and then fails during test.
Caused by missing `err` check.
=> Network: fix nil deref when existing connection fails to open v1 stream

auth/auth.go, auth/auth_test.go, core/tls.go, network/transport/grpc/connection_manager.go, network/transport/grpc/connection_manager_test.go
When using `tls.Config` be sure to set the `MinVersion` because:
>	// If zero, TLS 1.0 is currently taken as the minimum.
Which is obviously not what we want.
=> Set min TLS version to 1.3

network/network_integration_test.go, network/transport/grpc/connection.go, network/transport/grpc/connection_manager.go, network/transport/grpc/connection_manager_test.go, network/transport/grpc/outbound_connector.go, network/transport/grpc/outbound_connector_test.go
Changes:
- When a gRPC stream fails to open (e.g. protocol v1 or v2), log this as a protocol-level error, rather than connection level failure.
- Outbound connections: don't try other protocols when node DID of the peer fails (optimization, declutters log)
- Outbound connections: backoff when node DID authentication fails
=> Network: improve logging and backoff in case Node DID authentication fails

core/server_config.go, core/server_config_test.go, core/test.go, network/config.go, network/transport/v1/protocol_v1.go
It seems like with `FlatPaths` set to `true` in koanf we can't parse configuration when using child structs. With this PR you can use a struct or pointer to a struct and it will unmarshal the configuration recursively. However, at some point we might want to think about building a library ourselves that handles flags, environment variables and configuration files.
Note that it uses the `koanf` tag to determine the path. So, this will work:
```go
type TestConfig struct {
Example string `koanf:"test.example"`
Inner InnerConfig `koanf:"test.inner"`
}
type InnerConfig struct {
Example string `koanf:"example"`
}
```
With the following YAML configuration:
```yaml
test:
example: value
inner:
example: value2
```
=> Make inject config work recursively

crl/validator.go, crl/validator_test.go
Log issuer name where available, otherwise log CRL endpoint (in case of network errors)
Fixes https://github.com/nuts-foundation/nuts-node/issues/674
=> Improve CRL synchronization errors

auth/services/oauth/oauth.go, auth/services/oauth/oauth_test.go, auth/services/services.go
Randomly fails because the clock skew is too small now and then.
Also made the use of `time.Duration` appropriate.
=> Auth: fix clockskew test by making the skew larger (slow CirlceCI)

network/transport/grpc/connection.go, network/transport/grpc/connection_manager.go, network/transport/grpc/connection_test.go
Happens now and then on CircleCI, can theoretically happen runtime as well.
`close()` causes `context()` to return `nil` (which is valid), callers should handle it. Introduced `waitTilClosed()` to reduce chance of errornous use.
=> Network: fix call on nil context due to racy connection close

vdr/doc/finder.go, vdr/doc/finder_test.go, vdr/types/interface.go, vdr/vdr.go, vdr/vdr_test.go
This adds a DocFinder interface to the VDR.
It supports finding DID Documents with specific predicates.
Stole Predicate setup from @dmeijboom ;)
This feature is required for service discovery. At startup, the network needs to find all did Documents with a concrete NutsComm address.
=> add Finder to VDR

vcr/test.go, vcr/vcr.go, vcr/vcr_test.go
fixes #698 
the vcr translates the DIDs in the VC to their `NutsComm` service owners.
After merge, notify Slack channel on changes since issuing a private VC will no longer work without a node identity.
=> find NutsComm service owners for private credentials

network/network.go, network/network_integration_test.go, network/network_test.go, network/transport/connection_manager.go, network/transport/connection_manager_mock.go, network/transport/connection_manager_test.go, network/transport/grpc/authenticator.go, network/transport/grpc/authenticator_test.go, network/transport/grpc/connection_manager.go, network/transport/grpc/connection_manager_test.go, network/transport/types.go, network/transport/v1/protocol_v1_integration_test.go, network/transport/v2/handlers.go, network/transport/v2/handlers_test.go
fixes #699 
Adds a bool to `Connect` allowing unauthenticated connections to bootstrap nodes.
=> allow connection to bootstrapnode

network/transport/grpc/connection.go, network/transport/grpc/connection_list.go, network/transport/grpc/connection_list_test.go, network/transport/grpc/connection_manager.go, network/transport/grpc/connection_manager_test.go, network/transport/grpc/connection_test.go
Previously caused calling `Stop()` while a new inbound connection is received caused the Connection Manager to deadlock, being blocked by `conn.waitUntilDisconnected()` which blocks `GRPCServer.GracefulStop()`.
Solved by having the context `conn.waitUntilDisconnected()` waits for, derive from a parent context supplied by ConnectionManager, which is cancelled when `Stop()` is called.
=> Network: fix ConnectionManager shutdown deadlock due to GRPCServer.GracefulStop()

events/event.go
Now logged twice:
```
time="2022-01-06T14:38:07Z" level=warning msg="Revocation-supporting private key installed for irma-demo.MijnOverheid.root, but no revocation server is configured: issuance sessions will always fail"
time="2022-01-06T14:38:07Z" level=info msg="started Event manager" module=events
time="2022-01-06T14:38:07Z" level=info msg="started Event manager" module=core
```
=> Events: removed 'started Events manager' log, since it's already logged by core

vcr/config.go, vcr/test.go, vcr/vcr.go
Instead of setting config from the server config it was overridden which means that the default flags were ignored in the VCR
=> Make sure the override public flag is set properly

network/network.go, network/network_test.go
Taken from https://github.com/nuts-foundation/nuts-node/pull/708/commits/b1fc658016b22bd13cc8b5b94dea465e82c79c33
The `nodeDIDResolver` passed to `v2.New()` (create v2 protocol instance) got passed the default, emtpy node DID resolver. After that, it's overwritten with a resolver that contains the actual node DID. But since it's overwritten, v2 doesn't get the new, populated node DID resolver. Leading to node DID not being populated when encountering a private TX. Simply moving the initialization be before the protocol init fixes this.
Not really unit testable, since it calls package functions (`v2.New`), which can't be mocked. It's also a private member of v2 protocol, so not accessible for assertion. Integration-testable by https://github.com/nuts-foundation/nuts-node/pull/708
=> Network: fix node DID not being passed to v2

auth/services/irma/signer.go, auth/services/irma/signer_test.go, auth/services/irma/validator_test.go
Hotfix for now. This should be 'redesigned' as currently we are checking every signer for a specific error (whether a session was found or not) until one either returns no error or another error. This will break when third-party libraries (such as IRMA) decide to raise other errors but with the same meaning.
=> Return session not found in IRMA signer if a session was not found

network/dag/bbolt_dag.go, network/dag/bbolt_dag_test.go
DAG observers are currently notified when a TX was passed to `Add()` which already existed on the DAG. This never caused issues, but https://github.com/nuts-foundation/nuts-node/pull/741 assumes its `transactionAdded()` function is called only once per TX, because otherwise it emits duplicate `TransactionAddedEvent`s.
It would not be a big issue since all subscribers should be idempotent, but it might cause unneeded logging/confusion/load. Thus we should avoid if we can do so with relative ease.
=> Network: don't notify observers when TX isn't added to DAG

network/dag/publisher.go, network/dag/publisher_test.go, network/dag/replayer.go
Now publishes `TransactionAddedEvent` directly when a new TX is added to the DAG. Had to rework DAG replay, because otherwise it wouldn't be emitted.
Consequence is that `Publisher` now relies heavily on the calling of `transactionAdded` and `payloadWritten`, especially the first one. It must be called in correct order for the emitted events to be in correct order. But luckily, that is the DAG's job, which does it well.
=> Network: emit TransactionAddedEvent in unblocking fashion

vcr/vcr.go, vcr/vcr_test.go, vdr/ambassador.go, vdr/ambassador_test.go, vdr/doc/resolvers.go, vdr/doc/resolvers_test.go
It has a double fix. The callback first searches for docs based on the TX hash, if found it skips the update.
If a creation has been recorded from a different TX it'll merge the two creations.
=> Fix duplicate did document creation

network/dag/publisher.go, network/dag/publisher_test.go
This only occurs when a TX is created by the local node.
=> Network: do not log error when missing TXs for written payload

vcr/vcr.go, vcr/vcr_test.go, vdr/types/interface.go
fixes #743 
Passing resolveMetadata enables the controller active check.
=> pass ResolveMetadata for resolving VC issuer

crypto/crypto.go, crypto/interface.go, crypto/mock.go, crypto/storage/fs.go, crypto/storage/fs_test.go, crypto/storage/mock.go, crypto/storage/storage.go, crypto/storage/vault.go, crypto/storage/vault_test.go, crypto/test.go, network/network.go, network/network_test.go, network/transport/connection_manager.go, network/transport/connection_manager_mock.go, network/transport/nodedid.go, network/transport/nodedid_test.go
When not configured and not in strict mode, allow the node DID to be auto-resolved. It's matched by intersecting DID documents with a NutsComm URL endpoint and the private keys in the keystore.
Fixes https://github.com/nuts-foundation/nuts-node/issues/621
=> Network: auto-resolve node DID

vcr/vcr.go, vcr/vcr_test.go, vdr/doc/resolvers.go, vdr/doc/resolvers_test.go, vdr/types/interface.go
Better fix for #743.
Instead of providing an empty resolverMetadata (or a time), make checking for disabled controllers default.
=> VDR: Fix resolving disabled DID docs

network/transport/grpc/authenticator.go, network/transport/grpc/authenticator_test.go
In the authenticator we currently match the NutsComm address with one of the SANs. This is done by a regular comparison which means that it will be case sensitive but RFC5280 states that it should be case-insensitive. 
See: [RFC5280](https://www.rfc-editor.org/rfc/rfc5280#section-4.2.1.6)
=> Match SANs case insensitive in protocol v2 authentication

core/status/engine.go, core/status/engine_test.go, crypto/hash/sha256.go, crypto/hash/sha256_test.go
We already supported JSON for easier consumption by systems, but the text view became less and less readable. Returning the text view in YAML format makes reading much easier (because of its indentation), less work (use Go's default YAML marshaler) and lets other systems parse the node's diagnostics as YAML too (aside from JSON).
Fixes https://github.com/nuts-foundation/nuts-node/issues/467
=> Diagnostics: change text view to YAML for improved readability

network/transport/v1/logic/handlers.go
When starting a new node or a new node connects to the local node, sync'ing the complete DAG, the log (on both sides) is be littered with the following messages:
```
time="2022-01-27T10:53:42Z" level=info msg="Peer's historic block differs which will be sync-ed for now, but will be disallowed in the future (peer=b3f308de-630d-4c63-a77a-16c6b7cf1d4f,local hash=2ba4abfb214b2379a35668e559c43590854c4aa5f5779f3bf498b560a3dfc8c9,peer hash=45978d76a009ceef5e8bff24d2c94b38af6f0b931ae9ea47c864934299da4b03)" module=Network
time="2022-01-27T10:53:42Z" level=info msg="Peer queries historic block which is supported for now, but will be disallowed in the future (peer=53b37e3d-cab4-48cb-a40f-87e2e49250cc)"
```
These are part of the v1 protocol DAG sync, which will be replaced by v2 before disallowing …
=> Network: log historic block queries on debug instead, since it will be replaced by v2

core/status/engine.go, core/status/engine_test.go
It adds little value: engines are registered hardcoded, so there can't be really any confusion on what engines there are (to developers). It's leftover from the previous version of the Nuts node which allowed engines to be disabled for a specific node instance. Also: it's useless information for the users of the Nuts node viewing the diagnostics. 
It takes up browser viewport space when viewing it, so we're probably better of without it.
=> Diagnostics: remove engine list

network/network_integration_test.go, network/transport/grpc/connection.go, network/transport/grpc/connection_manager.go, network/transport/grpc/connection_manager_test.go, network/transport/grpc/connection_mock.go, network/transport/grpc/test.go
Since introducing service discovery, nodes will connect to each other if they both published their `NutsComm` endpoint. We have an integration test which tests this bi-directional connection (node A and B both connect to each other), but the assertions in that test was wrong. And it appears to be broken, leading to a reconnect loop:
```
time="2022-01-24T08:13:23Z" level=info msg="Connected to peer (outbound): nuts.woutslakhorst.nl:5555" module=Network
time="2022-01-24T08:13:23Z" level=warning msg="/transport.Network/Connect: Peer connection error (peer=8fe5a452-2bc0-436d-8e22-2e97d0b53b8b(did:nuts:3wEb8GJEuenjMexQXKfrdAr8CvA69SdbVh8qhUpDMcX2)@): rpc error: code = Unknown desc = already connected" module=Network
time="2022-01-24T08:13:23Z" level=warning msg="/v2.Protocol/Stream: Peer …
```
=> Network: allow bi-directional connections to be deduplicated

cmd/root.go, cmd/root_test.go, core/echo.go, core/echo_mock.go, core/engine.go, core/test.go, events/event.go, main.go, main_test.go, network/transport/grpc/connection_manager.go, test/http/server.go
Currently, the Nuts node isn't shut down at all. This risks data corruption and sending avoidable errors to network peers.
This PR introduces signal trapping to instruct the engines to shut down. It also has some fixes for existing problems with the shutdown.
=> Core: properly shutdown node on OS interrupt

main_test.go
Otherwise is can cause issues when running locally when you have an (git ignored) `nuts.yaml` in the project root.
=> Fix main test: do not load nuts.yaml from repo root

network/transport/grpc/backoff.go, network/transport/grpc/backoff_test.go
The maximum backoff value (max. time waited before trying to reconnect to a peer) is currently 30 seconds. With configured bootstrap nodes this was fine.
However, now anyone can publish their node's address, to be discovered and connected to. When DID documents with `NutsComm` services are abandoned, this leads to dead endpoints which will be retried every 30 seconds (given there's no node to connect to at the published endpoint), see log below.
If we increase the max. backoff, it won't clutter the log every 30 seconds. I suggest increasing it to 1 hour.
These were the intervals with max = 30s (given some randomness with each step):
```
1.5s
2.25s
3.375s
5.0625s
7.59375s
11.390625s
17.0859375s
25.62890625s
30s
```
And these with max = 1h:
```
1.5s
2.25s
3.375s
5.0625s
7.59375s
11.390625s …
```
=> Network: increase max backoff to declutter log

main_test.go, network/dag/state.go, test/node.go, vcr/issuer/interface.go, vcr/issuer/leia_store.go, vcr/issuer/leia_store_test.go, vcr/issuer/mock.go, vcr/vcr.go, vcr/vcr_test.go
Order of starting publisher/verifying DAG was incorrect. Caused VDR to be empty when the DAG was verified, thus keys were missing for checking signatures.
Fixed and introduced an integration test to assert starting a node with existing DAG works properly. Also found a bug in VCR due to leia store not being closed on shutdown.
=> Network: fix startup/verify order of DAG state

network/dag/bbolt_dag.go, network/dag/interface.go, network/dag/mock.go, network/dag/publisher.go, network/dag/state.go, network/dag/state_test.go, network/storage/bbolt_context.go, network/transport/v1/protocol_integration_test.go, test/predicates.go
fixes #799
a dag.State observer can now be called with or without a transactional context.
=> split dag.State observers in transactional and non-transactional

network/cmd/cmd_test.go, network/dag/bbolt_dag.go, network/dag/bbolt_dag_test.go, network/dag/dotviz_test.go, network/dag/parser.go, network/dag/parser_test.go, network/dag/publisher_test.go, network/dag/signing.go, network/dag/signing_test.go, network/dag/test.go, network/dag/transaction.go, network/dag/transaction_test.go, network/dag/verifier.go, network/dag/verifier_test.go, network/network.go, network/network_test.go, network/transport/v1/logic/payload_collector_test.go, network/transport/v1/protocol_integration_test.go, network/tx.go, vcr/ambassador_test.go
closes #779 
some parts are marked with `deprecated` to make sure when LC is mandatory to reduce code complexity.
=> add LC to new transactions and verify them when they are parsed

network/transport/v2/conversation.go, network/transport/v2/conversation_test.go, network/transport/v2/handlers.go, network/transport/v2/handlers_test.go, network/transport/v2/protocol.go, network/transport/v2/protocol.pb.go, network/transport/v2/protocol_test.go
closes #819
This is just the managing of conversations.
The `TransactionListQuery` and `TransactionList` messages are supported. This does not mean those messages are implemented in the protocol. It's just to show how the response checking works.
=> added conversation manager to v2 protocol

cmd/root.go, didman/cmd/cmd.go, didman/cmd/cmd_test.go
Useful for registering NutsComm endpoint, e.g.:
```
nuts didman svc add did:nuts:Ey1KsopGGroX5pqTbNntWLALXuJv4ze9jZqdaSSKU5WX NutsComm grpc://swvjdvpt-grpc.nnaas.reinkrul.nl:5555
```
or registering a compound endpoint:
```
nuts didman svc add did:nuts:Ey1KsopGGroX5pqTbNntWLALXuJv4ze9jZqdaSSKU5WX some-service '{"foo": "bar"}'
```
=> DIDMan: provide CLI commands for registering/deleting endpoints

vdr/store/bbolt.go, vdr/store/bbolt_test.go
fixes #834
The scope of the return false was wrong, so it only succeeded if the first item in the list was a match.
=> correct VDR bbolt filtering on source TX

network/dag/state.go, network/dag/state_test.go
This causes a race condition during test and does not add any extra functionality. The DB connection is non-recoverable.
=> remove setting field to nil after shutdown

events/integration_test.go
Another test failing often.
The waitFor only checks every 10ms. So a total timeout of 10ms is a bit short.
=> increase test timeout for pubsub test

core/diagnostics.go, core/diagnostics_test.go, network/dag/bbolt_dag.go, network/dag/state_test.go, network/network.go, network/network_test.go, network/transport/v1/logic/impl.go, network/transport/v1/logic/impl_test.go, network/transport/v1/logic/stats.go
Was previously a relatively flat list, further grouped the diagnostics of `ConnectionManager`, the protocols and DAG state.
New format:
```
network:
connections:
connected_peers:
- id: 7f6f07c3-ec37-4a90-b39b-df9a970c2578
address: 172.21.0.4:36196
nodedid: ""
acceptunauthenticated: false
- id: 0ec2ffc0-3093-4660-b819-ce821da2877e
address: 172.21.0.2:38142
nodedid: ""
acceptunauthenticated: false
connected_peers_count: 2
outbound_connectors: []
peer_id: d1052df5-29b4-4ac0-ad99-89785b8e8cba
node_did: ""
protocol_v1:
missing_payload_hashes: []
peer_omnihashes:
0ec2ffc0-3093-4660-b819-ce821da2877e: ef82d2e2cc6474b77c7a44d1d11b416513b8c7709d199c48f5a30c7f79b50498
7f6f07c3-ec37-4a90-b39b-df9a970c2578: ef82d2e2cc6474b77c7a44d1d11b416513b8c7709d199c48f5a30c7f79b50498
protocol_v2: …
```
=> Further group network diagnostics

network/dag/state.go, network/dag/state_test.go, network/network_integration_test.go, network/transport/grpc/connection_list.go, network/transport/v2/conversation.go, network/transport/v2/conversation_test.go, network/transport/v2/handlers.go, network/transport/v2/handlers_test.go, network/transport/v2/protocol_integration_test.go, network/transport/v2/protocol_test.go, network/transport/v2/senders.go, network/transport/v2/senders_test.go
Closes #832 
There are some todo's in there. They are a reminder to change after the entire v2 protocol is implemented and tested.
During implementation, some questions regarding the protocol came up:
TODO:
=> Adds TransactionListQuery and response to v2 protocol

docs/_static/vcr/v2.yaml, vcr/api/v2/generated.go
The Go generator doesn't fail on this, but for other languages it does.
=> VCR: Fix OAS response for VC search operation

cmd/root.go, cmd/root_test.go, network/dag/verifier.go, network/dag/verifier_test.go, vdr/ambassador.go, vdr/ambassador_test.go, vdr/doc/resolvers.go, vdr/store/bbolt.go, vdr/store/bbolt_test.go, vdr/store/memory.go, vdr/store/memory_test.go, vdr/types/common.go, vdr/types/interface.go, vdr/types/mock.go
closes #846 
fixes #878 
Added check if transaction has already been processed. Startup is 30 seconds faster on a macBook compared to previous implementation.
I also replaced the fixed date check for resolving key by ref or date. It now first tries by ref and then by date. After v2 by date could be removed
=> rewrote VDR persistent store

vcr/verifier/verifier.go, vcr/verifier/verifier_test.go
According to RFC011, VCs must have the type `VerifiableCredential` and one additional type.
=> VCR: Validate vc.type

makefile, vcr/api/v2/generated.go, vcr/api/v2/holder.go, vcr/api/v2/holder_test.go, vcr/api/v2/types.go
Required to properly support variants of data types (single value v.s. list) of VCs.
=> VCR: SearchVC() unmarshal query as VC instead of map

vcr/api/v2/holder.go, vcr/api/v2/holder_test.go
Currently broken, because it searches for NutsOrganizationCredentials.
=> VCR: Fix v2 search for NutsAuthorizationCredential

vcr/api/v2/api.go, vcr/api/v2/api_test.go, vcr/credential/validator.go, vcr/credential/validator_test.go
As specified by OAS:
> The resolvable context of the credentialSubject as URI. If omitted, the "https://nuts.nl/credentials/v1" context is used. Note: it is not needed to provide the "https://www.w3.org/2018/credentials/v1" context here.
=> VCR: Verify Nuts LD context is present for Nuts and set it by default

network/dag/bbolt_tree.go, network/dag/bbolt_tree_test.go, network/transport/grpc/outbound_connector_test.go
This way it's not influenced by timing or externally started goroutines
=> Network test fix: assert on number of completed rollback TXs

crypto/hash/sha256.go, crypto/hash/sha256_test.go, network/dag/tree/iblt.go, network/dag/tree/tree_test.go, network/dag/tree/xor.go, network/dag/tree/xor_test.go
The xor of hashes is needed in more places than the tree package. (currently implemented in transport/v1 & dag/tree, and needed in transport/v2)
This place made the most sense for me to add it as a public method.
Should this be an in-place operation?
=> Add hash.Xor

auth/services/oauth/oauth.go
Provides some insight for operators.
It could be a bug/misconfiguration, or an attacker.
=> Auth: log warning if access token request organization mismatches the user identity

network/transport/v2/gossip/manager_test.go
=> Network: fix negative waitgroup counter in gossipmanager test

main_test.go, network/network.go, network/transport/grpc/backoff.go, network/transport/grpc/backoff_test.go, network/transport/grpc/connection.go, network/transport/grpc/connection_list_test.go, network/transport/grpc/connection_manager.go, network/transport/grpc/connection_manager_test.go, network/transport/grpc/connection_mock.go, network/transport/grpc/outbound_connector.go, network/transport/grpc/outbound_connector_test.go, network/transport/grpc/test.go, network/transport/v1/protocol_integration_test.go, network/transport/v2/protocol_integration_test.go
Persists the backoff for outbound connectors to BBolt.
Decided to persist the moment (date/time) of the next retry rather than the backoff interval, because then the interval over restarts stays more or less the same. Otherwise it would reconnect immediately after a restart (or just after the max. backoff).
Fixes https://github.com/nuts-foundation/nuts-node/issues/891
=> Network: persisted outbound connector backoff

network/transport/grpc/connection_manager_test.go, network/transport/v2/senders.go, network/transport/v2/senders_test.go
Asserts the (hardcoded) overheads against the actual message size.
=> Network: fix message overhead for chunked TransactionList

jsonld/ldutils.go, vcr/issuer/issuer.go, vcr/issuer/issuer_test.go, vcr/issuer/keyresolver.go, vcr/issuer/keyresolver_test.go, vcr/signature/json_web_signature.go, vcr/signature/json_web_signature_test.go, vcr/signature/proof/jsonld.go, vcr/signature/proof/jsonld_test.go
Fix status code of 500 to 400 when issuer not found
Fix duplicate messages like: "unable to canonicalize document: unable to normalize document: foo"
Fixed typo in error message.
=> Fix unclear error messages

network/transport/v2/conversation.go, network/transport/v2/conversation_test.go, network/transport/v2/handlers.go, network/transport/v2/handlers_test.go, network/transport/v2/protocol.go, network/transport/v2/senders.go, network/transport/v2/senders_test.go, network/transport/v2/transactionlist_handler.go, network/transport/v2/transactionlist_handler_test.go
#861 aims to limit the number of conversations to 1, but this would be too strict. 
The `TransactionSet` for example can be followed by `TransactionListQuery` and `TransactionRangeQuery`. It should also be possible request newly Gossiped transactions from multiple peers at the same time. Limiting a node to 1 active range query means that it can only perform set reconciliation with 1 peer at a time.
=> Network: limit node to 1 active conversation per peer

vcr/api/v2/types.go
Instead of using a VerifiableCredential from the go-did library as search param use a custom one which is less strict and allows empty fields.
=> Add SearchVCQuery type

echo/echo_integration_test.go, echo/nuts.yaml
closes #1067
This tests if echo is correctly translating our errors to the correct status codes.
=> added API integration test that tests 404s

network/transport/v2/senders.go, network/transport/v2/senders_test.go
backport of fdbbe8a3e70f9640d47c029eabaabec18092868d
=> increase overhead margins

crypto/api/v1/api.go, crypto/crypto.go, crypto/crypto_test.go, crypto/interface.go, crypto/jwx.go, crypto/jwx_test.go, crypto/test.go, network/dag/pal.go, network/transport/v2/protocol_test.go, vdr/vdr.go, vdr/vdr_test.go
Otherwise one could assume it's because a DID document is missing a verification method.
=> Crypto: adjust ErrKeyNotFound to clearly indicate it concerns private keys

network/network_integration_test.go, network/transport/v2/handlers.go, network/transport/v2/handlers_test.go
reflects latest protocol update, see https://github.com/nuts-foundation/nuts-specification/pull/189
If the Gossip does not result in the same XOR as its peer, the node now always makes an attempt at resolving their differences.
=> Network: Send State when peer is behind and there are no new transactions

network/transport/v2/gossip/manager_test.go
Several tests directly access a `peerQueue` without a lock. This can coincide with the Gossip manager trying to send Gossip messages and cause a data race.
Only 1 test actually depended on the gossip interval, so test duration is not increased.
=> Gossip: Reduce chance of test data race

echo/echo_integration_test.go, network/dag/interface.go, network/dag/mock.go, network/dag/publisher.go, network/dag/state.go, network/dag/state_test.go, network/network.go, network/network_integration_test.go, network/transport/v2/protocol.go, network/transport/v2/protocol_test.go
fixes #1116 
it basically simulates 2 separate notifications: 1 for the TX and 1 for the payload. But when receiving the payload notification you'll want the TX as well.
Now the notifications are equal again for creating and receiving nodes of private TXs
backport to V2
=> send notification from DAG with AND without payload

network/transport/connection_manager.go, network/transport/grpc/authenticator.go, network/transport/grpc/authenticator_test.go, network/transport/types.go
E.g.: no TLS, missing DID document, no SAN entries in TLS certificate
Currently, new nodes don't authenticate the node DID of their bootstrap nodes because initially, their DID document can't be resolved. After this fix, new nodes just accept the node DIDs of their bootstrap nodes, regardless their TLS certificate/DID documents. In the current situation, the node has to be restarted (or the connection re-established) to authenticate the peer.
=> Network: also override node DID auth when one of the prerequisites fail

network/dag/interface.go, network/dag/mock.go, network/dag/publisher.go, network/dag/state.go, network/dag/state_test.go, network/network.go, network/network_integration_test.go, network/transport/v2/protocol.go, network/transport/v2/protocol_test.go
fixes #1116 for V2 branch
backport of d3d9071d54e1add9f478dd70b7fc1749532d0105
* send notification from DAG with AND without payload
* separate observers for dag.STate
* add integration test for tree updates for priate tx
=> send notification from DAG with AND without payload (#1112)

network/dag/state.go, network/dag/state_test.go, network/dag/verifier.go, network/dag/verifier_test.go
fixed transaction dependency of TransactionVerifier, it now uses a bbolt.Tx instead of the context.
Another red block fixed:
=> remove dependency on context for transaction verifiers

docs/pages/getting-started/1-running-docker.rst
.datadir now matches with the mounted volumes in Docker
=> Docs: correct datadir

network/dag/mock.go, network/transport/v2/conversation.go, network/transport/v2/conversation_test.go, network/transport/v2/senders_test.go
During bursts of transactions it could happen that a node has the same xor as received in a State message. The node will ignore this State message resulting in the sender/peer having to wait for the conversation to timeout before it can start a new conversation with the node. This also blocked requesting new Tx received per gossip.
=> Network: make State message non-blocking

.github/workflows/e2e-tests.yaml
Together with https://github.com/nuts-foundation/nuts-go-e2e-test/pull/26 this removes earthly from the e2e tests
=> e2e tests without earthly

network/dag/bbolt_dag.go, network/dag/interface.go
According to the docs when making a backup `tx.Size()` is the way to get the exact number of bytes.
=> change dbsize stats

vcr/vcr.go
Migrate was still in place even after the network reset. This breaks VC searching as described in #1231.
=> VCR: remove Migrate

network/dag/bbolt_tree.go, network/dag/bbolt_tree_test.go, network/dag/state.go, network/dag/tree/tree.go, network/dag/tree/tree_test.go
access to trees is not managed properly and causes race conditions.
Currently the access is managed by a mutex in `state`, and on 1 mutex per `tree`. Replaced this with a mutex per `tree store`
=> Fix race condition in State trees

development/performance_analyzer/entrypoint.sh, development/performance_analyzer/node-exporter.conf
node-exporter should be restarted so it also works when a docker container is restarted
disabled metrics from node-exporter itself to reduce clutter
=> Restart node_exporter service

auth/services/irma/irmaconfig.go
Suggested change in irmago: https://github.com/privacybydesign/irmago/issues/232
=> Auth: log module name with IRMA log entries

docs/pages/deployment/monitoring.rst, network/dag/dag.go, network/dag/interface.go, network/dag/mock.go, network/dag/state.go, network/dag/state_test.go, network/network.go, network/network_test.go
closes #1287 
adds metric with name: `nuts_dag_transaction_count`
Count is incremented on state.Add()
=> add transaction count metric to prometheus output

auth/contract/verifier.go, auth/services/dummy/dummy.go, auth/services/irma/irmacontract.go, auth/services/irma/validator.go, auth/services/messages.go, auth/services/oauth/oauth.go, auth/services/oauth/oauth_test.go, auth/services/test.go, auth/services/uzi/validator.go
fixes #1286 
When result is set to INVALID (from within IRMA mostly), the reason is also filled.
=> add validation failure to auth token request output

core/echo.go, docs/pages/deployment/recommended-deployment.rst
Part of https://github.com/nuts-foundation/nuts-node/issues/40
I choose hardcoding the use of `X-Forwarded-For` because NGINX and HAProxy have support for it.
NGINX:
```
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```
HAProxy:
```
option forwardfor
```
Since you should always run (public/semi-public) HTTP endpoints with a reverse proxy in front, the Nuts Node should never be accessed directly by an external entity. So it's safe to just always assume `X-Forwarded-For` will contain the IP of the remote client (if it's not present it defaults to the IP-layer IP of the client).
And should this not uphold, IP addresses arenot used for authentication or granting access (e.g. allowlist), it is only logged. So no harm done.
=> Logging: configure X-Forwarded-For in Echo

core/echo.go, core/echo_test.go
When scraping them using Prometheus, this causes a lot of logged calls (just like calls to `/status`).
=> Logging: skip logging calls to HTTP metrics endpoints

core/echo.go, core/echo_test.go, docs/main.go
=> Ratelimiter: add paths that should also be rate limited

core/landingpage.html
The link to the production deployment documentation on the landingpage doesn't work. This should fix that.
=> Fix link to production deployment docs on landingpage

docs/_static/network/v1.yaml, network/api/v1/api.go, network/api/v1/api_test.go, network/api/v1/generated.go, network/dag/interface.go, network/dag/mock.go, network/dag/notifier.go, network/dag/notifier_mock.go, network/dag/notifier_test.go, network/dag/state.go, network/dag/state_test.go, network/interface.go, network/mock.go, network/network.go, network/network_integration_test.go, network/network_test.go, storage/bbolt_test.go
closes #1260
Doesn't currently add a Delete API.
=> expose notifier dlq to metrics/diagnostics/API

cmd/root.go, core/echo.go
Removes logging like:
```
⇨ http server started on [::]:80
⇨ https server started on [::]:1324
```
We already logged this kind of info ("Binding /n2n to :1323"), but improved this so it logs the default interface as well.
=> Echo: remove non-standard logging

network/transport/grpc/connection.go, network/transport/grpc/connection_manager.go, network/transport/grpc/connection_manager_test.go, network/transport/grpc/interface.go, network/transport/grpc/interface_mock.go, network/transport/grpc/stats.go, network/transport/grpc/stats_test.go, network/transport/grpc/testprotocol_impl.pb.go, network/transport/v2/protocol.go, network/transport/v2/protocol_test.go
Closes of https://github.com/nuts-foundation/nuts-node/issues/539
Example output:
```
nuts_network_grpc_messages_received{message_type="DiagnosticsBroadcast",protocol="v2"} 2
nuts_network_grpc_messages_received{message_type="Gossip",protocol="v2"} 31
nuts_network_grpc_messages_received{message_type="State",protocol="v2"} 1
nuts_network_grpc_messages_received{message_type="TransactionList",protocol="v2"} 1
nuts_network_grpc_messages_received{message_type="TransactionListQuery",protocol="v2"} 1
nuts_network_grpc_messages_received{message_type="TransactionPayload",protocol="v2"} 1
nuts_network_grpc_messages_received{message_type="TransactionPayloadQuery",protocol="v2"} 1
nuts_network_grpc_messages_received{message_type="TransactionSet",protocol="v2"} 1 …
```
=> Network: add Prometheus metrics for sent/received messages and peer count

network/network.go, network/network_test.go
Peer diagnostics collector is called periodically by v2 which reads it, while there might be a Shutdown call in-flight which sets the field to `nil`, causing a nil deref. Now it can still fail because the databases are closed (which is OK, because the node is shutting down anyways), but at least it's not a nil deref due to a data race.
Most correct fix would wait for the protocols  (v2) and its child goroutines (diagnostics collector) to finish, but that would require a lot more code, increasing complexity.
=> Fix datarace on network.state by not nil-ing it on shutdown

go.mod, go.sum
fixes #1405
go-leia has a fix where the search cursor wasn't advanced when there was a mismatch on the leaf of the search tree.
The fix advances the cursor and continues the search.
=> fix searching on empty string

network/dag/signing.go
fixes #1408 
old transactions still have it in their crit header. No logic has changed so nothing will break.
=> Network: Remove jwk/kid from crit header

docs/pages/deployment/tls-configuration.rst
A single proxy config should only contain `listen`, or a combination of `frontend` and `backend`
=> Docs: Updated HAProxy pass-through config

network/network_integration_test.go, network/transport/grpc/authenticator.go, network/transport/grpc/connection_manager.go, network/transport/grpc/ip_interceptor.go, network/transport/grpc/ip_interceptor_test.go, network/transport/grpc/tls_offloading.go, network/transport/grpc/tls_offloading_test.go
closes #1389
Behavior matches that of the echo handler
Will still produce IP of the proxy when configured for level 4 forwarding
=> gRPC sets ip based on X-Forwarded-For header if available

docs/pages/getting-started/3-configure-your-node.rst, network/network.go, network/network_test.go, network/transport/types.go, network/transport/types_test.go
closes #1385
Service discovery no longer accepts NutsComm endpoints that consist of reserved TLD's / addresses, or IP addresses.
Behavior of bootstrap nodes is unchanged.
- (How) Should this be documented?
=> Network: validate discovered NutsComm address

network/network.go
currently logs the node's own DID
=> Network: log peer's DID on NutsComm discovery

auth/auth.go
current message in logs:
`time="2022-09-13T15:18:54Z" level=error msg="missing publicUrl"`
=> Auth: improve publicURL error message

docs/pages/deployment/monitoring.rst, go.mod, go.sum, vcr/issuer/interface.go, vcr/issuer/leia_store.go, vcr/issuer/leia_store_test.go, vcr/issuer/mock.go, vcr/vcr.go, vcr/vcr_test.go, vcr/verifier/interface.go, vcr/verifier/leia_store.go, vcr/verifier/leia_store_test.go, vcr/verifier/mock.go
Closes https://github.com/nuts-foundation/nuts-node/issues/1432
E.g.:
```yaml
vcr:
credential_count: 7
issuer:
issued_credentials_count: 0
revoked_credentials_count: 0
verifier:
revocations_count: 18
```
=> VCR: Add stats on credentials in store

crypto/storage/vault.go, crypto/storage/vault_test.go
Reuse the getValue logic which handles errors correct. Fix mock to mimic vault implementation behaviour.
=> Fix vault memory error

crypto/api/v1/api.go, crypto/api/v1/api_test.go, crypto/api/v1/generated.go, crypto/api/v1/generated_test.go, crypto/interface.go, crypto/jwx.go, crypto/jwx_test.go, crypto/mock.go, docs/_static/crypto/v1.yaml
In KIK-V (and maybe HTI) we use  JSON web messages (JWM) messages to exchange information between services. Plain JWM messages can be  wrapped in JWS and JWE envelopes to ensure their origin with a signature (JWS) and be confidential by encrypting the message (JWE). 
In order to support JWM messages we need to encrypt(sign(plain)) these messages with NUTS. To our view, the JWE can be realized fairly easy by align to the sign_jwt method with a similar sign_jws method, with the following differences:
- The payload is not a set of claims, but a byte array, as the payload can be anything.
- The detached boolean is added to allow for detached JWS objects, that are objects _about_ a payload, which do not include the body. A use case can be a signed http request. 
Special attention needs to go …
=> JSON web messages part 1

vcr/issuer/issuer.go, vcr/issuer/issuer_test.go
This is a small fix to prevent duplicate VC context when set within the POST body
=> only add default VC context when missing

auth/auth.go, auth/services/contract/notary.go, auth/services/irma/irmaconfig.go, auth/services/irma/validator.go
Add `production` var to IRMA config and let it follow the strict-mode setting.
=> Set IRMA to production-mode on strict-mode installs (#1491)

core/config.go, core/config_test.go, docs/pages/deployment/configuration.rst, docs/pages/deployment/storage-configuration.rst, go.sum, storage/engine.go, storage/redis.go, storage/redis_test.go
This PR will add Redis Sentinel support.
Sentinel support is enabled when storage detects a Redis URL with sentinelMasterName as query parameter (see docs).
If Redis URL is configured through environment variables or commandline flags, commas separating sentinel hosts need to be escaped, otherwise the value is splitted into a []string. You can now prefix commas with a backslash to avoid splitting.
TODO:
No additional tests will be performed for now, test manually and add a more elaborate setup in end-to-end tests later.
Fixes https://github.com/nuts-foundation/nuts-node/issues/1369
=> Storage: support Redis Sentinel

vcr/store.go, vcr/store_test.go
fixes #1512
less strict validation on VC type introduced a panic. Extra painful is that it was only used for logging.
=> fix panic when VCs do not have a custom type

docs/pages/getting-started/6-adding-authorizations.rst
noticed when explaining search to a hackathon visitor
=> fix incorrect credential type in VC search example

network/network.go, network/network_integration_test.go, network/transport/grpc/connection_manager_test.go, storage/test.go, vdr/integration_test.go, vdr/store/store_test.go
closes #1219 
network/vdr integration test use bbolt store without syncing
test speedup:
network 26s -> 9s
vdr 5s -> 0.7s
=> Speedup integration tests

vcr/assets/assets/contexts/nuts-v2.ldjson
Found while testing VC field validation (https://github.com/nuts-foundation/nuts-node/pull/1190)
=> VCR: Fix Nuts v2 JSON-LD context, evidence missing @id

docs/_static/vcr/v2.yaml
removes the `>` character. With this character the example is text, now it is JSON.
=> Fix vcr api example requests

auth/api/v1/api_test.go, auth/services/oauth/oauth.go, auth/services/oauth/oauth_test.go, docs/pages/release_notes.rst, vcr/credential/resolver.go, vcr/credential/resolver_test.go, vcr/credential/test.go, vcr/credential/types.go, vcr/credential/validator.go, vcr/credential/validator_test.go, vcr/issuer/issuer.go, vcr/issuer/issuer_test.go, vcr/search.go, vcr/verifier/verifier.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/1032
TODO:
=> VCR: Validate that VCs only contain fields that are defined by JSON-LD context

docs/pages/getting-started/6-adding-authorizations.rst
Since it isn't allowed anymore for JSON-LD Nuts context v1
Also backport to v4 and v5
=> Docs: remove LegalBase from examples

network/dag/interface.go, network/dag/mock.go, network/dag/state.go, network/dag/state_test.go, network/network_integration_test.go, network/transport/v2/handlers.go, network/transport/v2/handlers_test.go, network/transport/v2/protocol.go, network/transport/v2/protocol_test.go, network/transport/v2/transactionlist_handler.go, network/transport/v2/transactionlist_handler_test.go
XOR and IBLT are cached in memory, but every request for an IBLT/XOR still required an DB call for the highest LC.
=> Network: add highest LC to cached state

network/dag/tree/tree.go, network/dag/tree/tree_test.go
Changed the way how trees are built after loading from disk. See #1509 for some benchmarks.
=> State: build tree bottom up

network/dag/notifier_test.go, network/dag/state.go, network/dag/state_test.go
* locks held while invoking listener methods
* missing atomic access on Prometheus mock
* dedicaded atomic type elimination
=> Eliminate mutex use in dag package

network/api/v1/api.go, network/api/v1/api_test.go, network/dag/dag.go, network/dag/dag_test.go, network/dag/interface.go, network/dag/payloadstore.go, network/dag/state.go, network/dag/verifier.go, network/interface.go, network/network.go, network/network_integration_test.go, network/network_test.go, network/transport/v2/handlers.go, network/transport/v2/handlers_test.go, network/transport/v2/protocol.go, network/transport/v2/protocol_test.go
closes #1543
`dag.getTransaction` and `dag.readPayload` now return `dag.ErrTransactionNotFound` and `dag.ErrPayloadNotFound` when the data is not found.
=> replace not found data nil with an ErrNotFound

docs/pages/release_notes.rst
Backport from v4 release.
Also noticed v4.2.0 was missing (present in v4), added as well.
=> v4.3.0: Release notes (backport)

auth/services/oauth/oauth.go, vcr/credential/resolver.go, vcr/credential/resolver_test.go, vcr/credential/validator.go, vcr/credential/validator_test.go, vcr/issuer/issuer.go, vcr/issuer/issuer_test.go, vcr/verifier/verifier.go
Checking whether all fields in a VC are defined in the given JSON-LD contexts should only happen when issuing a VC: protection against undefined fields (from VCs created by third parties) should be achieved by compacting it before returning it to the application/user.
TODO:
Part of https://github.com/nuts-foundation/nuts-node/issues/1564
=> VCR: Only check VC fields on issuance

crypto/hash/sha256.go, crypto/hash/sha256_test.go, crypto/hash/test.go, docs/generate_docs_test.go, network/dag/state_test.go, network/dag/tree/benchmark_test.go, network/dag/tree/iblt.go, network/dag/tree/iblt_test.go, network/dag/tree/tree.go, network/dag/tree/tree_test.go, network/dag/tree/xor.go, network/dag/tree/xor_test.go, network/dag/treestore.go
lessons learned from profiling in #1509
`Iblt.Unmarshal` can be made twice as fast by replacing the buckets slice with a bucket array of fixed length if needed. (useful if trees are reloaded from disk often)
=> Tree and Iblt optimizations

docs/pages/getting-started/6-adding-authorizations.rst
type is specced as string, not an array.
=> Docs: minor correction to issuing Auth credential

didman/api/v1/api.go, didman/api/v1/api_test.go, didman/types.go, vdr/doc/resolvers_test.go, vdr/doc/util.go, vdr/doc/util_test.go, vdr/types/common.go, vdr/types/common_test.go
Error type names should end with Error. The error strings each should classify the full context of what is already explicit in code. In this case, describe the error is about "DID Subjects" and "endpoint URIs".
Errors should live together with the code that encounters any of the respective cases. The package name becomes a descriptive part of the scenario. Package names like `types` or `core` must be killed with fire.
https://go.dev/doc/effective_go#names
Do not introduce functions for cases handled well in plain code, especially if such function has an odd structure like core.ResolveStatusCode does. The new `switch` is more readable, it requires no knowledge of the Nuts packages, and it provides a sane default [HTTP 500].
=> refactor types.ErrInvalidServiceQuery to doc.DIDServiceQueryError

Dockerfile
tests currently fail due to failing builds
=> Dockerfile: update musl-dev=1.2.3-r2

vcr/search.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/1628
=> VCR: SearchVCs now logs invalid VCs on debug to avoid log clutter

network/dag/state.go, network/dag/state_test.go
state.Add should fail when the event cannot be saved to guarantee notification of network subscribers
=> State: saveEvent should fail when Notifier.Save fails

go.mod, go.sum, vdr/doc/manipulator.go, vdr/doc/manipulator_test.go
fixes #1536
simple lib update and change in calling `doc.RemoveVerificationMethod`
=> update go-did to v0.4.0 and adjust usage accordingly

crl/validator.go, crl/validator_test.go
The CRL testdata expired on 15 november 2022.
This PR adds
* a `nowFunc` to `crl/validator` which can be overridden during testing to set it to a valid date.
* an extra test to check if a failing crl is actually resulting in an error.
=> Fix crl validator tests

cmd/root.go
This PR cleans up the output during startup when an error is encountered.
If the error is unrelated to the command options, the "usage" is not printed.
Reasoning:
* Finding the actual error is harder.
* Printing the usage info is confusing and condescending because it suggests the user made a mistake in the command.
Old output:
```
WARN[0000] Deprecated: use `tls.certkeyfile` instead of `network.certkeyfile` 
WARN[0000] Deprecated: use `tls.truststorefile` instead of `network.truststorefile` 
Error: no scheme file found
Usage:
nuts server [flags]
Flags:
--auth.clockskew int                            Allowed JWT Clock skew in milliseconds (default 5000)
--auth.contractvalidators strings               sets the different contract validators to use (default [irma,uzi,dummy]) …
```
=> Hide usage information on server error

network/transport/grpc/connection.go, network/transport/grpc/connection_manager.go, network/transport/grpc/connection_manager_test.go, network/transport/grpc/connection_mock.go, network/transport/grpc/connection_test.go, network/transport/grpc/test.go
fixes #1265 
store grpc error before closing connection, can then be used to increment backoff
currently backoff only increased for Code==16 (Unauthenticated)
=> Increment client backoff when server returned unauthenticated

.codeclimate.yml
Codeclimate seems unmaintained (at least for Go): https://github.com/codeclimate/codeclimate-golint/issues/28
`golint` is also deprecated: https://github.com/golang/lint
=> Disable codeclimate/golint since it breaks on generics

vcr/issuer/interface.go, vcr/issuer/issuer.go, vcr/issuer/issuer_test.go, vcr/issuer/leia_store.go, vcr/issuer/leia_store_test.go, vcr/types/constants.go
Returned HTTP 500 (unmapped error) because of ambiguous error types, issuer package just uses the commonly defined VCR errors (which are mapped in the API).
```shell
curl -X DELETE http://localhost:1323/internal/vcr/v2/issuer/vc/foo | jq
```
Now returns:
```json
{
"detail": "could not revoke (id=foo): credential not found",
"status": 404,
"title": "RevokeVC failed"
}
```
Closes https://github.com/nuts-foundation/nuts-node/issues/1635
=> VCR: Revoking unknown VC now returns HTTP 404

api/ssi_types.go, docs/_static/auth/v1.yaml, docs/_static/common/ssi_types.yaml, docs/_static/didman/v1.yaml, docs/_static/vcr/v2.yaml, docs/_static/vdr/v1.yaml, vcr/api/v2/generated.go
During past hackatons people keep getting confused about incorrect examples. Mostly about service ID which appears to be the service type in some examples, but which is actually the hash of the service.
This PR fixes examples containing DIDs (DIDs, verification method IDs and service IDs).
Partially fixes https://github.com/nuts-foundation/nuts-node/issues/1196
=> Docs: improve OpenAPI examples to reflect actual data

crypto/storage/fs.go, crypto/storage/fs_test.go
Fixes #1704 
File permissions to 0600 and don't create when already exists.
=> Fix crypto fs storage

network/transport/types.go, network/transport/types_test.go
The use of custom TLDs (`nodeA`) is not part of reserved addresses per https://www.ietf.org/archive/id/draft-chapin-rfc2606bis-00.html. This restriction complicates our testing strategy. 
Allowing non reserved TLDs does not pose a security risk since they probably do not resolve to anything, but if they do, authentication will fail on production networks since you cannot add these addresses to a PKIo certificate.
=> NutsComm: allow custom TLD

Dockerfile
docker builds of V5 branch stil fail without this
=> remove gcc and musl-dev deps (backport #1651)

go.mod, go.sum, network/dag/dag.go, network/dag/notifier.go, network/dag/notifier_test.go, network/dag/payloadstore.go, network/dag/payloadstore_test.go, network/dag/treestore.go, vcr/issuer/leia_store.go, vdr/store/store.go
New version of stoabs no longer returns an error on GetShelfWriter. This eliminates a lot of error checks
=> update to stoabs v1.5.1

crypto/crypto.go, crypto/crypto_test.go
Firstly, key IDs are unique in practice, since they are derived from the public key. Secondly, it's unsafe:
- An attacker who is allowed to (although currently not possible) specify his own key ID, could overwrite existing keys (potential data loss)
- It allows to accidentally overwrite a private key (potential data loss)
- Leaving it up to the storage implementation leads to unpredictable behavior
=> Crypto: do not overwrite private keys when generating new one

charts/nuts-node/Chart.yaml, charts/nuts-node/templates/deployment.yaml, charts/nuts-node/templates/nuts-data-pv.yaml, charts/nuts-node/values.yaml
- Make PV and PVC controllable by values.yaml, GKE does not need a VPC. Config for PV and VPC are split up.
- Added storageClassName to PV and PVC configuration, GKE needs it.
- Deployment, added startupProbe as the downloading and writing of the IRMA schema on the PV cause container creation timeouts.
=> Helm Fixes for GKE deployment

docs/_static/common/ssi_types.yaml
Without it, OpenAPI Generator Tools for Java doesn't recognize it as a YAML OpenAPI file.
=> Mark ssi_types.yaml as OpenAPI file

vcr/api/v2/registry.go
Replaces #1230 
The following query:
```
{
"query": {
"@context": [
"https://www.w3.org/2018/credentials/v1",
"https://nuts.nl/credentials/v1"
],
"type": [
"VerifiableCredential",
"NutsOrganizationCredential"
],
"credentialSubject": {
"organization": {
"name": "Zorggroep de Nootjes",
"city": "Amandelmere"
}
}
}
}
```
Log the following output:
```
DEBU[0003] [
{
"@type": [
"https://www.w3.org/2018/credentials#VerifiableCredential",
"https://nuts.nl/credentials/v1#NutsOrganizationCredential"
],
"https://www.w3.org/2018/credentials#credentialSubject": [
{
"http://schema.org/organization": [
{
"http://schema.org/city": [
{
"@value": "Amandelmere"
}
],
"http://schema.org/legalname": [
{
"@value": "Zorggroep de Nootjes"
}
]
}
]
}
]
}
]  module=VCR
INFO[0003] HTTP request …
```
=> VCR: Add debug log of expanded json-ld VCR search query

crypto/storage/vault_test.go, didman/api/v1/client_test.go, docs/_static/network/v1.yaml, docs/pages/deployment/cli-reference.rst, network/api/v1/api.go, network/api/v1/api_test.go, network/api/v1/client.go, network/api/v1/client_test.go, network/api/v1/generated.go, network/cmd/cmd.go, network/cmd/cmd_test.go
A ranged operation for ListTransactions was always intended and is implemented via this PR. The query string now accepts an optional ?start=N&end=M pattern. Following convention of the surrounding code the start parameter is inclusive and the end parameter is exclusive. These parameters restrict the lamport clock values of the returned transactions. This feature is needed to implement a scalable data viewer client.
=> implement ranged ListTransactions (?start=N&end=M)

auth/services/contract/notary.go, auth/services/oauth/oauth.go, didman/didman.go, jsonld/reader.go, vcr/api/v2/registry_test.go, vcr/context_test.go
Requires https://github.com/nuts-foundation/nuts-node/pull/1677, since otherwise any undefined property is imported into the Nuts context due to `@vocab`.
=> VCR: Validate SearchVCs input

auth/api/v1/api.go, auth/api/v1/api_test.go, docs/_static/auth/v1.yaml
Partially fixes #1527 
- More clearly indicates that the error is returned by the remote Nuts node
- Stop returning the received response code as the local API call's response code, a downstream error should have a specific status code, not influenced by the downstream system being called. Otherwise, you never know which status code is going to be returned, which can even be a vulnerability.
=> Auth: clearly distinguish errors returned by remote nodes

auth/api/v1/api_test.go, auth/api/v1/client.go, auth/api/v1/client_test.go, cmd/root.go, cmd/root_test.go, core/http_client.go, core/http_client_test.go, didman/api/v1/client_test.go, vdr/api/v1/client_test.go, vdr/cmd/cmd_test.go
Since the server may return anything (e.g., binary response, or a very large blob), it's unsafe to include it in the error message: it gets logged and sometimes returned to the client.
Better to record it in the error struct, but not to include it in the error message.
Since it's still useful to print when a CLI command fails (due to non-OK server response), introduced a wrapper for all client commands.
=> Core: remove server response body HTTP client errors

crypto/crypto.go, crypto/crypto_test.go, crypto/decryptor.go, crypto/jwx.go, crypto/storage/fs.go, crypto/storage/wrapper.go, crypto/storage/wrapper_test.go, jsonld/testsuite/compat_test.go
Fixes: NTS-007 #1723
Adds a wrapper for storage engines. For each function that accepts a kid param, the param gets validated for a provided kidPattern. This allows for multiple kid patterns in the future.
CodeScanning fails because we use a var in a path, which is true if you don't wrap the FS backend. So, perhaps someone can double check if this can be marked as invalid?
=> Crypto: Add KID check wrapper for crypto storage backends

didman/didman_test.go, vdr/ambassador.go, vdr/didservice/resolvers.go, vdr/validators.go, vdr/validators_test.go, vdr/vdr.go
part of #1508 
This splits did doc validators in `NetworkDocumentValidator` that validates documents received through the network, and `ManagedDocumentValidator` that provides stricter validation on did documents managed by a node before they are published. 
The latter has an additional validator: `managedServiceValidator` provides addition validation on services before publication. All services are validated on every did document update. _Could this be an issue with something like automated key rotation if a service reference is no longer valid?_
remaining after this PR is finished
- go through APIs and didman to validate the new did doc before it is updated/published
- remove checks in the above that are now redundant
- move ServiceResolver interface to vdr/types with the rest
=> VDR: Add ManagedDocumentValidator and managedServiceValidator

docs/pages/release_notes.rst
These notes are currently only on the V5 branch
=> Docs: add release notes of v5.0.4 and v5.0.5 to master

network/dag/state.go, network/dag/state_test.go
Useful for `data-viewer` to it can skip to the last page/transaction.
=> Network: add highest LC to diagnostics

.github/workflows/build-images.yaml
Fixes https://github.com/nuts-foundation/nuts-node/issues/1733
See https://github.com/marketplace/actions/docker-metadata-action
`latest` tag should be handled correctly by default (semver): https://github.com/marketplace/actions/docker-metadata-action#latest-tag
Not sure how to test this without creating a release...?
=> Build: migrate to GitHub Docker Actions

auth/services/oauth/oauth.go, didman/types.go, network/network.go, network/network_test.go, network/transport/types.go, network/transport/types_test.go, vcr/issuer/network_publisher.go, vcr/issuer/network_publisher_test.go, vdr/validators.go
This PR introduces a NutsCommURL type which is a string.
This type validates itself during unmarshalling. Makes everything a bit more consistent.
=> Improve consistancy of NutsComm Endpoint validation

go.mod, go.sum, network/dag/dag.go, network/dag/notifier.go, network/dag/notifier_test.go, network/dag/payloadstore.go, network/transport/grpc/backoff.go, network/transport/v2/protocol_test.go, storage/bbolt_test.go, storage/redis_test.go, vdr/store/store.go
Implements changes in https://github.com/nuts-foundation/go-stoabs/pull/41
Prevents some potential nil dereferencing in cases where `data, err := staobs.Reader.Get()` returns double nil
=> Storage: handle ErrKeyNotFound returned by stoabs.Reader.Get

didman/api/v1/api.go, didman/api/v1/api_test.go, didman/didman.go, didman/didman_test.go, vdr/validators.go
validation now takes place in vdr.Update
invalid service error was previously incorrectly mapped to 406, is the specced 400 now
=> Didman: remove redundant compound service validation

network/transport/v2/gossip/queue_test.go
CI sometimes fails because done2's value is evaluated before the toggling goroutine is scheduled
=> Test: fix timing issue in test

docs/pages/deployment/backup-restore.rst
closes #1790 
I can't find any other reference to the non-existing sub-path. Followed the steps and was able to restore a backup using the guide.
=> Remove storage.database sub-path from backup&restore docs

core/metrics.go, core/metrics_test.go, docs/pages/deployment/monitoring.rst, go.mod, go.sum
Fixes NTS-009: #1716
First solution was limiting the logged http path to 200 chars.
After discussion in the comments, I changed the solution to removing http metrics logging completely.
There is still a mention of a `http_` prefix in the docs, but I think this won't hurt or confuse the reader.
=> Core: Remove prometheus metrics for http requests

auth/auth.go, auth/auth_test.go, auth/cmd/cmd.go, auth/cmd/cmd_test.go, auth/config.go
fixes #1845
config was always set to default
=> migrate irma auth config to current format

core/logging.go, network/network.go, network/transport/grpc/authenticator.go, network/transport/grpc/authenticator_test.go, network/transport/grpc/connection.go, network/transport/grpc/connection_mock.go, network/transport/grpc/predicate.go, network/transport/grpc/predicate_test.go, network/transport/grpc/test.go, network/transport/types.go, network/transport/types_test.go, network/transport/v2/handlers.go, network/transport/v2/handlers_test.go, network/transport/v2/protocol.go, network/transport/v2/protocol_test.go
This adds Peer.Authenticated to signal if a stream is authenticated or not.
closes #1664, and is part of a ongoing refactor on the connection manager (peer is not the right place for this flag)
`/status/diagnostics` currently has a `acceptunauthenticated: true/false` should this be replaced with the actual `Authenticated` value?
=> Network: add authenticated plag to peer

network/transport/grpc/interface.go
Removed in #1840, but needed for mocks.
=> Fix grpc mocks

vdr/ambassador.go, vdr/ambassador_test.go
fixes #1754 
This correctly resolves the latest DID Document. This was already done for the controllers...
+backport to V5.0
=> resolve previous document based on tx prev hash in VDR update

core/config_test.go, core/http_client.go, core/http_client_test.go, didman/api/v1/client.go, network/api/v1/client.go, vcr/api/v2/client.go, vdr/api/v1/client.go
closes #1891 
Using the client API lib for our APIs involved creating a `api.HTTPClient` for various packages and then calling its methods. It was not possible to inject an alternative TokenBuilder in this process. Especially the registry admin benefits from this since it needs to inject its own token builder.
the registry creates clients like:
```
vdrClient := vdrAPI.HTTPClient{
ServerAddress: config.NutsNodeAddress,
Timeout:       apiTimeout,
}
```
This PR allows for adding an AuthorizationTokenBuilder impl
note: fixed `data` dir creation from `config_test.go`
=> allow for custom AuthorizationTokenBuilder on API Client

audit/audit.go, audit/audit_test.go, audit/test.go, crypto/crypto.go, crypto/crypto_test.go, crypto/log/logger.go, docs/pages/deployment/audit-logging.rst
Needs some more test coverage, but first review round to see if it's not too hacky.
It creates a new logger, specifically for auditing. At first use, it copies the Formatter from the standard logger and decorates it with a Formatter that alters the log level using byte comparison. The order of default fields is hardcoded, so it only replaces the first occurence.
Fixes #1888
Text output:
```
time="2023-02-13T15:52:47+01:00" level=audit msg="Generating new key pair: kid" actor=test-actor event=CreateNewKey module=Crypto operation=TestModule.TestOperation
```
Colored text output:
```
AUDIT[0000] Generating new key pair: kid                  actor=test-actor event=CreateNewKey module=Crypto operation=TestModule.TestOperation
```
JSON output:
``` …
```
=> Audit: log events on custom 'audit' log level

network/network.go
changes relevant part of log line from: `nodeAddr="{{grpc   nuts.nl:5555   false false   }}"` to `nodeAddr=nuts.nl:5555`
=> Fix address logging in service discovery

auth/services/oauth/oauth_test.go, docs/pages/release_notes.rst, vcr/credential/revocation.go, vcr/credential/revocation_test.go, vcr/credential/test.go, vcr/issuer/issuer.go, vcr/issuer/issuer_test.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/1911
Also needs to be applied to master branch.
=> VCR: Don't check VC existence when revoking

network/transport/grpc/connection_manager.go, network/transport/grpc/connection_manager_test.go
closes #1925
Also changed the log level from Warn to Info when the node fails to connect a stream after having successfully setting up a gRPC connection.
=> Network: reduce backoff when connected to unexpected DID

network/transport/types.go
To match casing in YAML.
Fixes https://github.com/nuts-foundation/nuts-node/issues/1941
=> Network: consistent casing for diagnostics in JSON 

docs/pages/deployment/production-configuration.rst, http/engine.go
- Consistency in FS path; `/opt/nuts`
- Code blocks instead of inline code for long strings
- Broken link formatting
- Typo
=> Docs: tweaks in API auth documentation

network/transport/grpc/authenticator.go, network/transport/grpc/authenticator_test.go
It's already logged as `did` log field, no need to include it in the error message. It makes the log message unnecessarily harder to read:
```
time="2023-03-13T16:39:19+01:00" level=warning msg="Peer node DID could not be authenticated" did="did:nuts:EGPFSJaUuN1RBRReCvWBFzetpzZKTRJBtGg67jMi3uKF" error="none of the DNS names in the peer's TLS certificate match the NutsComm endpoint (nodeDID=did:nuts:EGPFSJaUuN1RBRReCvWBFzetpzZKTRJBtGg67jMi3uKF)" module=Network peerAddr="172.20.0.13:35724" peerAuthenticated=false peerDID= peerID=0b85e051-c01f-4b4e-8375-b1c95f46b380
```
=> Network: remove DID from auth errors, since it's logged by the caller

codegen/configs/vdr_v1.yaml, docs/_static/vdr/v1.yaml, docs/pages/release_notes.rst, vdr/api/v1/api.go, vdr/api/v1/api_test.go, vdr/api/v1/generated.go, vdr/api/v1/types.go
This also changes the response content-type of `application/json+did-document` to `application/json`. The code generator doesn't play nice with specialized JSON types (it will treat it as a binary/stream type), and I think the same will applies to other JSON unmarshallers as well (needing extra mapping for the content type). So why not make everyone's life easier and just return `application/json`. It's just JSON, after all.
=> VDR: Strict OpenAPI interfaces

vcr/api/v2/api.go, vcr/api/v2/api_test.go, vcr/issuer/interface.go, vcr/issuer/issuer.go, vcr/issuer/leia_store.go, vcr/issuer/leia_store_test.go, vcr/issuer/mock.go
fixes #1910 
The problem was that the query part for the JSON-LD context did an equal to `""`.
Changed it to only include that query part if the context is actually non-empty.
Requiring the `@context` to be non-nil for VCs is overkill since every VC will have a JSON-LD context.
=> fix finding issued credentials

docs/pages/integrating/api-authentication.rst
Add super important whitespace
=> Fix non-visible commands in documentation

vcr/issuer/leia_store.go, vcr/issuer/leia_store_test.go
fixes #1909 
Indices had to be created first.
Added test shows that existing data is now correctly detected and no loading of the backup is done.
=> fix correct loading order of data in issuer store

auth/services/x509/x509_validator.go, auth/services/x509/x509_validator_test.go, crl/mock.go, crl/validator.go, crl/validator_test.go
It currently only shows `CRL database is outdated, certificate revocation can't be checked`, this enriches this with the reason and URL of the CRL that caused the error.
=> x509: show offending URL in CRL validator sync errors

auth/services/x509/x509_validator.go, auth/services/x509/x509_validator_test.go, crl/mock.go, crl/validator.go, crl/validator_test.go
Backport of https://github.com/nuts-foundation/nuts-node/pull/2008 to v5.1
=> x509: show offending URL in CRL validator sync errors (#2008)

core/engine.go, core/engine_test.go, crypto/cmd/cmd.go, crypto/crypto.go
After upgrading from v5.1.0-rc1 to v5.1.0 I got the error: "Failed to start server" (err = invalid url: empty), without further context to find out what was configured incorrectly. Turned out `crypto.external.address` was unset (because it was renamed from `.url`).
Added error wrapping for external crypto client setup and module lifecycle errors, to help pinpointing which module causes the error.
=> Core: originate errors from modules in system lifecycle

core/engine.go, core/engine_test.go, crypto/cmd/cmd.go, crypto/crypto.go
Backport of https://github.com/nuts-foundation/nuts-node/pull/2012
=> Core: originate errors from modules in system lifecycle (#2007)

network/transport/types.go, network/transport/v2/conversation.go, network/transport/v2/conversation_test.go, network/transport/v2/handlers_test.go, network/transport/v2/senders.go, network/transport/v2/senders_test.go, network/transport/v2/transactionlist_handler_test.go
fixes #1950 
replaced peerID in conversation map with `Peer.String()`.
=> use transport.Peer in conversation instead of PeerID

auth/auth.go, auth/services/x509/uzi_validator.go, crl/validator.go, crl/validator_test.go, network/network.go, network/network_test.go, network/transport/grpc/config.go, network/transport/grpc/config_test.go, network/transport/grpc/connection_manager.go, network/transport/grpc/connection_manager_test.go, network/transport/v2/protocol_integration_test.go
The new CRL validator introduced possible panics during startup. This PR introduces the changes to the connection manager to prevent that.
I'm not sure if the error cases are sufficiently tested
=> Network: grpcConnectionManager construction can return errors to prevent panics

README.rst, docs/pages/deployment/configuration.rst
`network.auth` -> `network.auth_config`
value was changed during review, forgot to update the documentation.
=> Docs: fix typo in configuration.rst

docs/pages/release_notes.rst
5.2 was tagged on a commit before the introduction of this feature
=> Docs: move tls.crl.maxvaliditydays release note to 5.3.0

pki/logger.go, pki/validator.go, pki/validator_test.go
closes #2086 
currently defaults to soft-fail, hard-fail will be configurable when its an engine
=> PKI: softfail when crl or denylist is missing or outdated

vcr/issuer/network_publisher.go, vcr/issuer/network_publisher_test.go
Removing these constants since they are both also declared in types
mainly needs to be removed to prevent accidental usage since
`RevocationDocumentTye =  "application/vc+json;type=revocation"` is unused but very similar to 
`RevocationLDDocumentType = "application/ld+json;type=revocation"` from types
=> VCR: remove duplicate and conflicting constants

network/network.go
The Reprocess API call runs async and there is currently no way to tell if it has finished.
Should this be back ported to other 5.x releases so it is added iff we release any future patches on those versions?
=> Network: add log message when Reprocess has completed

vcr/types/constants.go, vcr/vcr_test.go, vcr/verifier/verifier.go, vcr/verifier/verifier_test.go
Earlier, they had the same errors message, which is confusing.
=> VCR: Distinguish VP/VC not valid at given time errors

didman/didman.go, didman/didman_test.go
By only logging VC/DID document processing errors.
Otherwise, if a party issues one of the invalid VC cases below (no subject ID, no subject at all, invalid subject ID) `SearchOrganizations` returns nothing, effectively breaking the functionality.
Fixes https://github.com/nuts-foundation/nuts-node/issues/2115
Needs backporting to v5.2
=> Didman: make organization search more robust

.readthedocs.yaml
Our read the docs builds have been failing since last week. This is caused by a dependency update, but since we do not fix all dependencies it's not obvious which one caused it. 
The dep update no longer accepts the outdated version of (open)ssl that is apparently used by default in the build environment. The simplest fix appears to be forcing RTD to use a newer version of python (now uses 3.7, version 3.10+ require the supported version of openssl) which is easily managed by this default config.
I've added a hidden page to RTD to test if this works
https://nuts-node.readthedocs.io/en/docs-readthedocs-yaml/
=> Docs: add .readthedocs.yaml to fix failing build

didman/api/v1/api.go, didman/api/v1/api_test.go, didman/api/v1/generated.go, didman/didman.go, didman/didman_test.go, didman/mock.go, didman/types.go, docs/_static/didman/v1.yaml
Given https://github.com/nuts-foundation/nuts-node/issues/2131, it becomes very unpractical to update an absolute endpoint (service with a URL) when it's referenced by other services: it would mean parties have to:
1. delete all references first,
2. then delete the service itself,
3. then create the service with the updated endpoint,
4. finally recreate all references.
That it didn't hurt much up until now is because the "is being referenced"-check was always broken (at least for references from other documents), but it still applies to for references within the same document.
Furthermore, each hackaton people are asking how to update a service so having an API for that really helps.
=> Didman: added UpdateEndpoint and UpdateCompoundService

core/engine.go, core/engine_test.go
removed `Diagnostics()` from `System`, wasn't used.
=> removed dead diagnostics code

docs/pages/release_notes.rst
Release notes for v5.1.1 which fixes #2140
After merge, I'll release and update release notes for v5.2.
After that master.
=> Release notes for V5.1.1

auth/services/irma/factory_test.go
In the latest patch they fixed a case we use for testing error conditions.
So we're no longer able to test it that way.
Also logic behinds it does a mkdirall and fail conditions only check if dirs exist.....
=> irma config no longer generates errors

vcr/oidc4vci/issuer_client.go, vcr/oidc4vci/issuer_client_test.go, vcr/oidc4vci/wallet_client.go
To avoid connecting to the wrong Authz server by accident.
There's no client_id as of right now, so no way to check it.
Fixes https://github.com/nuts-foundation/nuts-node/issues/2033
=> OpenID4VCI: Verify identifiers in resolved metadata

auth/services/oauth/authz_server.go, auth/services/oauth/authz_server_test.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/2174
Maybe add in e2e test as well?
=> Auth: add missing selfsigned fields userRole and username to Access token

vcr/credential/types.go
should have been optional, otherwise you get an empty value and the test data is no longer valid.
=> make assuranceLevel optional

network/transport/v2/conversation.go
This should cause memory leaks everywhere.
=> the conversation manager used a timer in its cleanup routine

vdr/didservice/resolvers.go, vdr/didservice/resolvers_test.go
A range loop reuses the memory address of the variable. Therefore the last key from the list will be 'found' even if the `if` doesn't match.
Backport to V5.2
=> fix key resolving when multiple keys exist

pki/denylist.go, pki/denylist_test.go
This change makes configuring the denylist a lot simpler
=> Allow literal \n in trustedsigner

network/transport/grpc/predicate.go, network/transport/v2/gossip/manager.go, network/transport/v2/gossip/manager_test.go, network/transport/v2/gossip/mock.go, network/transport/v2/handlers.go, network/transport/v2/handlers_test.go, network/transport/v2/protocol.go
fixes #1950 
2nd part of phasing out peerID
=> gossip manager now uses Peer.Key instead of peerId

network/network.go, network/network_test.go, network/transport/grpc/config.go, network/transport/grpc/config_test.go
this health check is performed on both `network.tls` where it uses the configured certificate, and `network.auth_config` where it validates the received certificate as part of the self-connect check.
```
{
"details": {
"crypto.filesystem": {
"status": "UP"
},
"network.auth_config": {
"details": "cannot connect to own NutsComm grpc://nuts-dev.snaauw.com:5555: certificate is banned: gerard can tell you: subject=CN=nuts-dev.snaauw.com, S/N=14349442077069222814, issuer=CN=Nuts Development Network Root CA",
"status": "UNKNOWN"
},
"network.tls": {
"details": "certificate is banned: gerard can tell you: subject=CN=nuts-dev.snaauw.com, S/N=14349442077069222814, issuer=CN=Nuts Development Network Root CA",
"status": "DOWN"
},
"pki.crl": {
"status": "UP"
}
},
"status": "DOWN"
}
```
test denylist is …
=> Network: add revoked/denied cert to health check

docs/pages/deployment/tls-configuration.rst
The current documentation gives the assumption TLS doesn't need to be offloaded, which might technically be true, but doesn't work in practice (because `public` and `n2n`/gRPC require different certificates).
Clarified this, made TLS offloading the first option in the document and fixed some configuration errors.
=> Docs: clarified that no TLS offloading isn't really an option (in most cases)

.circleci/config.yml, .circleci/earthly-config.yml
#2202 needs go version 1.20, and testing using earthly has been removed last year
=> Update circleci config

network/transport/grpc/connection_manager.go, network/transport/grpc/tls_offloading.go, network/transport/grpc/tls_offloading_test.go
Offloaded connections are not validated (revoked/denied) by any `tls.Config`. This change ensures that the denylist is applied to the GRPC connections.
=> Network: validate certificate in interceptor

vdr/integration_test.go
Otherwise it always fails on my machine
=> Increase time-out to improve integration test stability

didman/didman.go, didman/didman_test.go, vdr/didstore/store.go, vdr/integration_test.go, vdr/vdr.go, vdr/vdr_test.go
Fix #2131.
This is WIP, needs tests and cleanup.
Given a service with id `did:nuts:123#abc` of type `oauth`.
During a DIDMan `deleteService` call it is checked if the service is in use.
Instead of the following reference format: `did:nuts:123/serviceEndpoint?type=oauth`
The following was used `did:nuts:123#abc` in the check.
Which always returned false
Then DIDMan removes the service from the DID Document and tries to update the DID Document.
Then the Updater performs a validation step on the DID Document which fails because there is a compound service with a reference to a service that does not exists.
=> Fix service deletion

docs/_static/network/v1.yaml, network/api/v1/api.go, network/api/v1/api_test.go, network/api/v1/generated.go, network/transport/grpc/addressbook.go, network/transport/grpc/addressbook_test.go, network/transport/grpc/connection_manager.go, network/transport/grpc/connection_manager_test.go, network/transport/types.go
closes #1929 
It'll now show the next connection attempt and the last error.
The next connection attempt is: previous + backoffValue
=> Added last error and next connection attempt to addressbook stats

network/network_integration_test.go, network/network_test.go, network/transport/grpc/authenticator.go, network/transport/grpc/authenticator_test.go, network/transport/grpc/connection.go, network/transport/grpc/connection_manager.go, network/transport/grpc/connection_manager_test.go, network/transport/grpc/connection_mock.go, network/transport/grpc/connection_test.go, network/transport/grpc/stats.go, network/transport/grpc/test.go, network/transport/grpc/tls_offloading.go, network/transport/types.go, pki/denylist.go, pki/denylist_test.go, pki/interface.go, pki/mock.go, pki/test.go, pki/validator.go, pki/validator_test.go
closes #2018  alternative solution to #2235 
DenyList.Subscribers get pinged when the Denylist is updated (revalidation is not performed when Denylist is not configured). What to do with this information is determined by the subscriber. The connection manager verifies the certificate of all peers and disconnects those that are no longer valid.
diagnostics also show the last time the certificate was updated, which is zero if the denylist is not used
```
network:
connections:
certificates_last_validated: 0001-01-01T00:00:00Z
connected_peers:
- id: ...
```
=> Network: re-validate peers after denylist update

docs/pages/deployment/tls-configuration.rst
Otherwise, bootstrapping nodes are disconnected (gRPC will report `RST_STREAM` error) due to (too) large pages being transmitted.
=> Docs: add proxy_buffering and client_max_body_size to example NGINX config

.github/workflows/build-images.yaml
fixes #2250
as stated by https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> rewrite github docker action set-output

http/engine_test.go
closes #2256 
Cors headers do work, adjusted tests to confirm.
=> rewrite CORS tests to use correct headers

docs/_static/vcr/oidc4vci_v0.yaml, vcr/api/oidc4vci/v0/wallet_test.go, vcr/holder/oidc4vci_wallet_test.go, vcr/issuer/openid4vci/issuer.go, vcr/oidc4vci/docs/README.md
in the editors draft (v13) `types` has been renamed to `type` to match to json-ld reserved name
part of #2281
=> OID$VCI: rename types to type

docs/_static/vcr/oidc4vci_v0.yaml, vcr/issuer/openid4vci/issuer.go, vcr/issuer/openid4vci/issuer_test.go, vcr/oidc4vci/error.go
`invalid_or_missing_proof` has been renamed to `invalid_proof`. This is the only change to the error codes to date.
=> OIDC: Rename invalid proof error codes

.github/workflows/build-images.yaml
fixes #2167 
`latest` was always created, now it's only enabled if the tag being build is the latest github tag.
=> only enable latest tag for docker if build tag equals latest github tag

core/tls_test.go, http/engine_test.go, main_test.go, network/network_integration_test.go, network/network_test.go, network/transport/grpc/config_test.go, network/transport/grpc/connection_manager_test.go, test/node/server.go, test/pki/test.go
Easier to read, more resilient to moving files around.
=> Embed test PEM files instead of referencing via paths

.github/workflows/helm-chart-release.yaml
The action sets the newest chart as the latest release on GitHub by default
=> Helm: do not set new chart as latest release

vcr/search.go, vcr/search_test.go
Right now it logs a line for every invalid VCs, which might also be a revoked credential. Or untrusted. We're probably not interested in revoked credentials, _maybe_ in untrusted credentials (to find out why you can't find a certain VC). So best option to both keep the errors but also declutter the DEBUG log is to just log the error counts, individual errors on TRACE.
Example DEBUG log:
```
Filtered 13 invalid VCs from search results (more info on TRACE): 'EOF' (1 times), 'credential is revoked' (2 times), 'credential issuer is untrusted' (10 times)
```
=> VCR Search: don't log each individual invalid search result

core/http_client.go, core/http_client_test.go, vcr/config.go, vcr/holder/oidc4vci_wallet.go, vcr/holder/oidc4vci_wallet_test.go, vcr/issuer/openid4vci/issuer.go, vcr/issuer/openid4vci/issuer_test.go, vcr/oidc4vci/config.go, vcr/oidc4vci/issuer_client.go, vcr/oidc4vci/wallet_client.go, vcr/vcr.go, vcr/vcr_test.go
closes #2061 
I added a `StrictHTTPClient` to `core.http_client` which returns a `HTTPRequestDoer`. It wraps an `http.Client` and the `strictmode` config to make sure an error is returned when a non-HTTPS address is called when in strictmode.
Due to the additional passing of `strictmode`, I created a `oidc4vci.ClientConfig` to pass `strictmode`, `TLS.Config` and `ClientTimeout` and reduce the amount of parameters.
=> only allow openid4vci calls over https when strictmode is enabled

vcr/issuer/openid4vci/assets/definitions/NutsAuthorizationCredential.json, vcr/issuer/openid4vci/assets/definitions/NutsOrganizationCredential.json, vcr/issuer/openid4vci/issuer_test.go, vcr/issuer/openid4vci/test/valid/ExampleCredential.json
[spec says credential_definition](https://openid.bitbucket.io/connect/editors-draft/openid-4-verifiable-credential-issuance-1_0.html#name-credential-issuer-metadata-3)
=> fix typo: credentials_definition -> credential_definition

docs/_static/vcr/oidc4vci_v0.yaml, vcr/api/oidc4vci/v0/issuer.go, vcr/api/oidc4vci/v0/issuer_test.go, vcr/holder/openid.go, vcr/holder/openid_test.go, vcr/issuer/issuer_test.go, vcr/issuer/openid.go, vcr/issuer/openid_mock.go, vcr/issuer/openid_test.go, vcr/oidc4vci/error.go, vcr/oidc4vci/types.go
closes #2233
c_nonce is now filled with actual value. The c_nonce must match the same flow as the access token is bound to.
changed it from `*string` type to `string` type in `TokenResponse` struct since we always fill it.
=> generate and check c_nonce for credential request

e2e-tests/auth/selfsigned/run-test.sh, e2e-tests/nuts-network/direct-wan/run-test.sh, e2e-tests/nuts-network/gossip-overflow/run-test.sh, e2e-tests/nuts-network/gossip/run-test.sh, e2e-tests/nuts-network/private-transactions/prepare.sh, e2e-tests/nuts-network/private-transactions/run-test.sh, e2e-tests/nuts-network/ssl-offloading/haproxy/run-test.sh, e2e-tests/nuts-network/ssl-offloading/nginx/run-test.sh, e2e-tests/nuts-network/ssl-pass-through/run-test.sh, e2e-tests/oauth-flow/run-test.sh, e2e-tests/openid4vci/issuer-initiated/run-test.sh, e2e-tests/ops/key-rotation/run-test.sh, e2e-tests/storage/backup-restore/prepare.sh, e2e-tests/storage/backup-restore/run-test.sh, e2e-tests/storage/redis/run-test.sh, e2e-tests/util.sh
=> Cleanup: use --wait in e2e tests

e2e-tests/nuts-network/direct-wan/node-A/nuts.yaml, e2e-tests/nuts-network/direct-wan/node-B/nuts.yaml, e2e-tests/nuts-network/private-transactions/node-A/nuts.yaml, e2e-tests/nuts-network/private-transactions/node-B/nuts.yaml, e2e-tests/nuts-network/ssl-offloading/haproxy/node-A/nuts.yaml, e2e-tests/nuts-network/ssl-offloading/haproxy/node-B/nuts.yaml, e2e-tests/nuts-network/ssl-offloading/nginx/node-A/nuts.yaml, e2e-tests/nuts-network/ssl-offloading/nginx/node-B/nuts.yaml, e2e-tests/nuts-network/ssl-pass-through/node-A/nuts.yaml, e2e-tests/nuts-network/ssl-pass-through/node-B/nuts.yaml, e2e-tests/oauth-flow/node-A/nuts.yaml, e2e-tests/oauth-flow/node-B/nuts.yaml, e2e-tests/openid4vci/issuer-initiated/node-A/nuts.yaml, e2e-tests/openid4vci/issuer-initiated/node-B/nuts.yaml, e2e-tests/ops/key-rotation/node-A/nuts.yaml, e2e-tests/ops/key-rotation/node-B/nuts.yaml, e2e-tests/storage/backup-restore/node-A/nuts.yaml, e2e-tests/storage/redis/node-A/nuts.yaml, e2e-tests/storage/redis/node-B/nuts.yaml, e2e-tests/storage/vault/nuts.yaml
=> Cleanup: remove old network.tls properties from e2e tests

vcr/issuer/openid.go, vcr/issuer/openid_test.go, vcr/oidc4vci/error.go
Should be `invalid_or_missing_proof` according to https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-credential-error-response
=> OpenID4VCI: fix unknown nonce error

network/dag/consistency.go, network/dag/consistency_test.go, network/dag/interface.go, network/dag/mock.go, network/dag/state.go, network/dag/tree/tree.go, network/dag/tree/tree_test.go, network/transport/v2/handlers.go, network/transport/v2/handlers_test.go, network/transport/v2/protocol_integration_test.go, network/transport/v2/protocol_test.go
closes #2295 
The dag state now starts a go routine that loops over parts of the dag when triggered. The trigger is a multiple XOR comparison failure detected from gossip messages. All connected nodes will need to have a different XOR before it's triggered. When triggered it handles a page of TX per 10 seconds.
The fix does not run as migration on startup. Although performance is good enough (20k tx/s), it exposes healthy nodes to an alternate code path which was previously not present. With this solution only nodes with a broken xor tree will be exposed to this code, reducing the risk of introducing new bugs for healthy nodes.
iblt trees are not repaired as discussed in #2295
=> add xor tree repair loop

network/transport/grpc/connection_manager.go, pki/cmd.go, pki/config.go, pki/config_test.go, pki/denylist.go, pki/test.go, pki/validator_test.go
This PR adds default config values for the denylist.URL and denylist.TrustedSigner. This will cause the nuts-node to periodically download the denylist hosted at https://github.com/nuts-foundation/denylis. An e2e test will be added after this is merged
=> PKI: add denylist Key and URL

vcr/holder/openid.go, vcr/holder/openid_test.go, vcr/issuer/openid.go, vcr/issuer/openid_test.go, vcr/openid4vci/issuer_client.go, vcr/openid4vci/types.go, vcr/openid4vci/wallet_client.go, vcr/test/openid4vci_integration_test.go, vcr/vcr.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/2315
We should probably test this using the performance test?
=> OpenID4VCI: Re-use http.Client for connection re-use

docs/pages/deployment/tls-configuration.rst, e2e-tests/nuts-network/ssl-offloading/nginx/docker-compose.yml, e2e-tests/nuts-network/ssl-offloading/nginx/node-A/nginx.conf, e2e-tests/oauth-flow/docker-compose.yml, e2e-tests/oauth-flow/node-A/nginx.conf
Not sure if we should already fix this.
The [http2 directive](https://nginx.org/en/docs/http/ngx_http_v2_module.html#http2) is introduced in v1.25.1 that was released on 2023-06-13. Updating this now might be causing more issues with older versions than it is fixing.
=> Docs: update deprecated NGINX http2 directive

docs/pages/deployment/backup-restore.rst, vcr/issuer/leia_store.go, vcr/test.go, vcr/vcr.go, vcr/vcr_test.go, vcr/verifier/leia_store.go, vcr/verifier/leia_store_test.go
Supposed to be part of #2317. #2323 only migrated issuer store to use new wrapper.
This PR adds the backup for the wallet and the revocations. This also eliminates a large part of the restore procedure.
=> Configure backup shelves for credentials and revocations

e2e-tests/nuts-network/private-transactions/node-A/nuts.yaml, e2e-tests/nuts-network/private-transactions/node-B/nuts.yaml, vcr/test/openid4vci_integration_test.go, vcr/vcr.go
without this the issuer panics when issuing if vcr.OpenID4VCI.Enabled=false because vcr.localWalletResolver == nil
=> Only set issuer.openidHandlerFn when vcr.OpenID4VCI.Enabled

docs/_static/vcr/openid4vci_v0.yaml, vcr/api/openid4vci/v0/generated.go, vcr/holder/openid.go, vcr/holder/openid_test.go, vcr/issuer/openid.go, vcr/issuer/openid_test.go
Make paths simpler;
- OAuth2 endpoints should be directly under the DID (`/token`)
- We don't need the `/issuer` and `/wallet` prefixes for openid4vci endpoints, since they don't overlap
=> OpenID4VCI: Move OAuth2 paths out of openid4vci subpath

vdr/vdr.go
Semantics are slightly different (now any private key matches) but it's for diagnostics only, so an extra false positive in a super-super edge case doesn't hurt.
Fixes https://github.com/nuts-foundation/nuts-node/issues/2311
=> VDR: Use cached IsOwned function for finding owned conflicts

network/transport/v2/handlers.go, network/transport/v2/handlers_test.go
fixes #2406 
When a node does a full sync it will request missing pages. This could result in a request of thousands of transactions. The peer sending those will not handle this request in a streaming way and will thus consume a lot of resources to fulfil the request. Syncing goes much smoother when only requesting 2 pages at a time. If more pages are requested, this PR will also change that the peer only sends 2.
=> Only request 2 pages per conversation on full sync

vdr/didnuts/didstore/integration_test.go, vdr/didnuts/didstore/store.go, vdr/didnuts/didstore/writer.go
fixes #2403 
by caching all conflicted documents at startup and updating them at runtime, the deadlock is removed.
It also speeds up the diagnostics in general.
=> cache conflicted docs in memory

vdr/didnuts/resolver.go, vdr/didnuts/resolver_test.go
fixes #2405 
only broken on master, probably due to the resolver refactor.
Added a test case to reproduce.
The resolver#ResolveControllers returned an error if one of the controllers couldn't be resolved. This is always the case when you resolve with a sourceTX in the resolveMetadata. On the development network this will always fail at tx:555. The ResolveControllers method should not stop on ErrNotFound but it should continue with resolving the other controllers.
=> ResolveControllers should return controllers that can be resolved

events/event.go, events/integration_test.go, events/stream.go, events/stream_test.go
fixes #2401 
this PR sets the limit to a 1000 messages (arbitrary) at the client waiting for an ack. Without this config the server would send all possible messages as fast as it could. Since the server is localhost, this is quite fast.
Now the server will wait at a thousand messages.
I also removed some dead configuration code...
=> limit number of nats messages waiting for an ack to 1000 at the client

.circleci/config.yml, Dockerfile, auth/services/selfsigned/signer_test.go, go.mod, go.sum, http/engine_test.go, vcr/pe/schema/go.mod
fixed breaking tests:
- context.TODO == context.Background is no longer true
- missing certificate error message changed
upgraded go version in:
- go.mod
- docker build
- circleci tests
=> upgrade go 1.21

auth/api/auth/v1/api_test.go, auth/api/iam/api.go, auth/api/iam/api_test.go, auth/api/iam/generated.go, auth/api/iam/implementation_documentation/README, auth/api/iam/implementation_documentation/metadata_types.go, auth/api/iam/metadata.go, auth/api/iam/metadata_test.go, auth/api/iam/types.go, auth/auth.go, auth/interface.go, cmd/root.go, codegen/configs/auth_iam.yaml, docs/_static/auth/iam.yaml
WIP
discussion point: 
auth.publicurl should become a required config field (and possibly move to root of config).
Its value is required on all .well-known endpoints. (oauth-authorization-server, (oauth) client, openid-credential-issuer, openid-credential-wallet, did.json, ...) 
To me it makes a lot of sense that you have to configure the _public address_ of the node for it to work (vault and redis require it too). We could set the default to http://localhost:1323 in non-strict mode when no value is provided, but guessing what the address is just adds to much complexity and room for errors (will require support) for something that is not very hard to configure.
TODO
=> OAuth add /.well-known/oauth-authorization-server endpoint

audit/http.go, auth/api/iam/api.go, auth/api/iam/assets/authz_wallet_en.html, auth/api/iam/assets/openid4vp_demo.html, auth/api/iam/assets/openid4vp_demo_completed.html, auth/api/iam/generated.go, auth/api/iam/openid4vp.go, auth/api/iam/openid4vp_demo.go, auth/api/iam/openid4vp_test.go, auth/api/iam/presentation_definitions.go, auth/api/iam/rendering.go, auth/api/iam/rendering_test.go, auth/api/iam/session.go, docs/_static/auth/iam.yaml
Next things to work on, fitting into this PR:
- Support direct_post mode for sending the authorization response from wallet to verifier, instead of having it as parameters on the redirect back to the verifier.
- Replace hardcoded metadata URLs with the ones specified by https://github.com/nuts-foundation/nuts-node/pull/2443 
- Support VPs in JWT format (consuming and producing), for compatibility with non-Nuts nodes
- Match Presentation Definition with credentials in wallet, instead of just loading credentials from VCR store (requires  https://github.com/nuts-foundation/nuts-node/issues/2389)
- Do some styling of the HTML templates for the "WOW!" factor
- i18n HTML templates (we should at least support Dutch)
- Support presentation_definition and presentation_definition_uri, so the …
=> OpenID4VP: Implement authorization request and handling

docs/pages/release_notes.rst, storage/leia.go, storage/leia_test.go
fixes #2448 
The set that is written in a single transaction is now correctly reset after a transaction.
=> fix correct backup store initiation

auth/api/iam/metadata.go, auth/api/iam/metadata_test.go, auth/api/iam/types.go
part of #2447
Adds `vp_formats` field to authorization server metadata.
=> add vp_formats to authorization server metadata

.github/workflows/govulncheck.yaml
The check now automatically uses the latest `stable` version of go. This means that we will not get notified of any vulnerabilities that may exist in go patch versions, but should be fine since we update asap anyway.
=> Set govulncheck's go-version to 'stable'

auth/api/iam/api.go, auth/api/iam/api_test.go, auth/api/iam/generated.go, auth/api/iam/implementation_documentation/metadata_types.go, auth/api/iam/metadata.go, auth/api/iam/metadata_test.go, auth/api/iam/types.go, codegen/configs/auth_iam.yaml, docs/_static/auth/iam.yaml
I tried to fill out as much as possible, but there are still a bunch of unknowns (tagged with TODOs). I've skipped all the fields related to openid connect / id_token for now. We can add these as needed.
=> Add client metadata + API

auth/api/iam/api_test.go, auth/api/iam/generated.go, auth/api/iam/s2s_vptoken.go, auth/api/iam/s2s_vptoken_test.go, docs/_static/auth/iam.yaml
fixes #2484 
This is a scaffold + input checking for the s2s RequestAccessToken internal API.
Placed under iam package. I could imagine our internal APIs for authv2 to be placed under the auth package instead?
+regenerated APIs using codegen 1.15.0
=> added auth v2 request access token api for s2s flow

auth/api/iam/api.go, auth/api/iam/api_test.go, auth/api/iam/generated.go, docs/_static/auth/iam.yaml
The APIs under `iam/{id}` no longer expect a DID as param but only the ID part.
=> changed OAS to reflect path component is the ID part of a DID

auth/api/iam/api.go, auth/api/iam/api_test.go, auth/api/iam/authorized_code.go, auth/api/iam/error.go, auth/api/iam/error_test.go, auth/api/iam/generated.go, auth/api/iam/openid4vp.go, auth/api/iam/openid4vp_test.go, auth/api/iam/types.go, cmd/root.go, codegen/configs/auth_iam.yaml, http/requestlogger.go
This PR introduces an OAuth2 error handler that:
- Redirects the browser back to the provided `redirect_uri` (with `error` and `error_description` parameters)
- If there's no `redirect_uri`, it either prints the error as plain text (for a browser) or JSON (for an API client)
It also fixes HTTP request logging status codes for the IAM API package.
=> IAM: Implement correct OAuth2 error handling

network/dag/consistency_test.go, network/transport/grpc/connection_manager_test.go, network/transport/v2/gossip/manager_test.go, network/transport/v2/protocol_test.go, network/transport/v2/transactionlist_handler_test.go, pki/validator_test.go, storage/engine.go, storage/interface.go, storage/mock.go, storage/session.go, storage/session_test.go, storage/test.go, vcr/issuer/openid.go, vcr/issuer/openid_store.go, vcr/issuer/openid_store_test.go, vcr/issuer/openid_test.go, vcr/vcr.go
closes #2391 
This moves the in memory session store to the storage engine. In a later stage this makes it easier to change the in memory variant to a clustered variant.
The generic one includes expiry out-of-the-box.
It uses the JSON marshalling style of set and get for generics.
=> move session store to storage.SessionDatabase

go.mod, go.sum, vdr/didkey/resolver.go, vdr/didkey/resolver_test.go, vdr/vdr.go, vdr/vdr_test.go
We might need this for supporting demos with Sphereon wallet.
This adds a dependency on `go-multicodec`, which we could go without if we just take the constants (it's a limited set).
TODO:
=> Resolving did:key DIDs

crypto/jwx.go, crypto/jwx_test.go, didman/didman.go, go.mod, vdr/didkey/resolver.go, vdr/didkey/resolver_test.go
(more active OSS contributor)
Both libraries were already a transitive dependency, just replaced the direct usage.
=> Switch to mrtron/base58 lib, maintainer looks more reputable 

auth/api/iam/metadata.go, auth/auth.go, core/url.go, core/url_test.go, network/transport/types.go
All URLs obtained from external sources (metadata endpoints) need to be validated for OAuth2/OpenID4VC meaning that all methods using these URLs will require the following codeblok:
```
if strictmode {
issuerURL, err = core.ParsePublicURL(issuer, false, "https")
} else {
issuerURL, err = core.ParsePublicURL(issuer, true, "https", "http")
}
```
This PR makes that a bit easier
=> Refactor ParsePublicURL

network/dag/notifier.go, network/dag/notifier_test.go
This will only log non-retryable errors once, and ignores events at startup that failed on an unknown context.
=> Backport5.4/refactor retry event at startup

network/network_test.go
Certificate recently expired, so the test is now finally testing what it said it was testing.
=> Fix broken test

vcr/holder/wallet.go, vcr/holder/wallet_test.go
Verifiable Presentations, regardless whether they're in JSON-LD or JWT format, should have an ID (although not required by VC data model).
Required by use case list; VPs can be part of a tombstone set based on their ID.
=> Add ID to Verifiable Presentations

auth/api/iam/api.go, auth/api/iam/api_test.go, auth/api/iam/generated.go, auth/api/iam/s2s_vptoken.go, auth/api/iam/s2s_vptoken_test.go, auth/api/iam/types.go, codegen/configs/auth_iam.yaml, docs/_static/auth/iam.yaml
closes #2541
I've copied the v1 introspection OAPI and edited it. There are still a couple of fields unused for the user authentication part.
I've also removed the issuer key from the s2s access token store since its not available during introspection
=> Add introspection endpoint for s2s flow

vcr/pe/presentation_submission.go, vcr/pe/presentation_submission_test.go, vcr/pe/test/test_definitions.go, vcr/pe/types.go
Simplified logic a bit; `1 InputDescriptorMapping = 1 Credential` (instead of `1..n` credentials), nesting only if there's multiple VPs.
=> PEX: Changed path_nested to be object instead of slice

vcr/credential/resolver.go, vcr/credential/resolver_test.go, vcr/pe/presentation_definition.go, vcr/pe/presentation_submission.go, vcr/pe/presentation_submission_test.go
`PresentationSubmission.Resolve()` yields a map of input descriptor IDs to mapped credential.
=> PEX: Resolve credentials from presentation submission

vcr/pe/presentation_definition.go, vcr/pe/presentation_submission.go, vcr/pe/presentation_submission_test.go, vcr/pe/util.go, vcr/pe/util_test.go, vcr/test/test.go
Excerpt from https://github.com/nuts-foundation/nuts-node/pull/2518
=> PEX: Provide ParseEnvelope to correctly parse PEX VP envelopes

docs/_static/vcr/vcr_v2.yaml, vcr/api/vcr/v2/api.go, vcr/api/vcr/v2/api_test.go, vcr/api/vcr/v2/generated.go
closes #2642 
primary use case is to load a VC into the wallet when issued to a web:did.
=> load a VC into a wallet via the internal API

vcr/pe/presentation_submission.go, vcr/pe/presentation_submission_test.go, vcr/pe/test/test_definitions.go
go-did marshals `verifiableCredential` to a JSON object instead of an array in that case.
=> PEX: ldp_vp submission with 1 VC should not index credential property

discovery/interface.go, discovery/interface_test.go, discovery/mock.go, discovery/module.go, discovery/module_test.go, discovery/store.go, discovery/store_test.go, docs/_static/discovery/v1.yaml, storage/sql_migrations/001_discoveryservice.sql
Timestamp returned from server changed to string, to allow tags from multiple several to be discerned from each other.
Also changed the name to "tag" since timestamp indicates a clock and/or number. This makes having a lamport clock code-wise easier for function/type naming.
=> Discovery: opaque timestamp

auth/api/auth/v1/api.go, auth/services/selfsigned/signer.go, auth/services/selfsigned/signer_test.go
Signature verification performed more elaborate checks (employee details non-empty strings) than on session creation, which allows EmployeeID sessions to fail on input that was deemed valid earlier. That causes confusion, so should be the same.
Also, validation failure reason isn't logged or returned. Ideally it's returned to the client, but then we have to alter (extend) the OpenAPI spec. So for now, only log it.
Or should we still return it?
=> Auth: create session and validate signatures perform the same checks

vcr/pe/presentation_definition.go, vcr/pe/presentation_definition_test.go, vcr/pe/test/pd_jsonld_jwt.json
Required for token introspection and Discovery Service search results.
=> PEX: Resolve values mapped by Input Descriptor constraint fields

discovery/test.go, vcr/credential/resolver.go, vcr/credential/resolver_test.go, vcr/holder/wallet.go, vcr/test/test.go
=> Derive signer of JWT-VP from the kid header, not the 'iss' field

discovery/api/v1/generated.go, discovery/api/v1/wrapper.go, discovery/api/v1/wrapper_test.go, discovery/interface.go, discovery/mock.go, discovery/module.go, discovery/module_test.go, discovery/test.go, docs/_static/discovery/v1.yaml
PR adds `Discovery.Seach()` API that searches for presentations registered on a discovery service. The actual search functionality for the database already existed in the store implementation, this PR adds API exposure.
Alongside the matching VPs, it also returns a map with fields from the PEX definition mapped to credential fields, just like the OAuth2 token introspection API. This is useful for displaying search results (e.g. organization search like in Demo EHR).
Example output:
```json
[
{
"vp": "eyJhbGciOiJFUzI1NiIsImtpZCI6ImRpZDpleGFtcGxlOmFsaWNlIzAiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOlsidXNlY2FzZV92MSJdLCJleHAiOjE3MDQyMTI1MTksImlzcyI6ImRpZDpleGFtcGxlOmFsaWNlIiwianRpIjoiZGlkOmV4YW1wbGU6YWxpY2UjOGE5NWVlMTYtZmI1Ny00NjYzLThkZTctY2Y2NzJmMTRlNWQzIiwibmJmIjoxNzA0MTgzNzE5LCJzdWIiOiJkaWQ6ZXhhbXBsZTp …
```
=> Discovery: search API for clients

discovery/api/v1/api.go, discovery/api/v1/api_test.go, discovery/api/v1/generated.go, docs/_static/discovery/v1.yaml
Found these issues while fixing the e2e test.
Fixes:
- Endpoint was intended as an internal endpoint, moved it to `/internal/discovery/v1`
- Use of dynamic query parameters isn't supported by codegen, workaround
=> Discovery: fix API of Client.Search()

vcr/test/openid4vci_integration_test.go, vdr/api/v1/api.go, vdr/api/v1/api_test.go, vdr/api/v2/api.go, vdr/api/v2/api_test.go, vdr/didnuts/creator.go, vdr/didnuts/manager.go, vdr/didnuts/manager_test.go, vdr/didweb/manager.go, vdr/integration_test.go, vdr/interface.go, vdr/management/management.go, vdr/management/management_mock.go, vdr/mock.go, vdr/vdr.go, vdr/vdr_test.go
To produce a DID document of a certain type, you need to implement the `DocumentManager` interface. This is in preparation of extending the functionality of updating `did:web` documents; after this PR, https://github.com/nuts-foundation/nuts-node/pull/2734 will add CRUD for services. Later on, Verification Method CRUD might be added as well.
The goal is to have VDR only delegate calls to supported DID methods.
When `did:nuts` support is removed, many of the "old" (current) interfaces can be removed, this one will remain.
=> VDR: Group all DID Document management funcs in a new interface

pki/denylist.go
Or should NOK be WARN, to signal ops?
=> PKI: Adjust validation logging; OK = trace, NOK = info

codegen/configs/discovery_v1.yaml, discovery/api/v1/api.go, discovery/api/v1/generated.go, discovery/api/v1/types.go, discovery/interface.go, discovery/mock.go, discovery/module.go, discovery/module_test.go, docs/_static/discovery/v1.yaml
Required for future "Nuts Admin"-applications that want to show which Discovery Services are available.
=> Discovery: API to list configured Discovery Services

charts/nuts-node/templates/nuts-data-pv.yaml
Incorporated a conditional that checks if 'storageClassName' exists under .Values.nuts.data.persistedVolume in nuts-data-pv.yaml. The GKE platform sets the storageClassName to its own value after creation. When Helm runs a diff on the upgrade command, the change of the value of the storageClassName is detected. Helm than tries to patch the PVC, causing an error as it is immutable. This causes the upgrade command to fail. This solution only sets the storageClassName if the values.yaml explicitly does so, preventing this error condition to happen.
=> Add conditional for storageClassName in nuts-data-pv.yaml

vdr/api/v1/api.go, vdr/api/v1/api_test.go, vdr/api/v2/api.go, vdr/api/v2/api_test.go, vdr/cmd/cmd.go, vdr/didnuts/ambassador_test.go, vdr/didnuts/creator.go, vdr/didnuts/creator_test.go, vdr/didnuts/manager.go, vdr/didnuts/manager_test.go, vdr/didweb/manager.go, vdr/didweb/manager_test.go, vdr/management/management.go, vdr/management/management_mock.go, vdr/management/management_test.go, vdr/mock.go, vdr/vdr.go, vdr/vdr_test.go
DID methods have their own creation options, SelfControl and Controllers are `did:nuts` specific. `did:web` has (user) "id" (last path part in the DID).
This moves `did:nuts` options to the `didnuts` package and introduces an option for `did:web`.
=> VDR: Introduce DID method-specific creation options

storage/engine.go, storage/gorm_logger.go, storage/gorm_logger_test.go
By default, GORM writes logs in a custom format to stdout. GORM currently triggered on errornous SQL (also "record not found") and when queries take longer than 200ms.
This PR introduces a GORM logger that pipes the logging to logrus.
The implementation (and the slow SQL threshold) of `Trace()` is reflects its default implementation in GORM (although a bit simplified).
=> SQL: Redirect GORM logging to logrus

discovery/api/v1/api.go, discovery/api/v1/api_test.go
=> Discovery: return no search results as empty array

discovery/api/v1/api.go, discovery/api/v1/api_test.go, discovery/api/v1/generated.go, docs/_static/discovery/v1.yaml
So client application's don't need to parse the returned VPs
=> Discovery: return subject ID in search results

discovery/client.go, discovery/client_test.go, discovery/cmd/cmd.go, discovery/config.go, discovery/config_test.go, discovery/module.go, discovery/module_test.go
We had 2 background processes for refreshing Verifiable Presentations and fetching the latest changes from the Discovery Service. Simplified this to 1 process managed directly from the module, since there's no need to control the interval at which these run independently.
This also enabled putting the loading of changed/new Verifiable Presentations from the server directly after the refresh job, which causes refreshed VPs (of owned DIDs) to be immediately be in effect on the local copy of the Discovery Service. Otherwise, the client would see "stale" data.
This was still the case after `activate()` is called, so we now explicitly update the Discovery Service after successful registration.
=> Discovery: 1 background process for refreshing Discovery Service

go.mod, go.sum, vdr/resolver/did_test.go, vdr/resolver/key_test.go
When resolving keys, `DID.URI()` caused percent-encoded characters to be encoded again, causing private keys not be found.
=> VDR: Fix resolving keys for did:web DIDs with port

storage/test.go
invalid migration files return an error from storage.Configure that was ignored
=> fix ignored db migration error in tests

auth/api/iam/api.go, auth/api/iam/api_test.go, auth/api/iam/generated.go, auth/api/iam/types.go, codegen/configs/auth_iam.yaml, docs/_static/auth/iam.yaml, docs/_static/vcr/vcr_v2.yaml, e2e-tests/discovery/run-test.sh, e2e-tests/oauth-flow/openid4vp/run-test.sh, e2e-tests/oauth-flow/rfc021/run-test.sh, vcr/api/vcr/v2/api.go, vcr/api/vcr/v2/api_test.go, vcr/api/vcr/v2/generated.go, vcr/credential/statuslist2021/bitstring.go, vcr/issuer/interface.go, vcr/issuer/issuer.go, vcr/issuer/issuer_test.go, vcr/issuer/mock.go, vcr/issuer/statuslist2021_store.go, vcr/issuer/statuslist2021_store_test.go, vcr/types/constants.go
closes #2690 
this PR adds
- option to add credentialStatus entry to a VC during issuance
- revoking credentials with a credentialStatus
- fetching StatusList2021Credentials for issuers that have issued credentials with a credentialStatus
`example.com/iam/123/statuslist/1`
- in memory store that will be replaced by a sql store in a follow-up PR
=> StatusList: issuance

vcr/credential/revocation.go, vcr/credential/validator.go
It's a weird thing and its only purpose apparently is to prepend `validation failed: ` to the error string you give it. Since it only takes a string, you also lose the other error types being wrapped.
=> Remove credential.validationError

vcr/test.go, vdr/integration_test.go, vdr/resolver/did.go, vdr/resolver/did_test.go, vdr/vdr.go, vdr/vdr_test.go
Owned DIDs don't need to be fetched "remotely" from the own node.
Fixes https://github.com/nuts-foundation/nuts-node/issues/2639
=> VDR: Resolve did:web from database first, then HTTP

golden_hammer/module.go, golden_hammer/module_test.go
Might have to go altogether, but for now at least it should only look at `did:nuts` DIDs.
=> GoldenHammer: only work on did:nuts documents

vcr/issuer/issuer.go, vcr/issuer/issuer_test.go
PR contains
- split VC signing from building (needed for statuslist2021)
- issue statuslist2021 credentials with `validFrom`/`validUntil` fields (bug fix)
- always set `issuanceDate` in builder function. The API does not allow setting the issuanceDate, and we have an exported `TimeFunc()` to set a value for testing.
=> Issuer: split builder and signer

auth/api/iam/openid4vp_test.go
there are 2 tests with the same name `"invalid presentation_definition_uri"`, the second then gets a number appended by the standard library `"invalid presentation_definition_uri#01"`. This is then also used by the test to generate a TempDir. 
The `#` in the name of the TempDir sometimes causes problems on consecutive runs of the same test on my laptop.
=> fix test name

vcr/ambassador.go, vcr/ambassador_test.go
=> VCR: Do not log disallowed JSON-LD context URL as error

discovery/store.go, storage/engine.go, storage/engine_test.go, vcr/credential/store/sql_test.go, vcr/statuslist2021/store.go, vcr/statuslist2021/store_test.go
by limiting SQLite to 1 connection there is no need to have write locks in code to simulate SELECT FOR UPDATE.
this results in a deadlock when a new transaction is started from within a transaction, but this will fail during development.
=> Restrict SQLite driver to 1 DB connection

auth/api/iam/validation.go, auth/api/iam/validation_test.go, vcr/holder/wallet.go, vcr/holder/wallet_test.go, vcr/pe/presentation_submission.go, vcr/pe/presentation_submission_test.go
closes #2800
needed changes to allow for empty VPs to be built when requested so by an empty presentation definition.
This makes testing without any credentials easier when still conforming to specs.
=> allow for empty VPs to be build when no credentials are requested

auth/api/iam/api.go, auth/api/iam/api_test.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/2778
=> IAM: Handle ErrNotFound for unknown tokens when introspecting

core/echo_errors.go, core/echo_errors_test.go, http/requestlogger.go, http/requestlogger_test.go
They always default to 500, because the HTTP request logger used its own status code resolver. It now re-uses the one used by the error handler.
Fixes https://github.com/nuts-foundation/nuts-node/issues/2274
=> HTTP: correct status code logging for errors

.github/workflows/build-images.yaml
closes #1629 
this drops the tag `v` prefix for docker images, so tag `v6.0.0` creates docker image `nutsfoundation/nuts-node:6.0.0`
it also removes the major version tag (`nutsfoundation/nuts-node:6`). This is currently broken as tagging 6.0.1 will set this version as 6, even if tag 6.1.0 already exists.
Maybe wait to merge this until we are sure there will not be a v5.5.*
=> Docker: drop 'v' prefix from versions

.github/workflows/govulncheck.yaml
partially reverts #2862
`go-version-input: 'stable'` uses the latest patch version
`go-version-file: 'go.mod'` does not domain a patch version resulting in all current failures. 
We always build with the latest patch version asap, so using version 'stable' should be fine
=> Fix govulncheck: revert go-version to stable

e2e-tests/oauth-flow/run-tests.sh, e2e-tests/oauth-flow/statuslist2021/docker-compose.yml, e2e-tests/oauth-flow/statuslist2021/node-A/nuts.yaml, e2e-tests/oauth-flow/statuslist2021/node-B/nuts.yaml, e2e-tests/oauth-flow/statuslist2021/run-test.sh, vcr/issuer/issuer.go, vcr/issuer/issuer_test.go, vcr/revocation/statuslist2021_issuer.go, vcr/revocation/statuslist2021_issuer_test.go, vcr/revocation/statuslist2021_verifier_test.go, vcr/revocation/types.go, vcr/revocation/types_test.go, vcr/verifier/verifier_test.go
closes #2880 
This PR adds an e2e test. 
The e2e test revealed an issue where using a SQLite db would deadlock when trying to resolve an issuers signing key (loading did doc). Key resolving is now done outside the transactions that needs the key.
The fix above also allows partially reverting  #2827 to merge the `issuers.buildAndSignVC` and `.signVC` methods; This means key checking to moved back to the top which is probably sufficient to fix #2856. This time I added a comment on the check to keep key resolving at the top.
=> StatusList2021: add e2e test

storage/sql_migrations/003_did.sql, vdr/didweb/store.go
according to DID spec, the id always contains the DID, no need to have a primary key consist of both the did and id
also it would be too long (3140 bytes)
=> set primary key for did service and vm to id

docs/pages/integrating/api.rst
closes #2863 
https://nuts-node.readthedocs.io/en/api-update-rtd-2863/pages/integrating/api.html
specs are now order alphabetically with deprecated specs at the end. This conveniently places the new auth/v2 at the top of the list. 
I've removed the download links since I always click on the spec I am interested in before swagger ui is loaded. The files can still be downloaded from the individual spec references.
=> Docs: update API Reference

auth/auth.go, auth/auth_test.go, network/network.go, network/network_integration_test.go, network/network_test.go
When deploying my Discovery Server, I came across the issue that I must configure TLS (truststore, certificate and key) when strict mode is enabled.
This Nuts node only acts as Discovery Server; it only uses did:web and does not participate in a did:nuts network, meaning it does not need a client certificate (it does not connect to other node over gRPC or HTTP endpoints that require a client certificate).
This PR fixes the following:
- fixes the existing lenient check in the `network` module to allow TLS to be disabled when no bootstrap nodes are configured and there are no discovered nodes. The intended leniency is broken because `assumeNewNode` is initialized after the said check
- remove TLS enabled check in strict mode in the auth module; the strict HTTP client already checks whether …
=> Tweaked strict mode checks to allow running without TLS

auth/api/auth/v1/api_test.go, auth/api/iam/api.go, auth/api/iam/api_test.go, auth/auth.go, auth/cmd/cmd.go, auth/cmd/cmd_test.go, auth/config.go, auth/interface.go, auth/mock.go, e2e-tests/discovery/node-B/nuts.yaml, e2e-tests/oauth-flow/openid4vp/node-A/nuts.yaml, e2e-tests/oauth-flow/openid4vp/node-B/nuts.yaml, e2e-tests/oauth-flow/rfc021/node-A/nuts.yaml, e2e-tests/oauth-flow/rfc021/node-B/nuts.yaml, e2e-tests/oauth-flow/statuslist2021/node-A/nuts.yaml, e2e-tests/oauth-flow/statuslist2021/node-B/nuts.yaml
closes #2907 
removes `auth.v2apienabled` option
=> Enable iam api by default

core/server_config.go
=> Fail to start when deprecated network params are used

vcr/credential/store/sql.go, vcr/credential/store/sql_test.go
fixes #2925
This is a simple fix that strips whitespace before comparing.
A better solution is to use the canonicalised form to compare. Created #2928 for that.
=> ignore whitespace when storing VCs

discovery/api/v1/generated.go, docs/_static/discovery/v1.yaml
=> Discovery: do not decode DIDs in API paths, which leads to invalid did:web DIDs

.dockerignore, development/network/docker-compose.yaml, docs/pages/getting-started/1-running-docker.rst, e2e-tests/auth/selfsigned/docker-compose.yml, e2e-tests/denylist/defaults/docker-compose.yml, e2e-tests/denylist/github/docker-compose.yml, e2e-tests/discovery/docker-compose.yml, e2e-tests/nuts-network/direct-wan/docker-compose.yml, e2e-tests/nuts-network/gossip-overflow/docker-compose.yml, e2e-tests/nuts-network/gossip/docker-compose.yml, e2e-tests/nuts-network/private-transactions/docker-compose.yml, e2e-tests/nuts-network/ssl-offloading/haproxy/docker-compose.yml, e2e-tests/nuts-network/ssl-offloading/nginx/docker-compose.yml, e2e-tests/nuts-network/ssl-pass-through/docker-compose.yml, e2e-tests/oauth-flow/openid4vp/docker-compose.yml, e2e-tests/oauth-flow/rfc002/docker-compose.yml, e2e-tests/oauth-flow/rfc021/docker-compose.yml, e2e-tests/oauth-flow/rfc021/mysql.yml, e2e-tests/oauth-flow/rfc021/postgres.yml, e2e-tests/oauth-flow/statuslist2021/docker-compose.yml, e2e-tests/openid4vci/issuer-initiated/docker-compose.yml, e2e-tests/openid4vci/network-issuance/docker-compose.yml, e2e-tests/ops/key-rotation/docker-compose.yml, e2e-tests/storage/backup-restore/docker-compose.yml, e2e-tests/storage/redis/docker-compose.yml, e2e-tests/storage/vault/docker-compose.yml
`version` is deprecated since the compose spec has merged versions 2 and 3: https://docs.docker.com/compose/compose-file/compose-versioning/
fixing this because deprecation warnings are complicating debugging on the rootless docker user feature
=> Remove deprecated 'version' from docker-compose.yaml files

core/server_config.go, storage/config.go, storage/engine.go, storage/engine_test.go
closes #2971 
I figured we might want to provide some useful info in the error, so this PR tries to redact the secret:
``` yaml
storage:
sql:
connection: "fake://user:password@example.com:123/db"
```
fails with
```
"unable to configure Storage: failed to initialize SQL database: unsupported SQL database connection: fake://<redacted>@example.com:123/db"
```
This might still fail, so just not logging the string ever is the safest option.
What do you think? If this is preferred I will add tests etc.
=> storage.sql.connection string redaction

auth/client/iam/client.go, core/http_client.go, core/http_client_test.go
I've noticed several times that 100 characters is just not enough for most genuine errors  that the Nuts node returns. 200 should probably cut it.
=> HTTP client: clip response body to log at 200 characters instead of 100

.github/workflows/build-images.yaml
closes #2890
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
=> cancel superseded docker build actions

docs/pages/deployment/discovery.rst
Highlighting of HTTP code blocks is weird with red rectangles
=> Docs: change Discovery HTTP code blocks to normal code blocks

docs/_static/discovery/v1.yaml, docs/_static/vcr/vcr_v2.yaml, e2e-tests/auth/selfsigned/main_test.go, vcr/api/vcr/v2/api_test.go, vcr/api/vcr/v2/generated.go, vcr/cmd/cmd.go, vcr/cmd/cmd_test.go
Fix invalid specs:
- Discovery: https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fnuts-node.readthedocs.io%2Fen%2Flatest%2F_static%2Fdiscovery%2Fv1.yaml
- VCR: https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fnuts-node.readthedocs.io%2Fen%2Flatest%2F_static%2Fvcr%2Fvcr_v2.yaml
=> fix invalid swagger

policy/local.go, policy/local_test.go, policy/test/2_files/1and2.json, policy/test/2_files/3.json, policy/test/2_files/README.md, policy/test/2_files_duplicate/1.json, policy/test/2_files_duplicate/2.json, policy/test/2_files_duplicate/README.md, policy/test/no_files/README.md
Fixes https://github.com/nuts-foundation/nuts-node/issues/3008
=> Policy: allow multiple policy files in local PDP

vcr/revocation/statuslist2021_issuer.go, vcr/revocation/statuslist2021_issuer_test.go, vcr/revocation/statuslist2021_verifier.go
closes #3026 
StatusList2021Credential renewal after expiration is a system operation and should not be logged against the party requesting the credential
=> Audit log StatusList2021Credential renewal against system

auth/api/iam/api.go, auth/api/iam/api_test.go, auth/api/iam/generated.go, auth/api/iam/openid4vp.go, auth/api/iam/openid4vp_test.go, auth/api/iam/pkce_util.go, auth/api/iam/pkce_util_test.go, auth/api/iam/session.go, auth/api/iam/user.go, auth/client/iam/interface.go, auth/client/iam/mock.go, auth/client/iam/openid4vp.go, auth/client/iam/openid4vp_test.go, auth/oauth/error.go, auth/oauth/types.go, codegen/configs/auth_iam.yaml, crypto/api/v1/api_test.go, crypto/random_test.go, docs/_static/auth/iam.yaml
part of #3012
checking PKCE verifier requires storing oauth request at the authorization server (based on state param). Also changed error returns for /token which used the redirect_uri. /token is a backchannel call so no redirects possible
=> add PKCE to OAuth2 authorization code flow

development/dev-image/Dockerfile, docs/pages/deployment/docker.rst
closes #3045 
dev container user is still `root`
=> set workdir in dev image

auth/api/iam/api.go, auth/api/iam/api_test.go, auth/api/iam/assets/error.html, auth/api/iam/assets/templates.go, auth/api/iam/assets/templates_test.go, auth/api/iam/user.go, auth/oauth/error.go, auth/oauth/error_test.go
Was broken due to the OAuth2 path remapping (endpoints moved from `/iam` to `/oauth2`).
Also, if the user agent can't be redirected, it  now renders as text/html with:
```
invalid_request - no credentials available
```
(example)
=> IAM: fix OAuth2 error handling

auth/api/iam/api.go, auth/api/iam/api_test.go, auth/api/iam/metadata.go, auth/api/iam/metadata_test.go, auth/api/iam/openid4vp.go, auth/api/iam/openid4vp_test.go, auth/api/iam/params.go, auth/api/iam/types.go, auth/api/iam/user.go, auth/api/iam/user_test.go, auth/auth.go, auth/client/iam/interface.go, auth/client/iam/mock.go, auth/client/iam/openid4vp.go, auth/client/iam/openid4vp_test.go, auth/oauth/error.go, auth/oauth/jwx_es256k.go, auth/oauth/openid.go, auth/oauth/types.go, cmd/root.go
cleanup in preparation of #2712 
This change is needed since JAR with a `request_uri` will require storing some state. This belongs in the server and not he client.
also contains some bug fixes and cleanup that got squashed into 1 commit by accident after a rebase
=> refactor: move CreateAuthorizationRequest from OpenID4VPClient to Wrapper

charts/nuts-node/README.md, charts/nuts-node/templates/NOTES.txt, charts/nuts-node/templates/deployment.yaml, charts/nuts-node/templates/ingress.yaml, charts/nuts-node/templates/service.yaml, charts/nuts-node/templates/tests/test-connection.yaml, charts/nuts-node/values.yaml
This revision refactors nuts-node charts to support separate internal and external services. It provides different ingress classes, annotations, hosts, and rules for external and internal services. It also adjusts `service.yaml` to accommodate these changes and provides different application URLs for internal and external services. Configurations in `values.yaml` have been altered to reflect these changes as well.
=> Refactor nuts-node chart for separate internal and external services

auth/services/selfsigned/test/generate_test.go, jsonld/testsuite/compat_test.go, vcr/holder/presenter.go, vcr/issuer/issuer.go, vcr/issuer/issuer_test.go, vcr/signature/json_web_signature.go, vcr/signature/json_web_signature_test.go, vcr/signature/mock.go, vcr/signature/proof/jsonld.go, vcr/signature/proof/jsonld_test.go, vcr/signature/proof/proof.go, vcr/signature/signature.go
Because resolving `crypto.Key` requires another roundtrip to `KeyStore.Resolve`, which is done again when actually signing. So it only adds extra dependencies to functions that want to sign VCs.
Required by https://github.com/nuts-foundation/nuts-node/pull/3009
=> VCR: Sign through key ID instead of crypto.Key

docs/pages/deployment/pex.rst
For the token introspection response.
Also fixed styling issues (2 spaces instead of tabs to keep code blocks a bit more condensed).
=> PEX: Documentation on how a Policy maps Constraint Field IDs

auth/api/iam/api.go, auth/api/iam/api_test.go, auth/api/iam/generated.go, auth/api/iam/user_test.go, auth/client/iam/client.go, auth/client/iam/client_test.go, auth/client/iam/interface.go, auth/client/iam/mock.go, auth/client/iam/openid4vp.go, auth/client/iam/openid4vp_test.go, docs/_static/auth/iam.yaml
part of #2712
this adds the `request_uri` param as specced in [RFC9101](https://www.rfc-editor.org/rfc/rfc9101.html)
implemented separate from the OpenID4VP extension using `request_uri_method` to keep the PRs small
=> RFC9101 request_uri

auth/client/iam/client.go, core/http_client.go, core/http_client_test.go, vcr/openid4vci/issuer_client.go, vcr/revocation/statuslist2021_verifier.go, vdr/didweb/web.go
To prevent DoS (attack or accidental). This only applies to untrusted, external sources over which the administrator does not have control (either directly or through endpoint configuration).
=> Security: limit data read from external sources

docs/pages/deployment/pex.rst
Had an incorrect `definitions` field.
=> Docs: fix incorrect PEX example

auth/api/iam/metadata.go, auth/api/iam/metadata_test.go
The default value is true, but better to make it explicit
=> Explicitly support PresentationDefinitionUriSupported

e2e-tests/browser/openid4vp_employeecredential/docker-compose.yml, e2e-tests/browser/openid4vp_employeecredential/main_test.go, e2e-tests/browser/openid4vp_employeecredential/openid4vp.go, e2e-tests/browser/rfc019_selfsigned/main_test.go, e2e-tests/browser/util.go
By letting the verifier and requester use their own node it is a lot easier to figure out what requests are being made
also removes dependencies between tests
=> E2E: employee credential: use 2 nodes to simplify debugging

e2e-tests/oauth-flow/rfc021/do-test.sh, e2e-tests/oauth-flow/rfc021/mysql.yml, e2e-tests/oauth-flow/rfc021/postgres.yml, e2e-tests/oauth-flow/rfc021/run-test.sh, e2e-tests/oauth-flow/rfc021/sqlserver.yml, storage/engine.go
Hopefully fixes instable tests.
Also, e2e tests didn't ultimately fail if one of the tests failed in some circumstances (couldn't create DID due to DB being unavailable).
=> e2e tests: have Nuts containers wait for DB container healthy

docs/pages/deployment/storage.rst, e2e-tests/oauth-flow/rfc021/do-test.sh, e2e-tests/oauth-flow/rfc021/sqlserver.yml
Both were using the same database (`master`) since the database was passed incorrectly.
Fixes https://github.com/nuts-foundation/nuts-node/issues/3111
=> SQL: Fix SQL Server e2e test connection strings

storage/interface.go, storage/mock.go, storage/session_inmemory.go, storage/session_inmemory_test.go, storage/session_redis.go, storage/session_redis_test.go
part of #3063 
I chose this solution over changing `Delete(key string) (interface{}, error)` since the returned interface is always going to be an `[]byte` that still needs to be marshaled to the target object.
=> Add SessionStore.GetAndDelete

auth/api/iam/api.go, auth/api/iam/api_test.go, auth/api/iam/generated.go, auth/api/iam/jar.go, auth/api/iam/jar_test.go, auth/api/iam/metadata.go, auth/api/iam/metadata_test.go, auth/api/iam/openid4vp.go, auth/api/iam/openid4vp_test.go, auth/api/iam/user.go, auth/api/iam/user_test.go, auth/client/iam/client.go, auth/client/iam/client_test.go, auth/client/iam/interface.go, auth/client/iam/mock.go, auth/client/iam/openid4vp.go, auth/client/iam/openid4vp_test.go, auth/oauth/error.go, auth/oauth/types.go, docs/_static/auth/iam.partial.yaml, docs/pages/deployment/oauth.rst, e2e-tests/browser/openid4vp_employeecredential/docker-compose.yml, e2e-tests/browser/rfc019_selfsigned/docker-compose.yml
=> Support request_uri_method=post

auth/api/iam/api.go, auth/api/iam/api_test.go, auth/api/iam/metadata.go, auth/api/iam/metadata_test.go, auth/api/iam/openid4vp.go, auth/api/iam/openid4vp_test.go, auth/api/iam/session.go, auth/api/iam/types.go, auth/api/iam/user.go, auth/api/iam/user_test.go, auth/client/iam/openid4vp.go, auth/oauth/types.go
moved a bunch of constants from `auth/api/iam/types.go` to `auth/oauth/types.go`
removed duplicate and unused constants
=> cleanup oauth constants

auth/services/notary/notary.go, auth/services/notary/notary_test.go, auth/services/oauth/authz_server.go, auth/services/oauth/authz_server_test.go, crypto/crypto.go, crypto/crypto_test.go, crypto/interface.go, crypto/mock.go, crypto/storage/external/client.go, crypto/storage/external/client_test.go, crypto/storage/fs/fs.go, crypto/storage/fs/fs_test.go, crypto/storage/spi/interface.go, crypto/storage/spi/mock.go, crypto/storage/spi/wrapper.go, crypto/storage/spi/wrapper_test.go, crypto/storage/vault/vault.go, crypto/storage/vault/vault_test.go, crypto/test.go, http/cmd/cmd.go, network/network.go, vdr/didweb/manager_test.go
Could lead to dangerous assumptions (key does not exist, so (over)write it).
=> Crypto: let Exists() return an error if one occurs

auth/api/iam/api.go, auth/api/iam/api_test.go, auth/api/iam/openid4vp.go, auth/api/iam/openid4vp_test.go, auth/api/iam/s2s_vptoken.go, auth/api/iam/user.go, auth/api/iam/user_test.go, auth/oauth/types.go
closes #3063 
rewrote nonce validation in `handleAuthorizeResponseSubmission` since it assumed the first VP contained the "correct" nonce and later on did a second validation over all VPs
=> Burn nonce type SessionStore entries after first use

auth/api/iam/api.go, auth/api/iam/api_test.go, auth/api/iam/dpop.go, auth/api/iam/generated.go, auth/api/iam/openid4vp.go, auth/api/iam/openid4vp_test.go, auth/api/iam/session.go, auth/api/iam/user.go, auth/api/iam/user_test.go, auth/client/iam/client.go, auth/client/iam/client_test.go, auth/client/iam/interface.go, auth/client/iam/mock.go, auth/client/iam/openid4vp.go, auth/client/iam/openid4vp_test.go, auth/oauth/types.go, docs/_static/auth/v2.yaml, e2e-tests/browser/client/iam/generated.go
- store `token_endpoint` in session and use this to exchange `authorization_code`. closes #3134 
- replace `/.well-known/openid-configuration` with `/.well-known/oauth-authorization-server`. closes #3135 
- made `authorization_details` in the credential issuance request an object since the full contents are undefined
- increase test coverage
=> Use token endpoint from session

storage/sql_migrations/README.md
Fixes https://github.com/nuts-foundation/nuts-node/issues/3131
=> Storage: update migrations readme

auth/api/iam/dpop_test.go, crypto/crypto.go, crypto/dpop.go, crypto/dpop/dpop.go, crypto/dpop/dpop_test.go, crypto/jwx.go, crypto/jwx_test.go, crypto/memory.go
Initially Crypto was set up to just act on `crypto.Signer`, to support unexportable keys in a separate key vault at some point (meaning the private keys itself are never in the application memory, cryptographic operations are performed in the key vault). I tried implementing Azure Key Vault using this approach, but found that several functions act on the private key assuming it's always in-memory. This PR fixes that.
Note that this only applies to signing, not to encryption: our encryption algorithm of choice (ECIES) isn't supported by Hashicorp Vault/Azure Key Vault. If encryption is a feature we want to retain in combination with secure key storage, RSA keys could be used instead.
=> Crypto: work on crypto.Signer instead of concrete private keys for signing

docs/pages/release_notes.rst, network/dag/state.go, network/network.go, network/network_test.go
closes #3155
similar issued could exist for notifiers registered during configuration for modules, but I did not investigate this considering the scheduled removal of this feature
=> Fix nil defer during handlePrivateTxRetry by starting notifiers last in the network stack

auth/api/iam/api.go, auth/api/iam/api_test.go, auth/api/iam/generated.go, auth/api/iam/openid4vci.go, auth/api/iam/openid4vci_test.go, auth/api/iam/openid4vp.go, auth/api/iam/openid4vp_test.go, auth/api/iam/session.go, auth/api/iam/user.go, auth/client/iam/client.go, auth/client/iam/openid4vp_test.go, docs/_static/auth/iam.partial.yaml, docs/_static/auth/v2.yaml, e2e-tests/browser/client/iam/generated.go
cleanup and merge callbacks. This contains some fixes listed in #3152, but the majority is left for when we have access to a compliant issuer so we can do an end to end test of the flow.
=> Refactor and merge Callbacks

auth/api/iam/generated.go, docs/_static/vcr/vcr_v2.yaml
It breaks code generation in Java. Can be safely deleted, we don't necerassily need it.
=> VCR: Remove @context default value from OAS

auth/api/iam/api.go, auth/api/iam/api_test.go, auth/api/iam/generated.go, auth/auth.go, auth/auth_test.go, auth/client/iam/interface.go, auth/client/iam/mock.go, auth/client/iam/openid4vp.go, auth/client/iam/openid4vp_test.go, docs/_static/auth/v2.yaml, e2e-tests/browser/client/iam/generated.go, e2e-tests/oauth-flow/rfc021/do-test.sh, e2e-tests/oauth-flow/rfc021/node-A/presentationexchangemapping.json, vcr/credential/validator.go, vcr/credential/validator_test.go, vcr/holder/interface.go, vcr/holder/presenter.go, vcr/holder/presenter_test.go, vcr/pe/presentation_definition.go, vcr/pe/presentation_definition_test.go, vcr/verifier/signature_verifier_test.go, vcr/verifier/verifier.go, vcr/verifier/verifier_test.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/3198
TODO:
=> Auth v2: allow additional credentials in RequestServiceAccessToken

storage/sql_migrations/003_did.sql, vdr/didweb/manager.go, vdr/didweb/manager_test.go, vdr/sql/did_document_test.go, vdr/sql/verification_method.go, vdr/sql/verification_method_test.go
based upon #3196
The nuts and web method have different requirements on key types (encryption). Also when supporting encryption in the future, they should be RSA keys. This means that not all verification methods can be used for all key usage.
This PR adds some flags per VerificationMethod.
partial diff: https://github.com/nuts-foundation/nuts-node/compare/feature/3191_did_subject...feature/extend_did_vm
=> Extend DID verification method model with key usage

auth/api/iam/api.go, auth/api/iam/api_test.go, auth/api/iam/generated.go, auth/api/iam/jar.go, auth/api/iam/jar_test.go, auth/api/iam/metadata.go, auth/api/iam/metadata_test.go, auth/api/iam/openid4vci.go, auth/api/iam/openid4vci_test.go, auth/api/iam/openid4vp.go, auth/api/iam/openid4vp_test.go, auth/api/iam/session.go, auth/api/iam/user.go, auth/api/iam/user_test.go, auth/client/iam/client.go, auth/client/iam/interface.go, auth/client/iam/mock.go, auth/client/iam/openid4vp.go, auth/client/iam/openid4vp_test.go, core/to/util.go, docs/_static/auth/iam.partial.yaml, e2e-tests/browser/client/iam/generated.go, e2e-tests/browser/openid4vp_employeecredential/run-test.sh, http/client/caching.go, http/client/client.go, http/client/client_test.go
To support other DID methods. Changes:
- Changed the issuer URL to contain the complete DID instead of just the did:web ID part of the DID
- Changed the path of the issuer URL to `/oauth2` instead of `/iam`, to have it align with the other OAuth endpoints, and to explicitly decouple it from the did:web DID.
This is also preparation work for decoupling did:web from OAuth2; which will require the caller to provide the AS url in (near) future.
=> Auth v2: change OAuth2 issuer URL from /iam to /oauth2

auth/api/iam/api.go, auth/api/iam/api_test.go, auth/api/iam/generated.go, auth/api/iam/jar.go, auth/api/iam/jar_mock.go, auth/api/iam/jar_test.go, auth/api/iam/openid4vci.go, auth/api/iam/openid4vci_test.go, auth/api/iam/openid4vp.go, auth/api/iam/openid4vp_test.go, auth/api/iam/s2s_vptoken.go, auth/api/iam/s2s_vptoken_test.go, auth/api/iam/user.go, auth/api/iam/user_test.go, auth/api/iam/validation.go, auth/client/iam/interface.go, auth/client/iam/mock.go, auth/client/iam/openid4vp.go, auth/client/iam/openid4vp_test.go, docs/_static/auth/v2.yaml, e2e-tests/browser/client/iam/generated.go, e2e-tests/browser/openid4vp_employeecredential/openid4vp.go, e2e-tests/oauth-flow/openid4vp/do-test.sh, e2e-tests/oauth-flow/rfc021/do-test.sh, makefile, vdr/api/v2/generated.go
To support other DID methods. Next step is to change audience from AS's DID to AS URL.
@JorisHeadease @rolandgroen this also changes the OpenID4VCI's `issuer` parameter in `RequestCredential()` from the DID to issuer URL.
=> IAM: Provide authorization_server in access token requests 

auth/api/iam/api.go, vcr/issuer/issuer_test.go, vcr/revocation/statuslist2021_issuer.go, vcr/revocation/statuslist2021_issuer_test.go, vcr/revocation/types.go, vcr/revocation/types_test.go, vcr/vcr.go, vcr/verifier/verifier_test.go
To support other DID methods in future (`did:tdw`), the StatusList2021 issuer can't use `didweb.DIDtoURL` to determine the URL the StatusCredential lives on. This PR changes it to more explicit configuration.
Note: should we lookup the statuslist through `(DID, page)` combination instead? Since that also supports migration scenarios?
=> VCR: StatusList2021 forward compatibility for other DID methods

auth/api/iam/api.go, auth/api/iam/api_test.go
fixes #3203 
also changed existing test since the error comes from the own node, not from the other node.
=> map NoMatchingCredentials error to 419 status code

vdr/didnuts/ambassador_test.go, vdr/didnuts/creator.go, vdr/didnuts/creator_test.go, vdr/didnuts/manager.go, vdr/didnuts/manager_test.go, vdr/didweb/manager.go, vdr/didweb/manager_test.go, vdr/vdr.go
part of #3208
This PR adds the implementation of the SubjectManager to did:nuts and did:web. They are not yet called by anyone.
=> VDR refactor part trois: implement SubjectManager interface for nuts and web

auth/api/iam/api.go, auth/api/iam/api_test.go, auth/api/iam/openid4vp.go, auth/api/iam/openid4vp_test.go, auth/api/iam/s2s_vptoken.go, auth/api/iam/s2s_vptoken_test.go, auth/api/iam/validation.go, policy/interface.go, policy/local.go, policy/local_test.go, policy/mock.go
Kept in API endpoint for consistency with other `/oauth2` endpoints, but it's not needed in anyways so I removed it from the call stack.
=> PDP: Don't pass DID, not required

auth/api/iam/api_test.go, auth/api/iam/dpop_test.go, auth/api/iam/jar_test.go, auth/api/iam/user_test.go, auth/services/selfsigned/test/generate_test.go, crypto/interface.go, crypto/jwx.go, crypto/jwx_test.go, crypto/memory.go, crypto/memory_test.go, crypto/mock.go, crypto/test.go, e2e-tests/oauth-flow/rfc021/sqlserver.yml, network/dag/signing.go, network/dag/signing_test.go, network/dag/test.go, network/dag/verifier_test.go, network/network_integration_test.go, network/network_test.go, vcr/ambassador_test.go, vcr/issuer/issuer.go, vcr/issuer/keyresolver_test.go, vcr/issuer/openid_test.go, vcr/test/test.go, vcr/verifier/signature_verifier_test.go, vcr/verifier/verifier_test.go, vdr/didnuts/ambassador_test.go, vdr/didnuts/manager_test.go, vdr/vdr_test.go
This PR is to prepare for the separation of `KID` (frontend) and `KeyName/Version` (backend). Two main things:
- Change signature of SignJWS and SignJWT so they are 'public' facing and always work on the kid.
- Reduce the usage of the TestKey for internal purposes:
- the TestKey has a kid which is not always required
- used real keys from the `memoryKeyStore` so key and keyStore are actually consistent in test.
- found some dead code.
=> change SignJWS and SignJWT signatures

cmd/root.go, docs/pages/release_notes.rst, http/cmd/cmd.go, http/cmd/cmd_test.go, http/engine.go, http/engine_test.go
Already designated legacy, for v6 removed.
=> remove legacy API auth bearer token

auth/api/iam/api.go, auth/api/iam/api_test.go
DID creation/resolving already supports having a Nuts `url` with non-root/non-empty path (e.g. `/nuts`), but the metadata endpoints returned URLs without the configured path. This fixes the metadata to contains the configured path.
=> Auth v2: support non-root base URL in OAuth2 metadata

auth/api/iam/api.go, auth/api/iam/api_test.go, auth/api/iam/jar.go, auth/api/iam/jar_mock.go, auth/api/iam/jar_test.go, auth/api/iam/metadata.go, auth/api/iam/metadata_test.go, auth/api/iam/openid4vp.go
For forwards compatibility with other DID methods, and easier (future) enabling/disabling of Authorization Endpoint in metadata.
=> Auth: have jar.Parse() take metadata instead of DID

auth/api/iam/api_test.go, auth/api/iam/openid4vp.go, auth/api/iam/openid4vp_test.go
When initiating OpenID4VP through Authorized Code Flow. Check can't be done at this point, since it requires dereferencing the client_id into OAuth2 Authorization Server metadata, which is only possible for `did:web` DIDs.
It is also unnecessary: the same check can be done in future when the client retrieves the OpenID4VP authorization request (which uses JAR), since it then provides its metadata (which can contain the supported client ID schemes property).
=> Auth: remove check wallet supports 'did' in supported_client_auth_methods

docs/pages/release_notes.rst
v5.4.8 was only on the V5.4 branch, so fixed now
v5.4.9 addition will be back ported to V5.4 before the release
=> Release notes v5.4.8 and v5.4.9

auth/services/oauth/authz_server.go, crypto/interface.go
aligned the message with v6. 
In V6 `Exists` also returns an error clarifying this even further.
=> v5.4: fix error message in private key existence check

auth/api/iam/api_test.go, auth/api/iam/openid4vp.go, auth/api/iam/openid4vp_test.go, auth/client/iam/openid4vp.go, auth/client/iam/openid4vp_test.go, vcr/holder/interface.go, vcr/holder/memory_wallet.go, vcr/holder/mock.go, vcr/holder/presenter.go, vcr/holder/presenter_test.go, vcr/holder/sql_wallet.go
To aid selection of DID based on Presentation Definition (required by DID -> subject refactor).
Note that this doesn't actually allow a submission with multiple VPs, just selecting the right one.
=> VCR: Prepare wallet to perform on multiple DIDs

development/dev-image/Dockerfile, development/dev-image/entrypoint.sh, docs/pages/deployment/docker.rst
This PR contains 3 changes to the `entrypoint.sh` script. I'm happy to only merge the ones that make sense
- commit 1: fix script to first [create a persistent tunnel before hosting](https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/faq#how-can-i-create-a-persistent-tunnel) it. Calling `devtunnel host` without a `TUNNEL_ID` should create a temporary tunnel, but the behavior seems inconsistent as the tunnel is not always deleted. This commit should fix the inconsistency and always persist the created tunnel.
- commit 2: move tunnel variables from `/devtunnel/...` to `~/config/nuts-devtunnel`. It is likely that the `./config` folder is mounted anyway, so this saves a volume mount. However, the `config` directory inside the `nuts-node` is defined relative to the configured …
=> Fix dev image persistent tunnel

discovery/api/server/client/http.go, discovery/api/v1/api.go, discovery/api/v1/api_test.go, discovery/api/v1/generated.go, discovery/client.go, discovery/client_test.go, discovery/interface.go, discovery/mock.go, discovery/module.go, discovery/module_test.go, discovery/store.go, discovery/store_test.go, discovery/test.go, docs/_static/discovery/v1.yaml, e2e-tests/discovery/run-test.sh, go.mod, storage/sql_migrations/004_discoveryservice_client_registration.sql, vdr/didsubject/did.go, vdr/didsubject/management.go, vdr/didsubject/manager.go
fixes #3265 
This change lets the Discovery Service client manage Subjects rather than individual DIDs.
During activation/refresh it tries to register every DID in a subject. If 1 DID is successfully registered on the service, the operation is considered successful and a refresh is scheduled at 45% of the max_presentation_validitiy. This means that if a second DID fails that should not fail, it will not be retried until the next scheduled refresh. So it will be retried again at 90% of max_presentation_validity. If everything fails, the refresh/activation will be retried at the next configured refresh interval.
=> Discovery Service: change client to manage subjects, not DIDs

vdr/didsubject/manager.go
they should be equal to `next.ID`, which does not exist until `SqlDIDDocumentManager.CreateOrUpdate` is called (this does set `DIDDocumentID` on all services and vms)
=> remove incorrect value

auth/api/auth/v1/api_test.go, auth/api/iam/access_token.go, auth/api/iam/api.go, auth/api/iam/api_test.go, auth/api/iam/dpop.go, auth/api/iam/dpop_test.go, auth/api/iam/generated.go, auth/api/iam/jar.go, auth/api/iam/openid4vci_test.go, auth/client/iam/openid4vp.go, auth/oauth/test.go, auth/oauth/types.go, auth/oauth/types_test.go, crypto/dpop.go, crypto/dpop/dpop.go, crypto/dpop/dpop_test.go, docs/_static/auth/iam.partial.yaml, docs/_static/auth/v2.yaml, e2e-tests/browser/client/iam/generated.go, e2e-tests/oauth-flow/openid4vp/do-test.sh, e2e-tests/oauth-flow/rfc021/do-test.sh, e2e-tests/util.sh, vcr/holder/openid_test.go
closes #3314 
depends on #3333 
The access token request now also returns a kid that is used as path param.
=> Replace did param in DPoP proof API to kid

auth/api/iam/generated.go, auth/client/iam/openid4vp.go, discovery/api/v1/api.go, discovery/api/v1/api_test.go, discovery/api/v1/generated.go, discovery/api/v1/types.go, discovery/client.go, discovery/client_test.go, discovery/interface.go, discovery/mock.go, discovery/module.go, discovery/module_test.go, discovery/store.go, discovery/store_test.go, discovery/test.go, docs/_static/discovery/v1.yaml, e2e-tests/browser/client/iam/generated.go, storage/sql_migrations/004_discoveryservice_client_registration.sql, vcr/assets/assets/contexts/nuts.ldjson, vcr/credential/types.go, vcr/credential/util.go, vcr/credential/util_test.go, vcr/pe/presentation_definition.go, vcr/verifier/verifier.go
closes #3353 
closes #3352 
also returns the params with a search.
=> allow for additional parameters when activating discovery service

network/dag/interface.go, network/dag/mock.go, network/dag/state.go, network/network.go, network/network_test.go
fixes #3355 
from logs:
```
level=debug msg="Received 0 new transaction references via Gossip from peer" 
level=debug msg="XOR is different from peer but Gossip contained no new transactions"
level=debug msg="Requesting state from peer" 
```
The migration happens while the network is offline, so the changes aren't gossiped to peers. Should be fine though
=> Add state.Configure to load state/trees before migrations are run

network/dag/consistency.go, network/dag/treestore.go
part of #3355 
the `xorTreeRepair` fixes the `state.xorTree` issues in memory, but they are not written to disk. The next network transaction will result in the fix being stored, but this might take a while if transaction volume is low. (Such as during testing)
backport to v5
=> write DAG XOR tree consistency fixes to disk

network/dag/consistency.go, network/dag/treestore.go
does this need a patch release, or should we just leave it in this branch to be released together with some other fix?
=> backport - write DAG XOR tree consistency fixes to disk

audit/test.go, crypto/crypto_test.go, crypto/jwx_test.go, http/tokenV2/middleware_test.go, vcr/holder/sql_wallet.go, vcr/holder/sql_wallet_test.go, vcr/issuer/openid_test.go, vcr/test/openid4vci_integration_test.go
fixes #3362 
`wallet.List()` now only returns non-revoked, non-expired credentials. Trust and signatures are not checked. Trust checking is done via PEX and signatures are checked at upload time.
=> have wallet.List() only return non-revoked/non-expired credentials

storage/engine.go, storage/engine_test.go
closes #2987
`/health` of a health node:
```
{
"status": "UP",
"details": {
"crypto.filesystem": {
"status": "UP"
},
"network.auth_config": {
"status": "UP"
},
"network.tls": {
"status": "UP"
},
"pki.crl": {
"status": "UP"
},
"storage.sql": {
"status": "UP"
}
}
}
```
=> Add sql to /health

auth/api/iam/api.go, auth/api/iam/api_test.go, auth/api/iam/openid4vp.go, auth/api/iam/openid4vp_test.go, auth/client/iam/openid4vp.go, auth/client/iam/openid4vp_test.go, discovery/client.go, discovery/client_test.go, discovery/interface.go, discovery/module.go, discovery/module_test.go, vcr/holder/presenter.go, vcr/holder/presenter_test.go, vcr/holder/sql_wallet.go, vcr/pe/presentation_definition.go, vcr/pe/presentation_definition_test.go, vcr/pe/presentation_submission.go, vcr/pe/presentation_submission_test.go, vcr/pe/submission_requirement.go, vcr/pe/test/pd_jsonld.json, vcr/pe/test/pd_jsonld_jwt.json, vcr/pe/test/pd_jsonld_jwt_pick.json, vcr/pe/test/pd_jwt.json, vcr/pe/types.go
closes #3007 
closes #3025 
I changed the PEX implementation so it always returns a `errors.Join(pe.ErrNoCredentials, reason)` when there's no match. For RFC021 this is returned as is. For the discovery service this is placed in trace logging to get details when needed.
=> pass matcher details from PEX in error for non-matches

auth/api/iam/api_test.go, auth/api/iam/openid4vp.go, auth/api/iam/openid4vp_test.go, auth/client/iam/openid4vp.go, auth/client/iam/openid4vp_test.go, go.mod, vcr/credential/util.go, vcr/credential/util_test.go, vcr/holder/interface.go, vcr/holder/memory_wallet.go, vcr/holder/mock.go, vcr/holder/presenter.go, vcr/holder/presenter_test.go, vcr/holder/sql_wallet.go
Closes #3337
This PR only makes sure the holder uses a DID method in the RFC021 flow that is supported by the other side. All VCs used must also have a compliant issuer/credentialSubject.id.
=> Have s2s flow take verifier supported DID methods into account

storage/sql_migrations/003_did.sql
fix is either this or remove the todos without making fields `not null`
=> Fixs todos in SQL migration file

storage/orm/did.go, storage/orm/did_document.go, storage/orm/did_document_test.go, vdr/didsubject/did.go, vdr/didsubject/did_document.go, vdr/didsubject/did_document_test.go, vdr/didsubject/did_test.go, vdr/didsubject/manager.go, vdr/didsubject/manager_test.go
Closes #3381
For now we'll just allow VCs to be embedded in a VP by the credentialSubject.id. No cross-did possibilities using AlsoKnownAs
=> remove AlsoKnownAs from ORM

discovery/api/server/api.go, discovery/client.go, discovery/client_test.go, discovery/definition.go, discovery/interface.go, discovery/module.go, discovery/module_test.go, discovery/test.go, docs/pages/deployment/discovery.rst
closes #3383
known under JSON as `did_methods`. Direct activation and deactivation fails with `ErrDIDMethodsNotSupported`. If this error occurs in a refresh, the registration is removed.
=> add DIDMethods config param to discovery service

auth/api/iam/generated.go, docs/_static/auth/v2.yaml
builds on #3386
removed experimental label of all APIs except the user and openid4vci flow
moved the openid4vci flow up in the document so it is grouped with the other `/internal/auth/v2/{subjectID}/...` paths making it easier to scan the document.
**should we also change:**
`/internal/auth/v2/{kid}/dpop` -> `/internal/auth/v2/dpop/{kid}` 
`/internal/auth/v2/dpop_validate` -> `/internal/auth/v2/dpop/validate`
=> Mark user flow and openid4vci flow experimental

auth/api/iam/api.go
fixes #3273 
one of those things our tests don't catch. There's a separate issue for that somewhere. Tested by hand for now.
=> enable statuscode handler middleware for auth v2

discovery/store.go, e2e-tests/oauth-flow/rfc021/do-test.sh, e2e-tests/oauth-flow/rfc021/docker-compose.yml, e2e-tests/oauth-flow/rfc021/node-A/nuts.yaml, e2e-tests/oauth-flow/rfc021/node-B/nuts.yaml, e2e-tests/oauth-flow/rfc021/shared/discovery/definition.json, vcr/revocation/statuslist2021_issuer.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/3393
=> SQL: Fix locking with MS SQL Server

discovery/client.go, discovery/client_test.go, discovery/module.go, discovery/module_test.go, discovery/test.go, e2e-tests/discovery/run-test.sh
fixes #3405 
tests and logic required DiscoveryRegistrationCredential to be defined in Presentation Definition of discovery service. This was not the idea, it should always be present. Now it's allowed to not be in the PD, if it's in the PD that's fine as well. That way you can require certain services to be included.
=> allow for registration credential if not defined in PD

e2e-tests/oauth-flow/openid4vp/run-test.sh
fixes #3299 
re-enabling root did:web DIDs will not be part of the 6.0 release. It can be added in a minor, then the test can be fixed properly.
=> disable did:web root e2e-test

cmd/root.go, docs/_static/vcr/vcr_v2.yaml, e2e-tests/browser/openid4vp_employeecredential/main_test.go, e2e-tests/browser/rfc019_selfsigned/main_test.go, e2e-tests/browser/util.go, e2e-tests/discovery/run-test.sh, e2e-tests/oauth-flow/openid4vp/do-test.sh, e2e-tests/oauth-flow/rfc021/do-test.sh, vcr/api/vcr/v2/api.go, vcr/api/vcr/v2/api_test.go, vcr/api/vcr/v2/client.go, vcr/api/vcr/v2/generated.go
closes #3413 
Changed API from using DID path to subject.
Added checks:
- subject in path must exist
- subject in path must own credentialSubject.ID
- credential must be valid (without trust): sig, not revoked, not expired.
=> added checks to VCR.Load()

discovery/client.go, discovery/client_test.go, discovery/store.go, e2e-tests/oauth-flow/rfc021/do-test.sh
Was a "zero" `time.Time` (0000-00-00 00:00:00), which lead to a (very) large negative int, which didn't fit in the INT (4 bytes) type of MS SQL Server. Didn't find it earlier, since the check in the e2e test was incorrect.
```
{"error":"mssql: Arithmetic overflow error converting expression to data type int.","level":"warning","module":"Storage","msg":"Query failed (took 8.809369ms): UPDATE \"discovery_presentation_refresh\" SET \"service_id\"='test:SharedCarePlanning2024',\"subject_id\"='zbj-tst',\"next_refresh\"=-62135596800,\"parameters\"='{\"authServerURL\":\"...\"}' WHERE \"service_id\" = 'test:SharedCarePlanning2024' AND \"subject_id\" = 'zbj-tst'","time":"2024-09-26T17:02:51Z"}
```
=> Discovery: fix 'as soon as possible' refresh timestamp

discovery/api/v1/api.go, discovery/api/v1/api_test.go, discovery/api/v1/generated.go, discovery/api/v1/types.go, discovery/client.go, discovery/client_test.go, discovery/interface.go, discovery/mock.go, discovery/module.go, discovery/module_test.go, discovery/store.go, discovery/store_test.go, docs/_static/discovery/v1.yaml, docs/pages/deployment/discovery.rst, e2e-tests/discovery/run-test.sh, storage/sql_migrations/008_discoveryservice_client_error.sql
closes #3408 
- activation through the API is now a fail/success API, no magic is done at a later point if it fails.
- the refresh adds `presentationRefreshError` records if it fails for a candidate.
- refresh success or activation through the API clears the `presentationRefreshError` records.
- The `getServiceActivation` API returns an additional `status` and `error` field.
=> Alter discovery activation

docs/index.rst, docs/pages/deployment/migration.rst, docs/pages/integrating/version-incompatibilities.rst, docs/pages/release_notes.rst
This probably doesn't fit under `Version Incompatibilities`. We need to move it elsewhere, or rename the page and make Version Incompatibilities a subsection...
=> add migration notes to docs

e2e-tests/oauth-flow/rfc021/do-test.sh, vcr/revocation/statuslist2021_issuer.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/3451
=> VCR: Fix broken First() operation which breaks retrieving StatusList credential on MS SQL Server

vcr/revocation/statuslist2021_issuer.go
Fixes:
```
{"detail":"mssql: Invalid column name 'subject_id'.","status":500,"title":"StatusList failed"}
```
Caused by:
```
SELECT * FROM status_list_entry WITH (UPDLOCK, ROWLOCK) WHERE subject_id =
```
Also fixes a `count(*) > 0` leftover, which isn't supported by all databases (at least not by MS SQL Server).
There isn't really a good way to test this, since it only triggers when the StatusList credential expires (after 24h).
=> VCR: fix MS SQL Server status list refresh

discovery/store.go, discovery/store_test.go
=> prevent duplicate results in discovery search

cmd/root.go, discovery/client.go, discovery/client_test.go, discovery/module.go, discovery/module_test.go
=> stop refreshing when a subject has no active DID Documents

discovery/api/server/client/http.go, discovery/api/server/client/http_test.go
fixes #3471 
when the discovery server returns problem details, the client will try to parse. If successful, it'll pass on the error.
=> pass problem details when discovery service returns them

storage/engine.go, storage/engine_test.go
closes #3470 
I'm not convinced this is actually an improvement. The 2 most likely errors are
```
level=fatal msg="Could not start the server" error="unable to create datadir (dir=./data): mkdir ./data: read-only file system"
```
and
```
level=fatal msg="Could not start the server" error="unable to configure Storage: open data/rw-access-test-file: read-only file system"
```
Both are pointing to read-only file system issue, but the real issue is an unprivileged user.
The unprivileged user is what also caused `"failed to initialize database, got error unable to open database file: out of memory (14)"` that resulted in this issue. This check does prevent the OOM error from ever occurring again though.
I don't see how to clarify the error without adding a very long error description since we …
=> Check RW permissions in datadir

discovery/client.go, discovery/client_test.go, discovery/module.go, discovery/module_test.go, discovery/store.go, discovery/store_test.go, storage/sql_migrations/010_discoverypresentation_validation.sql
fixes #3468 
any did:web or revocation downtime will not block discovery entries. Entries are invalid until VerifyVP succeeds at least once. After that a revocation checker will remove entries when a VC is revoked.
Only downside is a full table scan on presentation records every 10 minutes. If this becomes a problem (eg > 100k results) then `Search` has to verify the VPs and delete entries as a side effect.... (or some elaborate eventing thing from revocationList to discovery service.)
=> move discovery VP validation to background process to prevent errors

discovery/client.go, discovery/client_test.go, discovery/module.go, discovery/module_test.go, discovery/test.go, docs/pages/deployment/discovery.rst, e2e-tests/discovery/definitions/definition.json
closes #3298 
`DiscoveryRegistrationCredential` is now required in PEX to do anything useful. Other remarks are pushed to RFC branch
=> require DiscoveryRegistrationCredential in PEX

docs/_static/auth/v2.yaml
=> fix tokenIntrospection response description

crypto/jwx.go, crypto/jwx_test.go, crypto/memory.go
=> SignJWS: always add kid to header

auth/client/iam/client.go, auth/services/oauth/relying_party.go, core/http_client.go, core/http_client_test.go, crypto/storage/external/client.go, didman/api/v1/client.go, docs/pages/deployment/security-considerations.rst, http/client/caching.go, http/client/client.go, http/client/client_test.go, http/engine.go, network/api/v1/client.go, pki/denylist.go, pki/validator.go, vcr/api/vcr/v2/client.go, vcr/openid4vci/identifiers.go, vcr/openid4vci/issuer_client.go, vcr/revocation/statuslist2021_verifier.go, vcr/test/openid4vci_integration_test.go, vdr/api/v1/client.go, vdr/api/v2/client.go, vdr/didweb/web.go, vdr/didweb/web_test.go
fixes outcome from Elevation Of Privilege.
checked all creations of `http.Client` and replaced with `client.New`, `client.NewWithCache` or `client.NewWithTLSConfig`.
Also connected the limitreader to the strictClient.
=> secure outgoing http client with max connections

discovery/store.go, discovery/store_test.go
=> fix duplicate search results for wildcard param

README.rst, crypto/cmd/cmd_test.go, docs/pages/deployment/configuration.rst, docs/pages/deployment/storage.rst, e2e-tests/nuts-network/direct-wan/node-A/nuts.yaml, e2e-tests/nuts-network/direct-wan/node-B/nuts.yaml, e2e-tests/nuts-network/private-transactions/node-A/nuts.yaml, e2e-tests/nuts-network/private-transactions/node-B/nuts.yaml, e2e-tests/nuts-network/ssl-offloading/haproxy/node-A/nuts.yaml, e2e-tests/nuts-network/ssl-offloading/haproxy/node-B/nuts.yaml, e2e-tests/nuts-network/ssl-offloading/nginx/node-A/nuts.yaml, e2e-tests/nuts-network/ssl-offloading/nginx/node-B/nuts.yaml, e2e-tests/nuts-network/ssl-pass-through/node-A/nuts.yaml, e2e-tests/nuts-network/ssl-pass-through/node-B/nuts.yaml, e2e-tests/openid4vci/issuer-initiated/node-A/nuts.yaml, e2e-tests/openid4vci/issuer-initiated/node-B/nuts.yaml, e2e-tests/openid4vci/network-issuance/node-A/nuts.yaml, e2e-tests/openid4vci/network-issuance/node-B/nuts.yaml, e2e-tests/ops/create-subject/docker-compose.yml, e2e-tests/ops/key-rotation/node-A/nuts.yaml, e2e-tests/ops/key-rotation/node-B/nuts.yaml, e2e-tests/storage/redis/node-A/nuts.yaml, e2e-tests/storage/redis/node-B/nuts.yaml, e2e-tests/storage/vault/nuts.yaml, main_test.go, storage/engine.go, storage/engine_test.go
strictmode should have minimal magic.
This should also prevent accidental migration to a SQLite DB on production environments
=> Require SQL connection string in strictmode

.github/workflows/codeql-analysis-cron-schedule.yml, .github/workflows/codeql-analysis.yml
=> Add gh action for CodeQL schedule

network/dag/notifier.go
=> backport: optimize network event notification retry at startup

docs/index.rst, docs/pages/deployment/certificates.rst, docs/pages/deployment/policy.rst, pki/interface.go, pki/validator.go, pki/validator_test.go
closes #3528 
changed the accepted errors list from fail open to fail closed
=> PKI Valdiator always fails on unknown CAs

charts/nuts-node/Chart.yaml
The latest changes are not available when pulling the `https://nuts-foundation.github.io/nuts-node/` repo. The version listed seems from a commit way before (16-6-'23) the latest changes:
```bash
$ helm search repo nuts-repo
NAME                     	CHART VERSION	APP VERSION	DESCRIPTION                          
nuts-repo/nuts-node-chart	0.0.3        	0.0.1      	A NUTS node Helm chart for Kubernetes
```
This PR bumps the version.
=> Nuts chart seems outdated: update chart version to 0.0.4

crypto/storage/vault/vault.go, crypto/storage/vault/vault_test.go, docs/pages/release_notes.rst
=> fix vault key path/key

vcr/assets/assets/default.index.yaml, vcr/vcr_test.go
=> add index for auth creds

cmd/root_test.go
a test kept creating `./cmd/data`
=> Prevent data dir from being created in cmd/

auth/auth.go, auth/auth_test.go, auth/interface.go
Allowing credentials to be issued from it.
This is probably not the right solution, since the actual issue is that `didmethods` indicates 2 things:
- DIDs the Nuts node creates for its subjects
- DID methods it accepts when other parties present credentials
These should probably be 2 lists. The 2nd list could actually be all supported DID methods (nuts, web, x509, jwk, key) minus those we can't resolve if not configured properly (nuts).
@woutslakhorst ?
=> Support did:x509 in Authorization Server metadata

auth/api/iam/api.go, auth/api/iam/api_test.go, storage/engine.go, storage/interface.go, storage/mock.go, storage/session.go, storage/session_inmemory.go, storage/session_inmemory_test.go, storage/session_memcached.go, storage/session_redis.go, storage/session_redis_test.go, storage/test.go
Cache access tokens per request. Subsequent requests are fulfilled from cache.
Added SessionOption to allow for custom `ttl` on session store.
Only implemented for `auth.iam`, not for `auth/v1`
closes #3552
=> Cache access tokens client side

test/pki/test.go, vcr/verifier/signature_verifier_test.go, vcr/verifier/verifier_test.go, vdr/didx509/resolver.go, vdr/didx509/resolver_test.go, vdr/didx509/x509_utils.go, vdr/didx509/x509_utils_test.go
Fixes #3596
Also deduplicates test code
=> did:x509: x5c claim is DER base64, not PEM

docs/_static/vdr/v1.yaml, docs/pages/release_notes.rst, vdr/api/v1/api.go, vdr/api/v1/api_test.go
fixes #3610 
body is now completely ignored. Changed API spec to reflect this.
=> fix VDR V1 CreateDID passing KeyFlags

docs/_static/vdr/v1.yaml, docs/pages/release_notes.rst, vdr/api/v1/api.go, vdr/api/v1/api_test.go
=> backport fix vdr v1 CreateDID KeyFlags

auth/test.go, docs/pages/deployment/certificates.rst, network/network_test.go, network/transport/grpc/config.go, network/transport/grpc/config_test.go, network/transport/grpc/connection_manager_test.go, pki/interface.go, pki/mock.go, pki/pki.go, pki/pki_test.go, pki/validator.go, pki/validator_test.go, vcr/verifier/signature_verifier_test.go, vdr/didx509/resolver.go, vdr/didx509/resolver_test.go, vdr/vdr.go
I've updated some go docs and comments to clarify that the pki engine is only a CRL checker, not a trust manager.
Since trust in the certificate chain must be validated externally (prior to checking the CRLs), we can assume that all presented certificates are part of trusted certificates chains and can be added to the CRL/CA lists at runtime. This simplifies the usage of the PKI engine a bit and closes #3583.
`PKI.CreateTLSConfig()` returns a `tls.Config` that contains the truststore that is in the nuts.yaml config. Added clarification that this must not be replaced the internal truststore of the engine. This method only exists here to set the CRL checker on the `tls.Config.VerifyPeerCertificate`.
**Currently the CRLs are checked by the did:x509 resolver that, I think, does not know if …
=> Add CAs/CRLs to the PKI engine at runtime

e2e-tests/clustering/memcached/run-test.sh, e2e-tests/clustering/redis/run-test.sh, e2e-tests/oauth-flow/rfc021/do-test.sh
The parameter doesn't exist any more.
=> e2e tests: remove client_id from RFC021 (is derived from subject in URL)

storage/session_memcached_test.go
fixes race condition
```
==================
WARNING: DATA RACE
Write at 0x00c000114ca0 by goroutine 797:
github.com/daangn/minimemcached.(*server).close()
/home/circleci/go/pkg/mod/github.com/daangn/minimemcached@v1.2.0/server.go:27 +0xc4
github.com/daangn/minimemcached.(*MiniMemcached).Close()
/home/circleci/go/pkg/mod/github.com/daangn/minimemcached@v1.2.0/minimemcached.go:90 +0x77
github.com/nuts-foundation/nuts-node/storage.memcachedTestServer.func1()
/home/circleci/project/storage/session_memcached_test.go:180 +0x2e
testing.(*common).Cleanup.func1()
/usr/local/go/src/testing/testing.go:1176 +0x179
testing.(*common).runCleanup()
/usr/local/go/src/testing/testing.go:1354 +0x261
testing.tRunner.func2()
/usr/local/go/src/testing/testing.go:1684 +0x50
runtime.deferreturn() …
```
=> Remove useless test to fix data race

.circleci/config.yml, auth/auth.go, auth/services/oauth/relying_party.go, vcr/credential/resolver.go, vcr/credential/resolver_test.go, vcr/credential/types.go, vcr/credential/validator.go, vcr/credential/validator_test.go, vcr/issuer/issuer.go, vcr/issuer/issuer_test.go, vcr/test/credentials.go, vcr/vcr.go, vcr/verifier/verifier.go, vcr/verifier/verifier_test.go, vdr/didx509/resolver.go
=> add validator for x509 credential attributes

docs/pages/deployment/discovery.rst
it was unclear how a registration param matches a PEX constraint.
=> update registrationParam to pex mapping

.github/workflows/govulncheck-cron-schedule.yaml, .github/workflows/govulncheck.yaml
part of #3629 
WIP, but need to deploy to master to test
=> Add scheduled govulncheck

.github/workflows/e2e-tests.yaml
the e2e tests occasionally fail because the cleanup step that removes the container fails. This addition should make the action succeed even if the cleanup action fails. cleanup will be performed on the next run
=> E2E: action doesn't fail when the container cleanup step fails

.github/workflows/e2e-tests.yaml, Dockerfile, go.mod
=> Add patch version to go.mod for 'Scheduled govulncheck'

docs/pages/development/2-releasing.rst
closes #3629 
might not be te best place to document this, so open for suggestions
=> Document scheduled actions updates for new releases

.github/workflows/e2e-tests.yaml, .github/workflows/govulncheck.yaml, Dockerfile, go.mod, go.sum
part of #3629 
merge after slack notifications are confirmed to work
=> V5.4 fix vulnerabilities

Dockerfile, docs/pages/release_notes.rst, go.mod
=> update minimal go version to 1.23.5 and cleanup dockerfile

docs/_static/auth/v2.yaml
examples on the properties are shown as json:
```
{
"token": "spnhVHZ4IFVvuNrpflVaB1A7P3A2xZ7G_a8gF_SHMynYSA"
}
```
which is confusing when using `Content-Type: application/x-www-form-urlencoded`
Moving the example to the schema becomes:
```
token=spnhVHZ4IFVvuNrpflVaB1A7P3A2xZ7G_a8gF_SHMynYSA
```
=> OAPI update introspection example

auth/api/iam/user.go, auth/api/iam/user_test.go, auth/client/iam/openid4vp_test.go, docs/_static/auth/v2.yaml, e2e-tests/browser/openid4vp_employeecredential/config/policy/zorgtoepassing.json, e2e-tests/clustering/memcached/run-test.sh, e2e-tests/clustering/redis/run-test.sh, e2e-tests/clustering/shared/presentationexchangemapping.json, e2e-tests/oauth-flow/rfc021/do-test.sh, e2e-tests/oauth-flow/rfc021/node-A/presentationexchangemapping.json, http/user/session.go, vcr/pe/presentation_definition_test.go
We used an `EmployeeCredential` and `NutsEmployeeCredential`. Both use the `https://nuts.nl/credentials/v1` context that only contains the `NutsEmployeeCredential`. 
My understanding is that there was a proposal to add the `EmployeeCredential`, but the idea was abandoned because the same could be achieved with the `NutsEmployeeCredential`.
I've tested this against v6.0.8 and there are no breaking changes except possibly for the browser/openid4vp_employeecredential e2e test. This uses the /request-user-access-token flow that is under a feature flag, so a breaking change is allowed.
backport to V6.0 to fix the documentation examples
=> Rename EmployeeCredential to NutsEmployeeCredential

auth/api/iam/user.go, auth/api/iam/user_test.go, auth/client/iam/openid4vp_test.go, docs/_static/auth/v2.yaml, e2e-tests/browser/openid4vp_employeecredential/config/policy/zorgtoepassing.json, e2e-tests/oauth-flow/rfc021/do-test.sh, e2e-tests/oauth-flow/rfc021/node-A/presentationexchangemapping.json, http/user/session.go, vcr/pe/presentation_definition_test.go
=> Backport v6.0: Rename EmployeeCredential to NutsEmployeeCredential

auth/api/iam/api.go, auth/api/iam/api_test.go, auth/api/iam/generated.go, docs/_static/auth/v2.yaml, e2e-tests/browser/client/iam/generated.go
Fixes https://github.com/nuts-foundation/nuts-node/issues/3719
=> Auth: allow client-side access token cache to be bypassed

docs/_static/vcr/vcr_v2.yaml, vcr/api/vcr/v2/api_test.go, vcr/api/vcr/v2/generated.go
This currently leads to a "credential not found" error.
Test case was for a certificate with an é, which lead to a did:x509 DID containing this character, which got double-decoded in the credential ID (because the ID is in format `<issuer DID>#<guid>`).
=> VCR: Fix deleting credential from wallet with encoded characters in ID/DID fails

test/pki/test.go, vcr/credential/validator.go, vcr/credential/validator_test.go, vcr/test/credentials.go, vcr/verifier/signature_verifier_test.go, vcr/verifier/verifier_test.go, vdr/didx509/resolver.go, vdr/didx509/resolver_test.go, vdr/didx509/x509_utils_test.go
Checking the implementation v.s. the spec (https://nuts-foundation.gitbook.io/drafts/rfc/rfc023-x509credential), some touch-ups.
Changes to align to the did:x509 specification:
- Explicitly refer to steps from resolution spec
- Removed the usage of x5t, and just use the first certificate of x5c. 
- Set verification method relationships (key usage) according to certificate key usage
- Error out of certificate key usage is invalid for did:x509 DID usage.
- Added some sanity checks for x5c header (no extra certs, order is correct)
=> did:x509 implementation touch-ups

development/performance_analyzer/Dockerfile
needs a privileged user to run `apk`. No harm in using root here since it is for dev purposes only
=> Use root user in performance analyzer

storage/engine.go, storage/gorm_logger.go, storage/gorm_logger_test.go
Example:
```
sql_query_duration_seconds_bucket{le="0.005"} 310
sql_query_duration_seconds_bucket{le="0.01"} 310
sql_query_duration_seconds_bucket{le="0.025"} 310
sql_query_duration_seconds_bucket{le="0.05"} 310
sql_query_duration_seconds_bucket{le="0.1"} 310
sql_query_duration_seconds_bucket{le="0.25"} 310
sql_query_duration_seconds_bucket{le="0.5"} 310
sql_query_duration_seconds_bucket{le="1"} 310
sql_query_duration_seconds_bucket{le="2.5"} 310
sql_query_duration_seconds_bucket{le="5"} 310
sql_query_duration_seconds_bucket{le="10"} 310
sql_query_duration_seconds_bucket{le="+Inf"} 310
sql_query_duration_seconds_sum 0.018362627000000003
sql_query_duration_seconds_count 310
```
=> #3663: Prometheus metrics for SQL query execution duration

http/requestlogger.go, http/requestlogger_test.go
Example output:
```
INFO[0006] HTTP request   duration_ms=60 method=POST module=http remote_ip=127.0.0.1 status=200 uri=/internal/vdr/v2/subject
```
=> #3663: add latency to HTTP access logging

go.mod, go.sum
fix for https://github.com/nuts-foundation/nuts-node/actions/runs/14615081576/job/41001352749
CVE details https://github.com/nats-io/nats-server/security/advisories/GHSA-fhg8-qxh5-7q3w
Does this need a new release?
=> fix vulnerability v6.1

.github/workflows/codeql-analysis-cron-schedule.yml, .github/workflows/govulncheck-cron-schedule.yaml
These checks run on a schedule. The 'master' schedule only needs to be updated on the main branch.
This disables vulnerability warnings in slack for branch 6.0
=> dropped support for 6.0 and add support for 6.1

.github/workflows/e2e-tests.yaml
This is needed to accept PRs from forks. Consequences might be that we have to ask for a PR to a new branch if a PR is significant.
=> disable e2e tests for PRs from forks

e2e-tests/clustering/redis/docker-compose.yml
=> lock redis to 7 to fix e2e tests
